### ISSUE TITLE
[Question] How many words in words file ?

### ISSUE THREAD

**Issue by supermamie** [JaidedAI/EasyOCR#103]
I plan to rework the french word list (there are many english words in the current one, ane dome are badly written).
I plan on pulling a list from wikipedia (fr.wiktionary.org), but this is huge.

What is best ?
50.000 most used words ?
170.000 common words ?
268.000 words ?

As in the examples there are road signs, which often contains people names in street names, should I also add nouns ?

**Comment by visutida** [comment]
50,000 most used words should be enough. More never hurts. It is also possible to add nouns.
