### ISSUE TITLE
name 'corrupt_msg' is not defined

### ISSUE THREAD

**Issue by RamadanHussein** [JaidedAI/EasyOCR#1054]
Hi,
I'm new to easyOCR , I created a simple code to read text from an image as below, but getting the below error 

"from easyocr import Reader 
import cv2
from matplotlib import pyplot as plt
import numpy as np 

def OCRimg(directory, imagename):
    IMAGE_PATH = directory + '\\' + imagename
    image = cv2.imread(IMAGE_PATH)
    paragraph = True
    languages = ['ar']
    reader = Reader(languages, gpu=False)
    results = reader.readtext(image, detail=0)
    #print(results)
    with open(directory + '\\out.txt', 'w', encoding="utf-8") as f:
        print(str(results), file=f)
    return results

OCRvalue = OCRimg(r'C:\sample', 'x.jpg')
print(OCRvalue)
"

Using CPU. Note: This module is much faster with a GPU.
Traceback (most recent call last):
  File "C:\Users\Ramadan\source\repos\PythonApplication1\PythonApplication1\ImgOCR.py", line 18, in <module>
    OCRvalue = OCRimg(r'C:\Datacap\ArabicOCR918\sample', 'x.jpg')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramadan\source\repos\PythonApplication1\PythonApplication1\ImgOCR.py", line 11, in OCRimg
    reader = Reader(languages, gpu=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ramadan\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyocr\easyocr.py", line 184, in __init__
    LOGGER.warning(corrupt_msg)
                   ^^^^^^^^^^^
NameError: name 'corrupt_msg' is not defined

**Comment by Kamilya2020** [comment]
from easyocr import Reader
import cv2
from matplotlib import pyplot as plt
import numpy as np

def OCRimg(directory, imagename):
    IMAGE_PATH = '/content/a01-000u-s00-00.png'
    image = cv2.imread(IMAGE_PATH)
    paragraph = True
    languages = ['en']
    reader = Reader(languages, gpu=False)
    results = reader.readtext(image, detail=0)
    #print(results)
    with open(directory + '\out.txt', 'w', encoding="utf-8") as f:
        print(str(results), file=f)
    return results

OCRvalue = OCRimg(r'C:\sample', 'x.jpg')
print(OCRvalue)

**Comment by Kamilya2020** [comment]
try it on google colab @RamadanHussein
