### ISSUE TITLE
PIL.Image.ANTIALIAS has been removed in Pillow 10

### ISSUE THREAD

**Issue by ROKOLYT** [JaidedAI/EasyOCR#1072]
Today [July 1st, 2023] Pillow 10.0.0 has been released, and PIL.Image.ANTIALIAS has been removed. Trying to use easyOCR in fresh venv results in crashes due to ANTIALIAS being removed. There are 2 possible and easy fixes:
+ Force Pillow to lower version ```Pillow==9.5.0```
+ Change ANTIALIAS to LANCZOS https://github.com/JaidedAI/EasyOCR/blob/f454d5a85d4a57bb17082c788084ccc64f1f7397/easyocr/utils.py#L572-L577
use ```Image.LANCZOS```

PR https://github.com/JaidedAI/EasyOCR/pull/1050 already fixed it, but hasn't been merged

**Comment by obensustam2** [comment]
Saved my life. Thank you

**Comment by JaidedTeam** [comment]
PR merged.

**Comment by jcrespy** [comment]
I just had the same problem and stumbled upon this. Just so you know, the problem still appears when installing easyocr through pip. I don't know if the fix is supposed to be out or only to appear on next release, so maybe this is expected.
