### ISSUE TITLE
Query on image resolution used for detection and recognition

### ISSUE THREAD

**Issue by tintin-py** [JaidedAI/EasyOCR#1078]
Wonderful project. I have a problem with the documentation [here](https://www.jaided.ai/easyocr/documentation/).
I have observed that the "canvas" parameter in the detection group of parameters takes a single int value (default = 2560). I am wondering if this means the image is resized to a square image or the maximum dimension is resized to the given canvas size while maintaining the aspect ratio. 
Can I get a clarification on this?

**Comment by maxi-w** [comment]
If your image width or height is bigger than that the image will be resized to have the longer side max that value. Aspect ratio is kept during scaling.

If your image is smaller it will not be scaled up. You need to use the mag_ratio for that.

**Comment by tintin-py** [comment]
Alright. Thank you. That solves my problem.
