### ISSUE TITLE
Should common punctuation marks be included in training text?

### ISSUE THREAD

**Issue by srdg** [JaidedAI/EasyOCR#109]
I wanted to know if the common punctuation marks such as , / " : ; ! etc. should be included in the training text (lang_char.txt and lang.txt). Does EasyOCR have a fallback to default language in case the character cannot be found in training text?

**Comment by rkcosmos** [comment]
symbol  = '!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~ ' are included to every languages. No need to add. When character is in the list but not training text/process, EasyOCR will try to give you the closest one (for example, a instead of ā).
