### ISSUE TITLE
Failed to download pretrained models

### ISSUE THREAD

**Issue by ukasyah98** [JaidedAI/EasyOCR#11]
I am having trouble downloading pretrained models from https://jaided.ai/read_download.

Using Google Chrome, I keep getting error "Failed - file incomplete". Is it caused by my internet connectivity? Nope, I have no problem accessing other websites. I think there's an issue with the server.

**Comment by rkcosmos** [comment]
File is large ( >200 Mb) and sometimes people are downloading simultaneously. In my experience, internet stability plays important role.

**Comment by ukasyah98** [comment]
Could you share the files on the other online storage services like Google Drive? Sorry, whenever downloading it, I keep getting same error.

**Comment by rkcosmos** [comment]
here,

[detector weight](https://drive.google.com/file/d/1tdItXPoFFeKBtkxb9HBYdBGo-SyMg1m0/view?usp=sharing)

[latin](https://drive.google.com/file/d/1M7Lj3OtUsaoppD4ZKudjepzCMsXKlxp3/view?usp=sharing)

[chinese](https://drive.google.com/file/d/1xWyQC9NIZHNtgz57yofgj2N91rpwBrjh/view?usp=sharing)

[japanese](https://drive.google.com/file/d/1ftAeVI6W8HvpLL1EwrQdvuLss23vYqPu/view?usp=sharing)

[korean](https://drive.google.com/file/d/1UBKX7dHybcwKK_i2fYx_CXaL1hrTzQ6y/view?usp=sharing)

[thai](https://drive.google.com/file/d/14BEuxcfmS0qWi3m9RsxwcUsjavM3rFMa/view?usp=sharing)
