### ISSUE TITLE
about trainer problem

### ISSUE THREAD

**Issue by ned0929** [JaidedAI/EasyOCR#1112]
i try to train taiwan_vehicle_plate number
but my dataset always have some problem
have someone can deal with it?

this is my test dataset and config files
https://drive.google.com/file/d/1BWGmFOn2BL_-jQUowWbXcD9ZBzrSb-dx/view?usp=drive_link

my dataset have 420 picture,but only 203 picture can be detect
![image](https://github.com/JaidedAI/EasyOCR/assets/74880183/ea26d09d-75b4-447d-9d1b-a179bdd23995)

my val dataset can't be detect
so it always report num_salple = 0

somebody can fix it?
sorry,my English is not very fluent :(

**Comment by MinGiSa** [comment]
can you check dataset.py?

def hierarchical_dataset, class OCRDataset

**Comment by ned0929** [comment]
i deal with it.
at first,I delete char i don't need in config_file,like this
![image](https://github.com/JaidedAI/EasyOCR/assets/74880183/75192b26-73c8-4cb8-aeeb-1214db9114a3)

,but i use default config file,like this
![image](https://github.com/JaidedAI/EasyOCR/assets/74880183/9345a4bc-22c0-4a7d-b2d6-0895cb1a1b60)
 then,i can find all files in dataset，i can countiune train it.but,i still understand why.
