### ISSUE TITLE
Order of OCR Text messed up when specific word is OCRed #help

### ISSUE THREAD

**Issue by tam0w** [JaidedAI/EasyOCR#1147]
![image](https://github.com/JaidedAI/EasyOCR/assets/16761657/28a260bc-e63c-4d6e-8b36-40e43aa4264a)

The orders of those texts are messed up, every single time I have the word 'Skye' in my OCR region.

any idea how to fix this? and any suggestions for parameters / dimension changes to get best ocr output for the given image type

_Originally posted by @tam0w in https://github.com/JaidedAI/EasyOCR/discussions/1146_

**Comment by mahaveerjain98** [comment]
Hi @tam0w , I got the similar issue, i have used sorting of the bounding boxes either from x-axis or y-axis as per your use case. For the above example you can sort by Y-axis of the boundary boxes, which can help you in ordered values. 
Replace detail to 1 from 0 , and take its boundary boxes in a list or a dataframe and sort it

**Comment by tam0w** [comment]
> Hi @tam0w , I got the similar issue, i have used sorting of the bounding boxes either from x-axis or y-axis as per your use case. For the above example you can sort by Y-axis of the boundary boxes, which can help you in ordered values. Replace detail to 1 from 0 , and take its boundary boxes in a list or a dataframe and sort it

thank you
