### ISSUE TITLE
Cannot detect single number

### ISSUE THREAD

**Issue by KirisameVanilla** [JaidedAI/EasyOCR#1157]
as it shows, if I give the whole png, it can recognize the six numbers in the red rectangle. but when i give the single number '0', it returns nothing
![image](https://github.com/JaidedAI/EasyOCR/assets/118162831/7dcd873f-333c-433f-9c4d-5e03b8ef3b9c)

**Comment by tam0w** [comment]
same problem!

**Comment by tam0w** [comment]
hi, i found a solution. 

if you want it to return a value when you only give the number 0, make sure to lower the threshold, text_threshold values to 0 in the readtext parameter for the reader class. CRAFT has issues detecting characters when only single characters are there, so if you lower the threshold for character detection, it will detect it.

**Comment by KirisameVanilla** [comment]
oh, that works! thx!
