### ISSUE TITLE
error in fine tune arabic model 

### ISSUE THREAD

**Issue by OmarEldsouky** [JaidedAI/EasyOCR#1195]
RuntimeError: Error(s) in loading state_dict for DataParallel:
	Missing key(s) in state_dict:
	Unexpected key(s) in state_dict:

**Comment by OmarEldsouky** [comment]
i used arabic.pth 
with these files:
number: '٠١٢٣٤٥٦٧٨٩'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: 'أ ب ت ث ج ح خ د ذ ر ز س ش ص ض ط ظ ع غ ف ق ك ل م ن ه و ي'
experiment_name: 'ar_filtered'
train_data: 'C:\Users\Omar Eldsouky\Downloads\Compressed\EasyOCR-master\EasyOCR-master\trainer\all_data\test'
valid_data: 'C:\Users\Omar Eldsouky\Downloads\Compressed\EasyOCR-master\EasyOCR-master\trainer\all_data\test2'
manualSeed: 1111
workers: 6
batch_size: 32 #32
num_iter: 300
valInterval: 200
saved_model: 'C:\Users\Omar Eldsouky\Downloads\Compressed\EasyOCR-master\EasyOCR-master\trainer\saved_models\arabic.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'C:\Users\Omar Eldsouky\Downloads\Compressed\EasyOCR-master\EasyOCR-master\trainer\all_data' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 256
lang_list:
         - 'ar'
new_prediction: False
and
import torch.nn as nn
from modules.transformation import TPS_SpatialTransformerNetwork
from modules.feature_extraction import VGG_FeatureExtractor, RCNN_FeatureExtractor, ResNet_FeatureExtractor
from modules.sequence_modeling import BidirectionalLSTM
from modules.prediction import Attention

class Model(nn.Module):

    def __init__(self, opt):
        super(Model, self).__init__()
        self.opt = opt
        self.stages = {'Trans': opt.Transformation, 'Feat': opt.FeatureExtraction,
                       'Seq': opt.SequenceModeling, 'Pred': opt.Prediction}

        """ Transformation """
        if opt.Transformation == 'TPS':
            self.Transformation = TPS_SpatialTransformerNetwork(
                F=opt.num_fiducial, I_size=(opt.imgH, opt.imgW), I_r_size=(opt.imgH, opt.imgW), I_channel_num=opt.input_channel)
        else:
            print('No Transformation module specified')

        """ FeatureExtraction """
        if opt.FeatureExtraction == 'VGG':
            self.FeatureExtraction = VGG_FeatureExtractor(opt.input_channel, opt.output_channel)
        elif opt.FeatureExtraction == 'RCNN':
            self.FeatureExtraction = RCNN_FeatureExtractor(opt.input_channel, opt.output_channel)
        elif opt.FeatureExtraction == 'ResNet':
            self.FeatureExtraction = ResNet_FeatureExtractor(opt.input_channel, opt.output_channel)
        else:
            raise Exception('No FeatureExtraction module specified')
        self.FeatureExtraction_output = opt.output_channel  # int(imgH/16-1) * 512
        self.AdaptiveAvgPool = nn.AdaptiveAvgPool2d((None, 1))  # Transform final (imgH/16-1) -> 1

        """ Sequence modeling"""
        if opt.SequenceModeling == 'BiLSTM':
            self.SequenceModeling = nn.Sequential(
                BidirectionalLSTM(self.FeatureExtraction_output, opt.hidden_size, opt.hidden_size),
                BidirectionalLSTM(opt.hidden_size, opt.hidden_size, opt.hidden_size))
            self.SequenceModeling_output = opt.hidden_size
        else:
            print('No SequenceModeling module specified')
            self.SequenceModeling_output = self.FeatureExtraction_output

        """ Prediction """
        if opt.Prediction == 'CTC':
            self.Prediction = nn.Linear(self.SequenceModeling_output, opt.num_class)
        elif opt.Prediction == 'Attn':
            self.Prediction = Attention(self.SequenceModeling_output, opt.hidden_size, opt.num_class)
        else:
            raise Exception('Prediction is neither CTC or Attn')

    def forward(self, input, text, is_train=True):
        """ Transformation stage """
        if not self.stages['Trans'] == "None":
            input = self.Transformation(input)

        """ Feature extraction stage """
        visual_feature = self.FeatureExtraction(input)
        visual_feature = self.AdaptiveAvgPool(visual_feature.permute(0, 3, 1, 2))  # [b, c, h, w] -> [b, w, c, h]
        visual_feature = visual_feature.squeeze(3)

        """ Sequence modeling stage """
        if self.stages['Seq'] == 'BiLSTM':
            contextual_feature = self.SequenceModeling(visual_feature)
        else:
            contextual_feature = visual_feature  # for convenience. this is NOT contextually modeled by BiLSTM

        """ Prediction stage """
        if self.stages['Pred'] == 'CTC':
            prediction = self.Prediction(contextual_feature.contiguous())
        else:
            prediction = self.Prediction(contextual_feature.contiguous(), text, is_train, batch_max_length=self.opt.batch_max_length)

        return prediction

first is YAML file and second is model.py

**Comment by zahrasadat9** [comment]
@OmarEldsouky
hi!
I saw that you trained the model successfully on Arabic data a year ago😅 and I couldn't find anyone else doing so with victory!
please if it's possible respond to this commend! I'm desperate and confused!
first of all, I made some data with [TextRecognitionDataGenerator](https://github.com/Belval/TextRecognitionDataGenerator) repo as they said
then I converted the data with create_lmdb_dataset.py as is explained in [deep-text-recognition-benchmark](https://github.com/clovaai/deep-text-recognition-benchmark) 
using your .yml file, of course changing the dirs etc.
at the time of running the program with the code that [EasyOCR](https://github.com/JaidedAI/EasyOCR) has provided in trainer.ipynb, this error raised:  No such file or directory: '..../labels.csv' (where the train data is)
BUT in nowhere of the whole documentationes of these repos, making a csv file for labels is mentioned !!!!!!
I'm just confused and exhausted and don't know what's wrong...
I really appreciate any help you can provide🙏

**Comment by OmarEldsouky** [comment]
OK, let me find the file and I will upload it to my Github and I will comment the link

**Comment by zahrasadat9** [comment]
@OmarEldsouky thanks a million🤩

**Comment by zahrasadat9** [comment]
> OK, let me find the file and I will upload it to my Github and I will comment the link

Hi! 
as it passes 5 days I thought about sending a reminder 🍀thanks again!

**Comment by Basel-Mohamed** [comment]
Hope you're all doing well, 
Any updates about how to fine-tune EasyOCR?
