### ISSUE TITLE
 Simplified Chinese is recognized as traditional Chinese.

### ISSUE THREAD

**Issue by panxinyang2014** [JaidedAI/EasyOCR#12]
Simplified Chinese is recognized as traditional Chinese.How to solve this problem?

**Comment by rkcosmos** [comment]
We are currently support only one Chinese. If necessary, you can convert the result later to your choice of writing system.

**Comment by panxinyang2014** [comment]
Thanks.  Can I add some simplified Chinese characters?

**Comment by rkcosmos** [comment]
Can you take a look at [zh_char](https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/character/zh_char.txt)? That is the list of all supporting Chinese characters. As I cannot read Chinese myself, maybe you can tell me if they are all traditional Chinese? If you can create a pull request for a list of simplified Chinese characters, I am willing to train another model.

**Comment by panxinyang2014** [comment]
@rkcosmos After my check, most of the zh_char are traditional Chinese characters, but more than 100 of them are simplified Chinese characters.I will create a pull request for a list of simplified Chinese characters a little later. Thanks!

**Comment by rkcosmos** [comment]
Perfect!
