### ISSUE TITLE
Sort textboxes into lines or paragraphs

### ISSUE THREAD

**Issue by Johndirr** [JaidedAI/EasyOCR#121]
It would be nice if the detected text was ordered in the same way someone would read it. Sometimes sentences are scrambled arround and sentences like this "reduce your risk of coronavirus infection" becomes something like "of coronavirus infection reduce your risk".

**Comment by rkcosmos** [comment]
This is a solid request. From bounding box coordinates, we can do clustering algorithm to group and sort. We also have to be careful some languages read from right to left. The real challenge is to do this in such a fast and reliable way. I will open this for coder who want to contribute.

**Comment by rkcosmos** [comment]
done in v1.1.5

**Comment by abhipn** [comment]
> done in v1.1.5

I don't see, how we can get text from document as lines. I have went through the API docs, and was able to find only about paragraph=True argument. Can you provide an example how I can extract text from document and get it line by line (similar to tesseract basic output).

**Comment by kbrajwani** [comment]
Hey guys the line-level detection is done?

**Comment by shivanand3939** [comment]
> > done in v1.1.5
> 
> I don't see, how we can get text from document as lines. I have went through the API docs, and was able to find only about paragraph=True argument. Can you provide an example how I can extract text from document and get it line by line (similar to tesseract basic output).

Same here, I do not see how this is resolved

**Comment by arctic-coder** [comment]
Hi! I had the same problem. I tried different values of `x_ths` and `y_ths`, but it didin't work good for my case (receipts). Post processing using sorting by coordinates was the solution for me:

```
result = reader.readtext(temp_image_path)
     
data = []
for entry in result:
    coordinates, text, confidence = entry
    (tl_x, tl_y), (tr_x, tr_y), (br_x, br_y), (bl_x, bl_y) = coordinates
    data.append([text, tl_x, tl_y, tr_x, tr_y, bl_x, bl_y, br_x, br_y, confidence])

df = pd.DataFrame(data, columns=['text', 'tl_x', 'tl_y', 'tr_x', 'tr_y', 'bl_x', 'bl_y', 'br_x', 'br_y', 'confidence'])

df['mid_y'] = (df['tl_y'] + df['bl_y']) / 2

#  DBSCAN Clustering algo
eps = 5  # !!!!!!! CHANGE IT IF NEEDED !!!!!! max distance to be on one line
dbscan = DBSCAN(eps=eps, min_samples=1, metric='euclidean')
df['line_cluster'] = dbscan.fit_predict(df[['mid_y']])


df_sorted = df.sort_values(by=['line_cluster', 'tl_x'])
grouped_texts = df_sorted.groupby('line_cluster')['text'].apply(lambda words: " ".join(words)).tolist()
extracted_text = "\n".join(grouped_texts)```
