### ISSUE TITLE
Could you give me some advice about the complex text detection task?

### ISSUE THREAD

**Issue by Aflexg** [JaidedAI/EasyOCR#1217]
Hello.I am trying to do the complex text detection task.I want to be able to detect text from images like these, using EasyOCR:
![1](https://github.com/JaidedAI/EasyOCR/assets/153363231/15993a93-b69d-4023-b1a6-7a54190048d5)
![2](https://github.com/JaidedAI/EasyOCR/assets/153363231/152d9e3b-5040-481a-a54f-8a77a5d0d187)
![3](https://github.com/JaidedAI/EasyOCR/assets/153363231/8b222af3-b0eb-4192-9142-eb6fa6ddc638)
![4](https://github.com/JaidedAI/EasyOCR/assets/153363231/0bbc0dda-8700-43ea-8552-a81ba798c4c8)

I made these images greyscale and tried to detect the text by EasyOCR, but the result was bad.Could you give me some advice to improve the result?

Maybe i should apply EasyOcr to the each string separately instead of the whole image ?

Something like these:
![2cut](https://github.com/JaidedAI/EasyOCR/assets/153363231/1cc59454-4b79-45c6-8dbf-94a37e79689a)
![2cut1](https://github.com/JaidedAI/EasyOCR/assets/153363231/d0c7bad5-9307-495c-bff6-455ef63b80cd)

Or like these:
![4cut](https://github.com/JaidedAI/EasyOCR/assets/153363231/83a7a89a-8c64-4eb6-ba28-5ab34d4f3abf)
![4cut1](https://github.com/JaidedAI/EasyOCR/assets/153363231/3f4cc8ac-caf6-4e2d-bfd4-2d9e78ce2a2b)

Or maybe i should try to retrain EasyOCR for my text detection task?If so how can i do that?

Or maybe there is other way to improve the result?

**Comment by magnusahlden** [comment]
I face a similar issues and my only fix to improve it somewhat was to split the pages into sections myself. I find the "craft" implementaton not working very well for me, and I think it might be connected to the fact that my images are text-heavy and rather large (scanned invoices). 

In general I think easyOCR needs to allow more control for segments, as my debugging showed that the main root of the problems was that the segments where missing from most texts except for the top of the page and the bottom of the page.
