### ISSUE TITLE
Error in easyoce.Reader module

### ISSUE THREAD

**Issue by Hassan1175** [JaidedAI/EasyOCR#122]
I am facing issue with easyocr.reader module.
I have successfully imported easyocr, but face issue on following line.

reader = easyocr.Reader(['ch_sim', 'en'])

error is following.

AttributeError: module 'easyocr' has no attribute 'Reader'

**Comment by rkcosmos** [comment]
Do you perhaps have a file name easyocr.py in your folder? looks like it import something else.

**Comment by Hassan1175** [comment]
No, I don't have as such file in my directory. I installed easyocr via pip. Btw, still I am facing the same issue.

**Comment by wantao666** [comment]
i have the same question.and i install the easyocr by `pip install easyocr`. and see the easyocr module by `pip list`.but when i import easyocr by 'import easyocr'.it's wrong and i don't know why and how to reslove it .

**Comment by yashwatwani** [comment]
I named by file as easyocr.py . After changing the filename I got the output.

**Comment by rkcosmos** [comment]
@Hassan1175 @wantao666 Any luck? My first assumption when I see this error is you import another easyocr which can be another file in your system. Delete or rename that file should work like @yashwatwani said.

**Comment by wantao666** [comment]
> i have the same question.and i install the easyocr by `pip install easyocr`. and see the easyocr module by `pip list`.but when i import easyocr by 'import easyocr'.it's wrong and i don't know why and how to reslove it .

@rkcosmos @yashwatwani @Hassan1175 
i have resolved this issue.
my error is that i install the wrong pytorch version with gpu.i should install the pytorch without gpu.
and then i run the easyocr success.

**Comment by ghandic** [comment]
Could this be resolved by adding stricter versions to the requirements.txt and setup.py?

**Comment by wantao666** [comment]
> Could this be resolved by adding stricter versions to the requirements.txt and setup.py?

![image](https://user-images.githubusercontent.com/29670394/88500656-e392a180-cffb-11ea-8f75-6c010c353ec2.png)
i use this pytorch version can run

**Comment by ghandic** [comment]
Could you use the Docker environment?

https://hub.docker.com/repository/docker/challisa/easyocr

If not here is the pip freeze from the Docker environment (note you can also see system dependancies in the Dockerfile):

```txt
asn1crypto==1.3.0
backcall==0.1.0
beautifulsoup4==4.9.0
certifi==2020.4.5.1
cffi==1.14.0
chardet==3.0.4
conda==4.8.3
conda-build==3.18.11
conda-package-handling==1.6.0
cryptography==2.8
cycler==0.10.0
decorator==4.4.2
-e git+https://github.com/JaidedAI/EasyOCR.git@6d6e73f0c3e7bd2ae7c45de8ec4e8467b8b5fc26#egg=easyocr
filelock==3.0.12
future==0.18.2
glob2==0.7
idna==2.8
imageio==2.9.0
ipython==7.13.0
ipython-genutils==0.2.0
jedi==0.16.0
Jinja2==2.11.1
kiwisolver==1.2.0
libarchive-c==2.9
lief==0.9.0
MarkupSafe==1.1.1
matplotlib==3.3.0
mkl-fft==1.0.15
mkl-random==1.1.0
mkl-service==2.3.0
networkx==2.4
numpy==1.18.1
olefile==0.46
opencv-python==4.3.0.36
parso==0.6.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==7.0.0
pkginfo==1.5.0.1
prompt-toolkit==3.0.4
psutil==5.7.0
ptyprocess==0.6.0
pycosat==0.6.3
pycparser==2.19
Pygments==2.6.1
pyOpenSSL==19.1.0
pyparsing==2.4.7
PySocks==1.7.1
python-dateutil==2.8.1
pytz==2019.3
PyWavelets==1.1.1
PyYAML==5.3.1
requests==2.22.0
ruamel-yaml==0.15.87
scikit-image==0.17.2
scipy==1.5.1
six==1.14.0
soupsieve==2.0
tifffile==2020.7.17
torch==1.5.0
torchvision==0.6.0a0+82fd1c8
tqdm==4.42.1
traitlets==4.3.3
urllib3==1.25.8
wcwidth==0.1.9
```

**Comment by rkcosmos** [comment]
I think most of the case is installing pytorch with CUDA when they don't have GPU. I've added a little bit more explanation on Readme. I'll close this for now.

**Comment by ghandic** [comment]
Should we publish two versions, gpu and cpu? Users managing dependancies is always a nightmare

**Comment by rkcosmos** [comment]
Do you mean on Pypi? like pip install easyocr and pip install easyocr_cpu?

**Comment by ghandic** [comment]
Yeah, think that could work?

**Comment by ghandic** [comment]
Ideally, we could push users to make use of Docker, then make two docker environments to showcase how it is used on CPU and GPU

Since the idea with EasyOCR is to lower the barrier to entry

**Comment by Usmaniatech** [comment]
pip install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
install easyocr again and you are good to go.

**Comment by shuhang465** [comment]
> I named by file as easyocr.py . After changing the filename I got the output.

thankyou! i named my python file "easyocr.py", so the code thought that i want to import "easyocr.py", however, i want to import the module "easyocr". this problem confused me an hour. thankyou very much!

**Comment by LegyMax** [comment]
> 
> 
> > I named by file as easyocr.py . After changing the filename I got the output.
> 
> thankyou! i named my python file "easyocr.py", so the code thought that i want to import "easyocr.py", however, i want to import the module "easyocr". this problem confused me an hour. thankyou very much!

same here lol

**Comment by harshitkd** [comment]
> > i have the same question.and i install the easyocr by `pip install easyocr`. and see the easyocr module by `pip list`.but when i import easyocr by 'import easyocr'.it's wrong and i don't know why and how to reslove it .
> 
> @rkcosmos @yashwatwani @Hassan1175 i have resolved this issue. my error is that i install the wrong pytorch version with gpu.i should install the pytorch without gpu. and then i run the easyocr success.

Hey I tried to install PyTorch without GPU and then I also tried to run easyocr, but still its showing me no module named 'easyocr'.

**Comment by Laoli123** [comment]
> > > I named by file as easyocr.py . After changing the filename I got the output.
> > 
> > 
> > thankyou! i named my python file "easyocr.py", so the code thought that i want to import "easyocr.py", however, i want to import the module "easyocr". this problem confused me an hour. thankyou very much!
> 
> same here lol
I is also a day
