### ISSUE TITLE
About textbox parameters

### ISSUE THREAD

**Issue by cjwjy007** [JaidedAI/EasyOCR#128]
Hello,
        I am doing a digital recognition task recently, I found some text boxes were not combined correctly. For example, the number '8973651.46' was detected as [8973651].[46]
        I want to change the threshold to make the text boxes connect together. And I found so many parameters (link_threshold in get_textbox() ,width_ths in group_text_box()  etc.) are influential. I wonder what is the best way to achieve this?
       By the way, it's even greater if the threshold parameters can be accessed outside.
       At last, thanks for the hard work offering such a splendid OCR tool. It's very useful !!

**Comment by rkcosmos** [comment]
I agree those parameters should be tunable from outside. I will make it happen soon. About how to tune, it's trial and error process. Default values are good for general application but it may not be the best for some type of image. You can try tune them on one image and use those set of parameters for the rest of similar images.

**Comment by rkcosmos** [comment]
ok, with [this](https://github.com/JaidedAI/EasyOCR/commit/fe1efd0a3e43317eb4eeffe7d0d6fdfedb270df9). You can now access it from outside via readtext's arguments. 

```
def readtext(self, image, decoder = 'greedy', beamWidth= 5, batch_size = 1,\
                 text_threshold = 0.7, low_text = 0.4, link_threshold = 0.4,\                
                 canvas_size = 2560, mag_ratio = 1., poly = False,\
                 contrast_ths = 0.1,adjust_contrast = 0.5, filter_ths = 0.003,\
                 workers = 0, allowlist = None, blocklist = None, detail = 1):
```

**Comment by cjwjy007** [comment]
Thanks for the quick patch :)

**Comment by cjwjy007** [comment]
Hi,
I have tested the 1.14 code today,  tuning `link_threshold` seems not quite enough for clustering. 
![20200714094319](https://user-images.githubusercontent.com/19515454/87370927-ce0e8800-c5b6-11ea-9415-b3dba57d5064.png)

`horizontal_list, free_list = group_text_box(text_box, width_ths = 0.5, add_margin = 0.1)`
Then I tuned `width_ths` to 0.7, it worked.
![20200714094117](https://user-images.githubusercontent.com/19515454/87371285-948a4c80-c5b7-11ea-9daa-c1a5508abb6d.png)

Could you plz make the 'margin control' parameter `width_ths` accessible as well? If you think that's necessary.

**Comment by rkcosmos** [comment]
yes, that's exactly what I planned to do when I wrote those codes. I almost forgot about this. Will do, thanks for reminding.

**Comment by rkcosmos** [comment]
done by this [commit](https://github.com/JaidedAI/EasyOCR/commit/b626a255b769f5ae204072e222ce528c784a746d)

**Comment by skrish13** [comment]
> 
> 
> ok, with [this](https://github.com/JaidedAI/EasyOCR/commit/fe1efd0a3e43317eb4eeffe7d0d6fdfedb270df9). You can now access it from outside via readtext's arguments.
> 
> ```
> def readtext(self, image, decoder = 'greedy', beamWidth= 5, batch_size = 1,\
>                  text_threshold = 0.7, low_text = 0.4, link_threshold = 0.4,\                
>                  canvas_size = 2560, mag_ratio = 1., poly = False,\
>                  contrast_ths = 0.1,adjust_contrast = 0.5, filter_ths = 0.003,\
>                  workers = 0, allowlist = None, blocklist = None, detail = 1):
> ```

awesome thank you!
