### ISSUE TITLE
Kind of CRNN 

### ISSUE THREAD

**Issue by gautamMalu** [JaidedAI/EasyOCR#129]
Hi,
In https://github.com/clovaai/deep-text-recognition-benchmark/, 
multiple versions of CRNN are provided based on Transformation(TPS/None), FeatureExtracter(VGG, RCNN, Resnet), LSTM, and CTC/Attention. 
Which CRNN are you using to train your Latin model?

**Comment by rkcosmos** [comment]
None+Resnet+LSTM+CTC

**Comment by sasi143** [comment]
@rkcosmos Is it "STAR-Net:TPS-ResNet-BiLSTM-CTC" are you describing

**Comment by rkcosmos** [comment]
No, it's not

**Comment by amitbcp** [comment]
@rkcosmos  in the model.py, it seems to be Bi-LSTM  line 15 of model.py
