### ISSUE TITLE
Support for digit recognition

### ISSUE THREAD

**Issue by dsbyprateekg** [JaidedAI/EasyOCR#130]
Hi,

Is the current version support digit recognition? If not, please add in future release. The OCR to recognize digits from meter is a common but will be very useful case.
Sample cropped  image of a meter screen-
![meter](https://user-images.githubusercontent.com/30830541/87308191-7b8e8680-c538-11ea-9a31-95d248f471b6.JPG)

Currently it is giving following result for above sample image-
![current_result_meter](https://user-images.githubusercontent.com/30830541/87308351-bb556e00-c538-11ea-9d0a-2fe5849b1dd3.JPG)

**Comment by rkcosmos** [comment]
try

`reader.readtext('meter.JPG', allowlist ='0123456789')`

**Comment by dsbyprateekg** [comment]
![error_meter](https://user-images.githubusercontent.com/30830541/87309227-f1dfb880-c539-11ea-8d4c-68e24624ae01.JPG)

**Comment by rkcosmos** [comment]
use last version

`pip install git+git://github.com/jaidedai/easyocr.git`

**Comment by rkcosmos** [comment]
also try zoom out a bit

**Comment by dsbyprateekg** [comment]
Please fix this error-
![error_ocr](https://user-images.githubusercontent.com/30830541/87312077-b941de00-c53d-11ea-85e6-a8cc936cf35a.JPG)

**Comment by rkcosmos** [comment]
my bad, should be fixed now.

**Comment by dsbyprateekg** [comment]
Still getting same error.

**Comment by rkcosmos** [comment]
did you uninstall and reinstall last version? I'm pretty sure it was space after \. and I deleted them all.

**Comment by dsbyprateekg** [comment]
I just rerun `!pip install git+git://github.com/jaidedai/easyocr.git`

**Comment by dsbyprateekg** [comment]
Now it's working but result is not right-
![meter2](https://user-images.githubusercontent.com/30830541/87322391-fbbde780-c54a-11ea-82d5-7647a39075cc.JPG)

**Comment by rkcosmos** [comment]
I think font is too different from training data. I will keep this in mind for next development.

**Comment by eeffoc** [comment]
Thanks, also looking forward to better digit support

**Comment by arezaei2** [comment]
I have the same issue. Was wondering if you guys have fixed this?

Thanks!
Ali

**Comment by shagunkam** [comment]
import easyocr
import cv2
import matplotlib.pyplot as plt

reader = easyocr.Reader(['en'], gpu=False)
image = cv2.imread('mybp3.jpg')
result = reader.readtext(image, detail=0)

Total = []
for (bbox, text, prob) in result:
    Total.append(text)
    (tl, tr, br, bl) = bbox
    tl = (int(tl[0]), int(tl[1]))
    br = (int(br[0]), int(br[1]))
    cv2.rectangle(image, tl, br, (0, 255, 0), 1)
    cv2.putText(image, text, (tl[0], tl[1] - 2), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 0, 0), 1)

plt.rcParams['figure.figsize'] = (16, 16)
plt.imshow(image)
plt.show()

# Print all detected text
for text in Total:
    print(text)
This will help to recognise digits.
