### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by ananitai440** [JaidedAI/EasyOCR#1329]
ERROR

![image](https://github.com/user-attachments/assets/0ceab2e3-0c4a-458c-9a8b-3628bb5fc562)

my code

import pytesseract
import os,easyocr
from PIL import Image

# Path to your image
# Create a reader object
reader = easyocr.Reader(['en'])

# Read the image
result = reader.readtext('1t2.png')

# Print the text
for (bbox, text, prob) in result:
    print(f'{text} (Confidence: {prob})')

**Comment by akachammile** [comment]
It appears that your PyTorch version is relatively high. Downgrading your torch version might resolve the issue.

**Comment by ananitai440** [comment]
I solved self
