### ISSUE TITLE
Brazillian car plates

### ISSUE THREAD

**Issue by TheMasterRoot** [JaidedAI/EasyOCR#136]
there is support for text detection in brazillian car plates?
i was testing in a dataset that i have but the accuracity is to low.

**Comment by rkcosmos** [comment]
Try using allowlist = 'only characters you are interested',

`reader.readtext('plate.jpg', allowlist = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789')`

also try adjust other parameters like contrast_ths, adjust_contrast and filter_ths. I know documentation is not complete yet, it'll come soon.

**Comment by TheMasterRoot** [comment]
thank you im waiting for docs ^^

**Comment by rkcosmos** [comment]
docs is ready. see Readme file
