### ISSUE TITLE
Train on special characters

### ISSUE THREAD

**Issue by WoHinDu** [JaidedAI/EasyOCR#137]
Hi,

thanks for the amazing library! I'm impressed by the results.

For me, it would be necessary to detect special characters which do not directly belong to any language. In particular, I tried to detect the € sign, but had no success. I also tried to whitelist them, but that had no effect. 

Is there any way to detect this kind of signs?

Best

**Comment by rkcosmos** [comment]
You can print all characters in selected model by 
`print(reader.lang_char)`
Unfortunately € sign is not in any model yet, I will try to take this into later model. We also plan to release training process but that's a lot of work and will take some time.

**Comment by amurgit** [comment]
@rkcosmos Could you please also consider about characters like hyphen or minus? Tried recognition on russian, unfortunatly it skip hyphen in the middle, for example "Мак-Клинтока" recognized as "Мак Клинтока".

**Comment by rkcosmos** [comment]
@amurgit I will keep that in mind for next development
