### ISSUE TITLE
RuntimeWarning: divide by zero

### ISSUE THREAD

**Issue by mahanmath** [JaidedAI/EasyOCR#138]
Thanks for all the effort you put in this project!
I encountered the following errors today; it seems divisions are done without error handling:

```
~/miniconda3/lib/python3.7/site-packages/easyocr/recognition.py:24: RuntimeWarning: divide by zero encountered in double_scalars
  ratio = 200./(high-low)
```

```
~/miniconda3/lib/python3.7/site-packages/easyocr/utils.py:385: RuntimeWarning: divide by zero encountered in int_scalars
  theta24 = abs(np.arctan( (poly[3]-poly[7])/(poly[2]-poly[6]) ))
```

**Comment by rkcosmos** [comment]
thanks for reporting, will fix.

**Comment by rkcosmos** [comment]
should be solved by [this commit](https://github.com/JaidedAI/EasyOCR/commit/b626a255b769f5ae204072e222ce528c784a746d)
