### ISSUE TITLE
Train to detect numbers only.

### ISSUE THREAD

**Issue by TheStrugglingEngineer** [JaidedAI/EasyOCR#139]
Hello,

Is it possible to force easyOCR to detect only digits characters 0...9 by eliminating the alphabet characters?

Thank you,
Kind Regards

**Comment by rkcosmos** [comment]
`reader.readtext('yourimg.jpg', allowlist = '0123456789')`

**Comment by TheStrugglingEngineer** [comment]
Yes I finally found it miself, it's whitelist = '0123456789'
