### ISSUE TITLE
Detail error

### ISSUE THREAD

**Issue by Sharan1712** [JaidedAI/EasyOCR#142]
I tried to keep detail is 0 but get an error saying unexpected keyword detail

Code:
reader = easyocr.Reader(['en'],gpu = False)
reader.readtext(np.asarray(image),detail = 0)

TypeError: readtext() got an unexpected keyword argument 'detail'

**Comment by rkcosmos** [comment]
uninstall and reinstall lastest version with

`pip install git+git://github.com/jaidedai/easyocr.git`
