### ISSUE TITLE
readtext() got an unexpected keyword argument 'detail'

### ISSUE THREAD

**Issue by SereneQI** [JaidedAI/EasyOCR#145]
Hello.

When I test the demo code, an error occurs.
`
import easyocr
reader = easyocr.Reader(['ch_sim','en'])
reader.readtext('test1.jpg',detail = 0)
`
It says "TypeError: readtext() got an unexpected keyword argument 'detail'".

I have tried the stable release and the latest development release, but this error still exists.

P.S. I install this package on a news conda environment with python version = 3.7.4.

So, how can I get a simple output? 
Any suggestions would be appreciated.

**Comment by rkcosmos** [comment]
see #142
