### ISSUE TITLE
Reinforcement of training on Korean language.

### ISSUE THREAD

**Issue by YujeongShin570** [JaidedAI/EasyOCR#149]
Hi, there.
I want to increase the accuracy about Korean OCR.
I read that you will upload training process, but did not tell about specific date.
Can you give me the ambiguous date or is there any way to increase the accuracy by myself?

Thank you for your help! : )

**Comment by rkcosmos** [comment]
Training process is on phase2. That's after October, can't promise exact date. You can wait or help me improve your language by trying EasyOCR on some images and report fail cases like this #146 . We can work out the best way to improve accuracy.

**Comment by YujeongShin570** [comment]
@rkcosmos Hi, good morning
I tried to update korean words in easyocr/dict, but there was not ko.txt in the folder. 
My point is that I wonder which dictionary you used to training Korean.

**Comment by rkcosmos** [comment]
I did a mistake of not having dictionary when training japanese and korean. It'll be very helpful if you can send a PR for ko.txt file. I'll use it to train future model.

**Comment by YujeongShin570** [comment]
[ko.txt](https://github.com/JaidedAI/EasyOCR/files/4945247/ko.txt)
Hi, there!
This is korean dictionary file which only includes about 5800 words. Would you add it to easyocr/dict? also, would you notice for me after making the new korean model?
Thank you for your help!

**Comment by rkcosmos** [comment]
File added. I'll keep this issue open and notify you when model is updated.

**Comment by kimlia545** [comment]
Any news?

**Comment by rkcosmos** [comment]
new model released in version 1.3.0.1.
