### ISSUE TITLE
pip install easyocr error

### ISSUE THREAD

**Issue by wangzaogen** [JaidedAI/EasyOCR#151]
hi , I have a question, when i execute  pip install easyocr  ,tips : a error: could not find a version that satisfies the requirement thorchvision>=0.5(from easyocr)

**Comment by rkcosmos** [comment]
torchvision is now version 0.6.1. https://pypi.org/project/torchvision/
Surely >0.5 is possible. you can try `pip install torchvision==0.6.1` first

**Comment by wangzaogen** [comment]
I first execute `pip install torchvision==0.6.1` ,also has error  `ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from torchvision) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)` , but torchvision requirements torch, so it's a loop

**Comment by rkcosmos** [comment]
Are you using Windows/linux or Mac?

**Comment by wangzaogen** [comment]
I first execute pip install torchvision==0.6.1 ,also has error ERROR: Could not find a version that satisfies the requirement torch==1.4.0 (from torchvision) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2) , but torchvision requirements torch, i go on pip install torch ,it was unfortunate that has error  ModuleNotFoundError: No module named 'tools.nnwrap'   so it's a loop

**Comment by rkcosmos** [comment]
for Windows, the [official instruction](https://pytorch.org/) from pytorch ask you to use this 

`pip install torch===1.5.1 torchvision===0.6.1 -f https://download.pytorch.org/whl/torch_stable.html`

that's for CUDA10.2.

**Comment by wangzaogen** [comment]
windows 10

**Comment by wangzaogen** [comment]
thanks ,i can try again

**Comment by wangzaogen** [comment]
using Windows , need to install somethings DDL for torch , can run easyocr?
i see you demo code 
```
import easyocr
reader = easyocr.Reader(['ch_sim','en'])
reader.readtext('poem.jpg', detail = 0)
```
execute this ,has a error ,
```
torch\__init__.py", line 81, in <module> ctypes.CDLL(dll)
ctypes\__init__.py", line 356, in __init__  self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module was not found
```
what's wrong this code

**Comment by rkcosmos** [comment]
I think it's torch's error. Do you have CUDA GPU or it's only CPU? If you are on CPU only. Pytorch installation would be 
`pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by wangzaogen** [comment]
yes, my computer only has CPU

**Comment by hilaloytun** [comment]
Hi Rakpong @rkcosmos 
I have similar problem, I followed the steps you've given it still sgives error, see img: 
![problem torch](https://user-images.githubusercontent.com/35769678/90319267-c552fe00-df36-11ea-9235-06fde7cd5859.jpg)

**Comment by rkcosmos** [comment]
![Screenshot from 2020-08-16 10-51-24](https://user-images.githubusercontent.com/12238328/90326104-83fe3500-dfae-11ea-836d-cf634a9d2896.png)

here's the latest instruction from [official pytorch website](https://pytorch.org).
