### ISSUE TITLE
dataset problems

### ISSUE THREAD

**Issue by JimmyHHua** [JaidedAI/EasyOCR#16]
Hi, this project is so amazing，thank you for your sharing. 

I wanna know if you can share the training dataset for the chinese and english char. 

Thank u again.

**Comment by rkcosmos** [comment]
I'm planning to create open dataset in the future.

**Comment by JimmyHHua** [comment]
> I'm planning to create open dataset in the future.

Thank u, we will waiting for that

**Comment by briliantnugraha** [comment]
Hi @rkcosmos, is there any plan to share the training dataset for thai language? thanks in advance
