### ISSUE TITLE
Insights for the Future

### ISSUE THREAD

**Issue by MohamedAliRashad** [JaidedAI/EasyOCR#164]
Ideas for long term investment in EasyOCR:

1. Real-time Scene Text Detection with Differentiable Binarization. [Paper](https://arxiv.org/abs/1911.08947) -  [Code](https://github.com/MhLiao/DB)
2. What Is Wrong With Scene Text Recognition Model Comparisons? Dataset and Model Analysis. [Paper](https://arxiv.org/abs/1904.01906v4) - [Code](https://github.com/clovaai/deep-text-recognition-benchmark)

**Comment by rkcosmos** [comment]
Nice, the first one has the potential to replace CRAFT. The second one is already in our reference.
