### ISSUE TITLE
This OCR cannot read about image rotated right 90 degrees.

### ISSUE THREAD

**Issue by YujeongShin570** [JaidedAI/EasyOCR#168]
Hi, there
I tested easy ocr about image rotated right 90 degrees as I attached below.
![rotated90degree](https://user-images.githubusercontent.com/58137372/88007180-59a08f80-cb48-11ea-9450-0ed66b56c524.png)

and I got a result as below.
![스크린샷, 2020-07-21 11-46-45](https://user-images.githubusercontent.com/58137372/88007227-7341d700-cb48-11ea-9c1b-4ad6a24964bd.png)

If I want to run the easy ocr for 1000 images which are mixed with aligned well and rotated 90 degrees, is there a function that automatically read rotated image?

Thank you for your help :)

**Comment by rkcosmos** [comment]
We don't have this feature yet. I will consider adding it in the future. The immediate solution is to look at confident scores. You can write something like 

Pseudo-code
```
if mean_confident_score < 0.4:
    new_img = rotate img by 90 degree
    new_result = reader.readtext(new_img)
    calculate new_mean_confident_score
    if new_mean_confident_score > mean_confident_score:
        end_result = new_result
```

**Comment by ghandic** [comment]
Quick fix if you're using text that runs horizontally only:

- width of cropped image should be longer, if in doubt (threshold) see the average of the image to decide whether to rotate or not
- in terms of flipping 180 before text recognition you can train a small model to detect if the cropped image needs flipping.

These could be features to add to the repo.

**Comment by rkcosmos** [comment]
@ghandic Agreed!

**Comment by Jeevan-Kiran-Lenka** [comment]
I would like to work on this issue
