### ISSUE TITLE
character box positions instead of text box positions

### ISSUE THREAD

**Issue by marunguy** [JaidedAI/EasyOCR#169]
Is it possible to get the character box positions instead of text box positions.

* text box position
![image](https://user-images.githubusercontent.com/6366548/88015855-274d5d00-cb5d-11ea-9935-f36d18174c34.png)

* character box position
![image](https://user-images.githubusercontent.com/6366548/88015880-3502e280-cb5d-11ea-9d37-55e71a26d1ef.png)

**Comment by rkcosmos** [comment]
No. If you really want to have character box, i recommend looking into [CRAFT](https://github.com/clovaai/CRAFT-pytorch) or [DB](https://github.com/MhLiao/DB). I'm sure it's possible to extract character box along their process but it's just detection not recognition.

**Comment by marunguy** [comment]
@rkcosmos 
Thanks you for your reply.
Is there a plan to support this function?

**Comment by rkcosmos** [comment]
Unfortunately, no. Trying to recognize character one by one is not practical for most language.
