### ISSUE TITLE
About training dataset

### ISSUE THREAD

**Issue by er778899789** [JaidedAI/EasyOCR#171]
Hi, JaidedAI
I want to practice the training process by myself. Can you share your (Chinese Traditional) training and testing dataset to me(Images and Label.txt)?
According to my test, your chi_tra recognize model's predict accuracy is really good. I want to use your dataset and add additional images and labels for my project to strengthen my performance. Can you help me? Thx!!

**Comment by rkcosmos** [comment]
Dataset will be released in phase 2. See roadmap on readme file.

**Comment by er778899789** [comment]
OK thx @rkcosmos
