### ISSUE TITLE
ocr for digit is weak!!! For example, 1.8 x 2.0 cm will be discerned as 8X2. Ocm; 69HUwill be discerned as G9HIU, how can i correct this model?

### ISSUE THREAD

**Issue by RONG-SONG** [JaidedAI/EasyOCR#183]

**Comment by rkcosmos** [comment]
Thanks for the feedback. We didn't give enough attention to digit. In the near future, we will release a dedicated model for digit+english. We also plan to release the detail about our training process so people can retrain model by themselves but that's after we extend support for several more main languages, fix bug and implement a few more features.

**Comment by pranaymodukuru** [comment]
When can we expect the dedicated digit+english model.. Also, the framework to retrain models on custom datasets
