### ISSUE TITLE
Recognition Model Download Failing

### ISSUE THREAD

**Issue by anindya7** [JaidedAI/EasyOCR#184]
On running it for the first time after installing from pip, the following error is thrown:

```
Downloading detection model, please wait
Download complete
Downloading recognition model, please wait
Traceback (most recent call last):
  File "easy_ocr_test.py", line 22, in <module>
    reader = easyocr.Reader(['ch_sim','en'])
  File "/usr/local/lib/python3.8/site-packages/easyocr/easyocr.py", line 197, in __init__
    urlretrieve(model_url[model_file][0], MODEL_PATH)
  File "/usr/local/Cellar/python@3.8/3.8.2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 286, in urlretrieve
    raise ContentTooShortError(
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 1064592 out of 228790017 bytes>
```

My code: 

`import numpy as np
import imutils
import argparse
import imutils
import cv2
import easyocr

ap = argparse.ArgumentParser()
ap.add_argument("-i", "--image", type=str, default="",
	help="path to input image file")
args = vars(ap.parse_args())

img = cv2.imread(args['image'])
img = imutils.resize(img, width=400)
(h, w) = img.shape[:2]

reader = easyocr.Reader(['en'])
result = reader.readtext(img, detail=1)
print(result)`

**Comment by anindya7** [comment]
Auto-resolved on retry. Possible network issue.

**Comment by figurative666** [comment]
I have tried again many times, but I have not been able to solve, please tell me what is the solution?
