### ISSUE TITLE
Input image channels

### ISSUE THREAD

**Issue by deefrawley** [JaidedAI/EasyOCR#185]
Hi. I tested this by passing a grayscale loaded image via OpenCV and got an error "Invalid number of channels in input image:". Ultimately I wanted to test this with bitonal images too - is this an EasyOCR restriction?

**Comment by ghandic** [comment]
No, that is just the shape of your numpy array, currently you're loading it in and it's looking like 

```python
[
  [[234],[100],[230]],
  [[234],[100],[230]],
  [[234],[100],[230]]
]
```
As an example numpy array of one channel image

You just need to make it a 3 channel image for now by 

```python
new_img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
```

This will make it:

```python
[
  [[234, 234, 234],[100, 100, 100],[230, 230, 230]],
  [[234, 234, 234],[100, 100, 100],[230, 230, 230]],
  [[234, 234, 234],[100, 100, 100],[230, 230, 230]]
]
```

**Comment by deefrawley** [comment]
Ahh, thank you very much!
