### ISSUE TITLE
Docker image for i686

### ISSUE THREAD

**Issue by gs7495945jglolfkgtjoiu** [JaidedAI/EasyOCR#187]
Not sure, if I can enter requests here. 
If possible, I'd like to ask for i686 and Raspberry PI docker images.
Regular install of EasyOCR failed in both cases.

**Comment by rkcosmos** [comment]
At the moment I'm expanding support for other languages. We have plan to focus on cross-platform integration later. For now, I'll just put 'need help' and 'PR welcome' tag here in case there are people who can help.
