### ISSUE TITLE
Questions related to thai dataset

### ISSUE THREAD

**Issue by mmmmmore** [JaidedAI/EasyOCR#19]
Hi ! Thank you for open sourcing your project. May I know which data set did you use to train detection & recognition models ?

**Comment by rkcosmos** [comment]
It is my own dataset.

**Comment by mmmmmore** [comment]
Since you are using CRAFT as the text detector, may I know if it performs well to detect thai text ? The pretrained model you used seems to be trained on non-thai dataset.

**Comment by rkcosmos** [comment]
I plan to release open dataset and its detail later. See [this issue](https://github.com/JaidedAI/EasyOCR/issues/16).
