### ISSUE TITLE
Error in easyocr.Reader with urlretrieve(model_url[model_file][0], MODEL_PATH) 

### ISSUE THREAD

**Issue by z-aliakseyeu** [JaidedAI/EasyOCR#191]
Hello!
Thanks for that amazing library first of all!
Could someone please help to resolve the issue i encountered today only (yesterday and before it was working smoothly).

in my code i have let's say:
```
import easyocr
reader = easyocr.Reader(['id', 'en'])
```
When i run it - i am getting the following error:
```
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
MD5 hash mismatch, possible file corruption
Re-downloading the recognition model, please wait
Traceback (most recent call last):
  File "tryout_easyocr.py", line 5, in <module>
    reader = easyocr.Reader(['id', 'en'])
  File "/usr/local/lib/python3.7/site-packages/easyocr/easyocr.py", line 194, in __init__
    urlretrieve(model_url[model_file][0], MODEL_PATH)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
```

Regardless what language i choose - i face this error in all the environments:
- in mac os runtime
- in docker
- in ubuntu
- in colab https://colab.research.google.com/github/vistec-AI/colab/blob/master/easyocr.ipynb#scrollTo=lIYdn1woOS1n

Diving deeper it tries to download the following file:
`https://www.jaided.ai/read_download/latin.pth`
which i wasn't able to download with wget, curl or browser as well for the same issue. 

Seems https://www.jaided.ai/ resets the connection during download

**Comment by Proteusiq** [comment]
I am running into the same issue

**Comment by z-aliakseyeu** [comment]
@Proteusiq when i downloaded and put files under that folder it says
```
MD5 hash mismatch, possible file corruption
Re-downloading the recognition model, please wait
Traceback (most recent call last):
  File "tryout_easyocr.py", line 5, in <module>
    reader = easyocr.Reader(['en'])
  File "/usr/local/lib/python3.7/site-packages/easyocr/easyocr.py", line 194, in __init__
    urlretrieve(model_url[model_file][0], MODEL_PATH)
  File "/usr/local/Cellar/python/3.7.8/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 288, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 327316 out of 215365830 bytes>
```
Did you face the same issue?

**Comment by z-aliakseyeu** [comment]
Thanks @Proteusiq !

Now the only question i have is how to download Indonesian lang model

**Comment by rkcosmos** [comment]
Indonesian language use latin model. If latin model is downloaded and placed in model directory. You should be able to call
`reader = easyocr.Reader(['id', 'en'])`.

**Comment by z-aliakseyeu** [comment]
Thanks @rkcosmos!
Is there some plans/ideas how to solve it without manual download?
Maybe i can contribute to make it work smoother?

**Comment by rkcosmos** [comment]
I plan to move download part behind Cloudflare and let them handle the traffic.

**Comment by imvladikon** [comment]
The manual download also doesn't work. I checked it (e.g. wget https://www.jaided.ai/read_download/cyrillic.pth -O /content/models/cyrillic.pth and just using a browser download) after several seconds, downloading is interrupted

**Comment by rkcosmos** [comment]
[cyrillic model](https://drive.google.com/file/d/1SBmKXV5dpN5Cekacqk3ms1xq3dGbDuu1/view?usp=sharing)

**Comment by rkcosmos** [comment]
too many people trying to get model, I will move it behind Cloudflare tomorrow, otherwise I'm going to broke because of traffic bill.

**Comment by SiYuan-Lee** [comment]
I encounter the same issue, where can I download the simple Chinese model instead of the Latin model.

**Comment by rkcosmos** [comment]
All links are on README.

**Comment by xhimalaya** [comment]
> I am running into the same issue
> [RESOLVED]
> 
> It is Download issues that happens due to network overload(multiple people trying to download at the same time)
> Solved by directly downloading models and place them to %USERPROFILE%/.EasyOCR/model from
> 
> [detector weight](https://drive.google.com/file/d/1tdItXPoFFeKBtkxb9HBYdBGo-SyMg1m0/view?usp=sharing)
> 
> [latin](https://drive.google.com/file/d/1M7Lj3OtUsaoppD4ZKudjepzCMsXKlxp3/view?usp=sharing)
> 
> See #11



> I am running into the same issue
> [RESOLVED]
> 
> It is Download issues that happens due to network overload(multiple people trying to download at the same time)
> Solved by directly downloading models and place them to %USERPROFILE%/.EasyOCR/model from
> 
> [detector weight](https://drive.google.com/file/d/1tdItXPoFFeKBtkxb9HBYdBGo-SyMg1m0/view?usp=sharing)
> 
> [latin](https://drive.google.com/file/d/1M7Lj3OtUsaoppD4ZKudjepzCMsXKlxp3/view?usp=sharing)
> 
> See #11

can you please tell me where to put those files after downloading???

**Comment by alexpm94** [comment]
@xhimalaya Place them in ~/.EasyOCR/model. That directory is created when easyocr is installed.

**Comment by Prasang13** [comment]
While downloading the model, I am facing this issue.
![image](https://user-images.githubusercontent.com/15967484/88997215-c6681680-d30c-11ea-85aa-3e66fcca8277.png)

**Comment by rkcosmos** [comment]
sorry, my website is down

**Comment by rkcosmos** [comment]
it should be up now.

**Comment by Prasang13** [comment]
nope, still not working

**Comment by rkcosmos** [comment]
not sure what's going on. At least website is up. You can also try manual download links from google drive. The links are on README.

**Comment by Vijayabhaskar96** [comment]
A Suggestion to @rkcosmos  You can host the models on https://gofile.io and add the direct download link as a mirror link to it so that if the model fails to download from your website it can retry to download from Gofile.io for the meantime till you host the models on Cloudflare.

**Comment by rkcosmos** [comment]
thanks for the suggestion, it's already behind CDN. Good to know the alternative.

**Comment by imvladikon** [comment]
I think there is way to do it like in the spacy package and model for spacy. They just provide models through assets on the github and module for [downloading ](https://github.com/explosion/spaCy#download-models) it e.g. https://github.com/explosion/spaCy/releases/tag/v2.3.0 and another option is just google drive (retrieving using https://pypi.org/project/gdown/)

**Comment by rkcosmos** [comment]
@imvladikon @Vijayabhaskar96 At the end, cloudflare doesn't allow heavy download traffic. I end up with downloading from google drive. thanks for ur suggestion.
