### ISSUE TITLE
HTTP Error 403: Forbidden

### ISSUE THREAD

**Issue by pr2tik1** [JaidedAI/EasyOCR#195]
Issue showed:
---

Downloading detection model, please wait

HTTPError                                 Traceback (most recent call last)
<ipython-input-16-ca0f38143924> in <module>()
      1 import easyocr
----> 2 reader = easyocr.Reader(['en'])

7 frames
/usr/lib/python3.6/urllib/request.py in http_error_default(self, req, fp, code, msg, hdrs)
    648 class HTTPDefaultErrorHandler(BaseHandler):
    649     def http_error_default(self, req, fp, code, msg, hdrs):
--> 650         raise HTTPError(req.full_url, code, msg, hdrs, fp)
    651 
    652 class HTTPRedirectHandler(BaseHandler):

HTTPError: HTTP Error 403: Forbidden

Why is it forbidden? I have done installation with this command as asked in README
> pip install easyocr

The code executed: 

import easyocr
reader = easyocr.Reader(['en'])

Running either on Colab and Local, both give the same error.

**Comment by rkcosmos** [comment]
downloaded issue should be fixed in the lastest update. To use last version, you need to uninstall first
`pip uninstall easyocr`

and install directly from source code
`pip install git+git://github.com/jaidedai/easyocr.git`

**Comment by pr2tik1** [comment]
Works fine on that change, Thank-you !

**Comment by liebig** [comment]
This is not working for me:
```ERROR: Cannot install easyocr and easyocr==1.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    easyocr 1.2.1 depends on torch
    torchvision 0.5.0 depends on torch==1.4.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies

```

**Comment by egeres** [comment]
I'm also experiencing the same issue as @liebig

**Comment by ShahzebAnsari** [comment]
Me to facing the same issue as @liebig

**Comment by z655062** [comment]
I have same question as @liebig

**Comment by rkcosmos** [comment]
hi everyone, it looks like dependency problem. Can you try to install pytorch and torchvision first by following their official instruction [here](https://pytorch.org/). And then install easyocr again.

**Comment by z655062** [comment]
it can work! thanks @rkcosmos

**Comment by PramodMonangi** [comment]
> hi everyone, it looks like dependency problem. Can you try to install pytorch and torchvision first by following their official instruction [here](https://pytorch.org/). And then install easyocr again.

This worked! Thanks a lot.
