### ISSUE TITLE
ONNX

### ISSUE THREAD

**Issue by ApurvaDani** [JaidedAI/EasyOCR#196]
I am trying to export the CRNN model which takes two inputs to ONNX format.

This is what I tried:
------------------------------------------------
text = torch.LongTensor(1, 39).fill_(0).to(device)
image = torch.randn(1, 1, 64, 384, requires_grad=True)

torch.onnx.export(model,
(image, text),
"model_onnx.onnx",
export_params=True,
opset_version=11,
do_constant_folding=True,
input_names = ['input1','input2'],
output_names = ['output'],
dynamic_axes = {'input1':{0:'batch_size',2:'height', 3:'width'}, 'output':{0:'batch_size'}})

But it throws an error:
RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible

---------------------------------------------------------
How can I export the CRNN model to ONNX?

**Comment by rkcosmos** [comment]
I don't have any experience with ONNX yet. We plan to export models to ONNX in phase 2 of development. (see readme)

**Comment by masgh021** [comment]
is it possible use it with c# ???????

**Comment by RyanCCC** [comment]
> I am trying to export the CRNN model which takes two inputs to ONNX format.
> 
> ## This is what I tried:
> text = torch.LongTensor(1, 39).fill_(0).to(device)
> image = torch.randn(1, 1, 64, 384, requires_grad=True)
> 
> torch.onnx.export(model,
> (image, text),
> "model_onnx.onnx",
> export_params=True,
> opset_version=11,
> do_constant_folding=True,
> input_names = ['input1','input2'],
> output_names = ['output'],
> dynamic_axes = {'input1':{0:'batch_size',2:'height', 3:'width'}, 'output':{0:'batch_size'}})
> 
> But it throws an error:
> RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
> 
> How can I export the CRNN model to ONNX?

I meet the same problem too. Have you solved it?

**Comment by masgh021** [comment]
Hello
i am interested to this position

**Comment by ziyeZzz** [comment]
> > I am trying to export the CRNN model which takes two inputs to ONNX format.
> > ## This is what I tried:
> > text = torch.LongTensor(1, 39).fill_(0).to(device)
> > image = torch.randn(1, 1, 64, 384, requires_grad=True)
> > torch.onnx.export(model,
> > (image, text),
> > "model_onnx.onnx",
> > export_params=True,
> > opset_version=11,
> > do_constant_folding=True,
> > input_names = ['input1','input2'],
> > output_names = ['output'],
> > dynamic_axes = {'input1':{0:'batch_size',2:'height', 3:'width'}, 'output':{0:'batch_size'}})
> > But it throws an error:
> > RuntimeError: Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible
> > How can I export the CRNN model to ONNX?
> 
> I meet the same problem too. Have you solved it?

Have you solved it?
