### ISSUE TITLE
How do I predict a batch of images to speed up model prediction

### ISSUE THREAD

**Issue by JoeZhou1025** [JaidedAI/EasyOCR#199]
Hi All!
Any suggestions on loading a batch of images?

**Comment by rkcosmos** [comment]
You can set `batch_size` like this `reader.readtext('img.jpg', batch_size = 4)`. Read more on API documentation section on README file.

**Comment by JoeZhou1025** [comment]
Thanks! But only on recognition part, how to make the detection part also predict batch by batch

**Comment by rkcosmos** [comment]
I see, we didn't have that feature because recognition is slower (most of the time).
