### ISSUE TITLE
Did you use LSTM or BiLSTM?

### ISSUE THREAD

**Issue by YujeongShin570** [JaidedAI/EasyOCR#204]
When I read readme file,
![image](https://user-images.githubusercontent.com/58137372/89384959-e139f100-d739-11ea-825b-19517bfeaa80.png)
I understood that you used LSTM for sequencemodeling. However, when I opened model.py,
![image](https://user-images.githubusercontent.com/58137372/89385105-121a2600-d73a-11ea-9032-0840453d86a2.png)
it seems like you imported BiLSTM. Thus, I am little bit confused that which one did you use for sequencemodeling.

**Comment by rkcosmos** [comment]
it's BiLSTM.
