### ISSUE TITLE
how to recognition MultiLine word???

### ISSUE THREAD

**Issue by swy0915** [JaidedAI/EasyOCR#205]
![image](https://user-images.githubusercontent.com/16319211/89390989-25c58c80-d73a-11ea-8643-164c67f0f550.png)
how to recognition MultiLine word?

**Comment by rkcosmos** [comment]
set `paragraph =True`, see API documentation on readme for more detail

**Comment by swy0915** [comment]
thank you very much! 

raw_result is several result,  function 'get_paragraph' combine them .
