### ISSUE TITLE
Different unicode for the same abkhazian character

### ISSUE THREAD

**Issue by danielinux7** [JaidedAI/EasyOCR#206]
Hello,
The issue is different unicode for the same abkhazian character:
Ԥԥ <--> Ҧҧ
Ӷӷ <--> Ҕҕ
Is there an easy way to implement this?

**Comment by rkcosmos** [comment]
Do you mean Ԥ vs Ҧ (also Ӷ vs Ҕ and their smaller couterpart) are actually the same character? That would complicate things a bit but it's still doable. I would just choose one version and replace another with the chosen one everywhere. Are there other characters like this apart from this 4 sets?

**Comment by danielinux7** [comment]
Yes, they are the same characters, just those 4 sets.

**Comment by danielinux7** [comment]
@rkcosmos just a reminder once you start training to add those characters because people are still using them.
