### ISSUE TITLE
increase the accuracy of the Japanese language

### ISSUE THREAD

**Issue by ducbluee** [JaidedAI/EasyOCR#209]
![1596880352 129928](https://user-images.githubusercontent.com/48615021/89707444-25c2c800-d998-11ea-8eb4-ff943a8601b0.png)
![1596880627 6829991](https://user-images.githubusercontent.com/48615021/89707455-396e2e80-d998-11ea-9373-ed2ba46209c1.png)
Currently, I have noticed that there are a few cases where the text looks very clear but the reading is not very accurate so I can get help.
with the first picture predicted out : 東レエJゴ_アリコゴ\"梯式会社
with the second image predicted:  株式会社ほほねぐり

**Comment by rkcosmos** [comment]
We plan to retrain Japanese model soon. Temporary fix for a case like this is to use allowlist or blocklist. for example, 
`reader.readtext('jap.jpg', blocklist = '!"#$%&\'()*+,-./:;<=>?@[\\]^_{|}~abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789')`

**Comment by ducbluee** [comment]
I have added the blocklist as you said but the prediction accuracy still hasn't improved. The prediction result remains unchanged. Please help me
