### ISSUE TITLE
Link refiner from CRAFT

### ISSUE THREAD

**Issue by mahanmath** [JaidedAI/EasyOCR#21]
First of all, thanks for making this tool! It's a great combination of powerful methods for text detection/recognition tasks.

I was wondering if the [link-refiner model from CRAFT](https://github.com/clovaai/CRAFT-pytorch/blob/e332dd8b718e291f51b66ff8f9ef2c98ee4474c8/test.py#L91) is intentionally omitted from the code. Otherwise, I'd be happy to make a PR for adding it.

**Comment by rkcosmos** [comment]
Yes, it's intentional. In my test (may not be very extensive), model without refiner is good enough.
