### ISSUE TITLE
Add more Devanagari languages (Bihari)

### ISSUE THREAD

**Issue by GokulNC** [JaidedAI/EasyOCR#212]
The Devanagari model that's present can also work with the following additional languages:

|Language|ISO 639-3|
|----------|---------|
|Bihari|bh|
|Maithili|mai|
|Angika|ang|
|Bhojpuri|bho|
|Magahi|mah|
|Nagpuri|sck|
|Newari|new|
|Goan Konkani|gom|

Please add the language codes to map to Devanagari.

Or if you feel it's clumsy with many languages, just add a lang_code called `devanagari` to your lang_list.

**Comment by rkcosmos** [comment]
Oh I didn't know India has so many languages. I prefer language code just to be consistent with others. Are they all use exactly same script without any additional characters? Do they use different words? (I'm trying to understand, how can I differentiate one language from another.)

**Comment by GokulNC** [comment]
> _I prefer language code just to be consistent with others._

Yes, the language codes I have quoted are ISO 639-3 and has no conflicts.

> _Are they all use exactly same script without any additional characters?_
Yes, same Devanagari script.

> _Do they use different words?_
Yes. But unless you're using a language model on top of your recognizer, it doesn't matter.
Because the script is consistent.

> _how can I differentiate one language from another?_
For the purpose of recognition, you can just map all those language codes under the `devanagari_lang_list` variable here:
https://github.com/JaidedAI/EasyOCR/blob/023d773de5d9feb1e893a3a393e60654a7a51bd8/easyocr/easyocr.py#L41

**Comment by GokulNC** [comment]
Great, thanks!

**Comment by GokulNC** [comment]
@rkcosmos 
Can you please also link the following languages to the Devanagari model?
- Haryanvi (ISO Code: `bgc`)
- Sanskrit (ISO Code: `sa`)

**Comment by GokulNC** [comment]
Also, please link the Manipuri language (code: `mni`) with the Bengali script.
