### ISSUE TITLE
UnboundLocalError: local variable 'img' referenced before assignment

### ISSUE THREAD

**Issue by GokulNC** [JaidedAI/EasyOCR#216]
Location: https://github.com/JaidedAI/EasyOCR/blob/914b164626959b479b0e5c3ace0c23297b8735d1/easyocr/easyocr.py#L316

Error: `UnboundLocalError: local variable 'img' referenced before assignment`

Reason: I passed the image read using `imageio.imread()` 

Solution: Please add an `if` case for that.

**Comment by rkcosmos** [comment]
It looks like imageio gives RGBA instead of RGB as a default. Fine, I can add a case for that. If you want to help, PR is also welcome.

**Comment by DMAgit** [comment]
Bump, getting the same issue.
