### ISSUE TITLE
API Support for running only Detector and only Recognizer separately

### ISSUE THREAD

**Issue by GokulNC** [JaidedAI/EasyOCR#217]
Request 1: Detection only.

An API like this:
```
import easyocr
detector = easyocr.Detector(args)
result = detector.detect(img)
```

Request 2: Recognizer only

An API like this:
```
import easyocr
recognizer = easyocr.Recognizer(args)
text, confidence  = recognizer.recognize(img_crop)
```

**Comment by rkcosmos** [comment]
looks reasonable, I will add them in future version

**Comment by GokulNC** [comment]
Will you be fine with a PR?
I'll do some restructuring of `easyocr.py` to make it a bit more generic and extendable.

**Comment by rkcosmos** [comment]
feature added in v1.1.9.
