### ISSUE TITLE
Data Requirement

### ISSUE THREAD

**Issue by ApurvaDani** [JaidedAI/EasyOCR#218]
I want to train this model for handwritten digits only. What should be the ideal data requirement for training the network for numbers only?
This is the kind of data, I want to train the model on.
![image](https://user-images.githubusercontent.com/37484263/89997660-0d112580-dcaa-11ea-942f-654dba25745a.png)

**Comment by rkcosmos** [comment]
You need a lot of images like that + their ground truth label.
