### ISSUE TITLE
Problem in detect the letter A on a particular font

### ISSUE THREAD

**Issue by RitanMihai** [JaidedAI/EasyOCR#219]
I got a problem with the recognition on this font (image below), to be precise always on letter **_A_** (I did not find the exact font) that is detected as letter P almost all the time, I mean one time I got the letter R, but never the right answer.

![text](https://user-images.githubusercontent.com/38959302/90092082-ab47ce80-dd30-11ea-8905-80bd6980da3e.jpg)

Any solutions? Can more fonts be supported? And how to add one if yes?

**Comment by rkcosmos** [comment]
We don't support training new model yet. However, we plan to extend our support in phase 2 (around end of this year).
