### ISSUE TITLE
GPU is not working.

### ISSUE THREAD

**Issue by gregcho** [JaidedAI/EasyOCR#22]
Hello.
I finally find good project for me. 
but I have 1 issue using GPU, CPU version is fine.

when I load program like this.
```
    read = easyocr.Reader(['en'])
    text = read.readtext('D:/workspace/EasyOCR-master/examples/4.jpg')
    print(text)
```

I got this message :
**RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu**

**Comment by gregcho** [comment]
I have two GPU.

- GeForce GTX 1070 Ti
- pytorch version : 1.5.1

**Comment by rkcosmos** [comment]
Can you try specify which gpu to be used by using gpu = 'your gpu' argument? See [this ssue](https://github.com/JaidedAI/EasyOCR/issues/10).

**Comment by gregcho** [comment]
'your gpu' argument means gpu number?

**Comment by rkcosmos** [comment]
Something like 'cuda:0' or 'cuda:1'. See [this discussion on pytorch](https://discuss.pytorch.org/t/selecting-the-gpu/20276).

**Comment by gregcho** [comment]
It is not work for me ..

**Comment by gregcho** [comment]
thanks!
