### ISSUE TITLE
Support Caucasian group of languages(10) that use Cyrillic

### ISSUE THREAD

**Issue by danielinux7** [JaidedAI/EasyOCR#220]
This group of languages:  _Abaza, Adyghe,  Kabardian, Avar, Dargwa, Ingush,  Chechen, Lak, Lezgian, and Tabassaran_ are using a combination of the Russian alphabet in addition to one letter [Ӏ(Palochka)](https://en.wikipedia.org/wiki/Palochka#Usage)
How can this be supported? (I could provide you with a dictionary with one of the languages that has this additional letter)

**Comment by rkcosmos** [comment]
This Palochka is going to be confused with I (capital i) for sure. They looks exactly the same for me. How can native speaker know which one id used or they probably don't have capital i in their system?

**Comment by danielinux7** [comment]
They don't have the capital i  in their alphabet.
This group of languages have their alphabet based on the Russian alphabet in addition to the Palochka.

**Comment by rkcosmos** [comment]
Ok, this is doable. I will add support for this set in the next release. For dictionary, it's not necessary right now but it can be used in further development later.

**Comment by danielinux7** [comment]
I will work on adding adyghe dic and char for now.
(One of the languages of the group.)
