### ISSUE TITLE
Running on mobile devices

### ISSUE THREAD

**Issue by amelmusic** [JaidedAI/EasyOCR#222]
First of all, thank you for your great work!

It would be great if we can enable running easyocr on the mobile phone. Currently we are using ML KIT from google to do the OCR on device itself.

I would love to help if someone can point me where to start digging in order to enable easyocr to work on mobile.

**Comment by rkcosmos** [comment]
The current model is probably too large for mobile. There's a plan to create lite version. Then we have to export Pytorch model to mobile platform (either TFlite or pytorch mobile (https://pytorch.org/mobile/home/)).

**Comment by mbrissier** [comment]
I am currently working on compiling the model into a torchscript model for mobile support. But it is not that easy, because torchscript brings limitation due to compiling in c++. I have to restructure the code, in order to get this working and remove/replace unsupported elements. I'll keep you updated and would appreciate help as well.

**Comment by Kromtar** [comment]
Hello, any news about this?
I am looking to make a compiled version of a Python program that implements EsayOCR. Any recommendations on how I should use torchscript to optimize the weight?

**Comment by bit-scientist** [comment]
Hello @Kromtar, @amelmusic , @rkcosmos. Did you you guys manage to develop a mobile version for easy OCR?

**Comment by Kromtar** [comment]
Hi @bit-scientist , in [this thread](https://github.com/JaidedAI/EasyOCR/issues/746) I explain a way to export and run the models with [ONNX](https://onnx.ai/).

ONNX can be run on mobile devices. 

Unfortunately some people are having errors following the guide. Hopefully this week I will be able to fix them.
