### ISSUE TITLE
Documentation uplift

### ISSUE THREAD

**Issue by ghandic** [JaidedAI/EasyOCR#224]
Something to add into the roadmap just some thoughts (happy to start work on this):

- readthedocs page
- Docstring coverage
- Add in typing to aid in autocomplete
- Add which versions of Python we're supporting in setup.py 
- Links to any functionality detailing how it works (eg add CRAFT paper into docstring, beamsearch use etc)
- For packaging perhaps we can add in optional functionality similar to [smart_open](https://github.com/RaRe-Technologies/smart_open/blob/develop/setup.py) where they have `pip install smart_open  // Install with no cloud dependencies` and `pip install smart_open[aws] // Install AWS deps` [Probably a seperate issue and PR]

**Comment by rkcosmos** [comment]
>     readthedocs page

We already have a [website](https://www.jaided.ai/easyocr). It's currently simple but getting better.

>     Docstring coverage
>     Add in typing to aid in autocomplete
>     Links to any functionality detailing how it works (eg add CRAFT paper into docstring, beamsearch use etc)

yes, please create a PR.

>     Add which versions of Python we're supporting in setup.py

I'm too lazy to test every releases on different Python versions, perhaps do it later after coding is more stabilized.

**Comment by ghandic** [comment]
Should be able to test on all versions of Python through Docker and automated CI/CD tests - can try to create a PR for this?

For the docstrings etc I'll have a crack and get the majority of it in there and add some TODO tags if there's any parts that I'm unclear on.

Started a Gitter channel so can chat more on there

**Comment by ghandic** [comment]
@rkcosmos from looking at requirements.txt skimage needs python 3.6+ so all of our code that supports python2 is redundant

**Comment by rkcosmos** [comment]
There are people using EasyOCR with python2. Some package may not officially support python2 but they are still usable. I would just avoid implementation that break python2 support.
