### ISSUE TITLE
Vertical text - Japanese

### ISSUE THREAD

**Issue by wernerchao** [JaidedAI/EasyOCR#227]
Hi, for group 7, Japanese version 2 + vertical text, is there a timeline on this?
I'd like to offer my help to train this vertical Japanese text model, as I've tried the current Japanese model on vertical text without much success.
Sorry if I'm not raising the issue correctly, this isn't a new language so I didn't attach the characters/words files.

**Comment by rkcosmos** [comment]
Current model doesn't support vertical text. The plan is to release new model within October this year. We don't need additional file for vertical Japanese.

**Comment by msameedkhan** [comment]
@rkcosmos does the model is going to support vertical text for english language also apart from japanese?

**Comment by wernerchao** [comment]
@rkcosmos just following up on this and offering help if you need any to get this done. Thank you for the great work.

**Comment by javad-centan** [comment]
@rkcosmos I can also help you for Japanese V2.
