### ISSUE TITLE
Train my own model

### ISSUE THREAD

**Issue by zy974400763** [JaidedAI/EasyOCR#228]
Thanks for your project.
I want to ask how to train my own model.

**Comment by YujeongShin570** [comment]
Author says in the one issue, he follows https://github.com/clovaai/deep-text-recognition-benchmark.

**Comment by amitbcp** [comment]
@rkcosmos  can you please specify the parameters you used to create the training data using : https://github.com/Belval/TextRecognitionDataGenerator 

I am training my model for latin using the same architecture as the one in EasyOCR and clovai. It would be helpful if dataset creation was possible

**Comment by rkcosmos** [comment]
I am not using his vanilla version. I modified a lot.

**Comment by amitbcp** [comment]
@rkcosmos , sorry i got confused. I understood the modification you made on the Recognition model. 
Did you make changes in the text-generator as well to create your custom dataset ?

**Comment by rkcosmos** [comment]
Yes, everything needs modification to make it works properly, except CRAFT.

**Comment by amitbcp** [comment]
Thankyou so much !
