### ISSUE TITLE
Problem while compiling

### ISSUE THREAD

**Issue by YaKalmar0** [JaidedAI/EasyOCR#23]
Hi there!

So I get the error while compiling code "reader = easyocr.Reader(['en'])".
This is the error:
File "/Users/yakalmar/anaconda3/lib/python3.6/site-packages/torch/serialization.py", line 814, in restore_location
    result = map_location(storage, location)
TypeError: 'bool' object is not callable

Don't you know how I can fix it?
Thank you in advance

**Comment by rkcosmos** [comment]
which pytorch version are you using?

**Comment by YaKalmar0** [comment]
> which pytorch version are you using?

I am using torch 1.3.1 version.

**Comment by rkcosmos** [comment]
I'm not sure. Probably has something to do with pytorch or pickle version. See [this pytorch issue](https://github.com/pytorch/pytorch/issues/32289). I would try to upgrade pytorch to see if it helps.

**Comment by nvlong21** [comment]
problem in https://github.com/JaidedAI/EasyOCR/blob/286ec6de4894e9a8b9a4dbbd845a498a4a8d2e0e/easyocr/easyocr.py#L51

**Comment by YaKalmar0** [comment]
> problem in
> 
> https://github.com/JaidedAI/EasyOCR/blob/286ec6de4894e9a8b9a4dbbd845a498a4a8d2e0e/easyocr/easyocr.py#L51
> 
> 
> fix it:
> ```
>         if gpu == True and torch.cuda.is_available(): self.device = 'cuda'
>         elif gpu == False or (not torch.cuda.is_available()):
>             self.device = 'cpu'
>             print('Using cpu, this module is much faster with gpu')
>         else: self.device = gpu
> ```

Yes, it worked! Thank you.
