### ISSUE TITLE
Please add bangla language

### ISSUE THREAD

**Issue by mesadhan** [JaidedAI/EasyOCR#233]
Please add the Bengali language with an example. I didn't find any helpful articles or examples that can help me. I used tesseract ocr but didn't get proper output. For tesseract ocr I need to do lots of pre-processing. Like image to text area segmentation and crop those areas then need to apply noise reduction.

**Comment by rkcosmos** [comment]
I just added support for Bengali yesterday (v1.1.8, note that it is not on pip package yet, you can install from source code). And here is a [tutorial](https://www.jaided.ai/easyocr/tutorial).
