### ISSUE TITLE
Failed on scanned receipts

### ISSUE THREAD

**Issue by tulasiram58827** [JaidedAI/EasyOCR#235]
Easy ocr not working well on scanned receipts. I am attaching the sample output. 
If I need to do any preprocessing for this kind of images please let me know.

FYI : The image which I used to detect text is from ICDAR 2015 SROIE dataset.

Thanks

![response](https://user-images.githubusercontent.com/27290902/91125168-b7cc0f80-e6be-11ea-9557-a18ad87b7835.jpeg)

**Comment by rkcosmos** [comment]
It looks like contrast is too low. Can you send me this original image?

**Comment by tulasiram58827** [comment]
![624](https://user-images.githubusercontent.com/27290902/91149949-59605a80-e6d9-11ea-968a-5c008f82eb89.jpg)

**Comment by tulasiram58827** [comment]
Or you can share you email id. So that i can directly mail you

**Comment by tulasiram58827** [comment]
@rkcosmos Can you check once

**Comment by rkcosmos** [comment]
sorry for late reply. I just tested it. The result is indeed very poor. The model didn't trained with data like this. I will keep this in mind for next model.
