### ISSUE TITLE
PR? readtext() option for detection- and recognition-only mode

### ISSUE THREAD

**Issue by AlexKuhnle** [JaidedAI/EasyOCR#239]
Hi,

I've modified the code to enable detection- and recognition-only calls to `Reader.readtext()`, see [here](https://github.com/AlexKuhnle/EasyOCR/commit/6eeed0bf9528049e0bf34f41fcc6e3e22ae898c6). More precisely, specifying `no_recognition=True` will skip the recognition step and just return the detected boxes, whereas passing boxes via `text_boxes=[...]` will skip the detection step and return corresponding recognized text.

Let me know if you would be interested in a PR.

**Comment by rkcosmos** [comment]
thanks, I'm doing the same thing in a little bit different way.
