### ISSUE TITLE
Can text region detection and text recognition be used separately?

### ISSUE THREAD

**Issue by yonghwan1994** [JaidedAI/EasyOCR#240]
Hello, thank you for your great research.

I need to separate text region detection and text recognition to improve the overall speed of my program.

Is there a way to separate the two steps in EasyOCR?

Like, 

1) just text region detection and no subsequent steps. 

2) And vice versa, do only text recognition in the found text area without detecting text area 

I would appreciate it if you let me know.

**Comment by rkcosmos** [comment]
I'm working on this. Code is already ready. Documentation will follow very soon.

**Comment by rkcosmos** [comment]
documentation here https://www.jaided.ai/easyocr/documentation

**Comment by bharatsubedi** [comment]
@rkcosmos is it possible to predict only some characters like 1234ABCD?
