### ISSUE TITLE
Information about training dataset for latin characters

### ISSUE THREAD

**Issue by zhaobozb** [JaidedAI/EasyOCR#244]
Hi there,

Thanks for your great work! Althrough I know you will open the training dataset in phase 2, could you share more information about your training dataset for latin characters recognition for now? I know possible dataset includes:
1. MJSynth Dataset
2. SynthText in the Wild Dataset
3. Text generated by TextRecognitionDataGenerator

Do you use the aboved datasets train your latin model?

Thank you very much!

**Comment by rkcosmos** [comment]
Only the third one with some modifications.
