### ISSUE TITLE
Does not recognize digit '7'

### ISSUE THREAD

**Issue by lagerfeuer** [JaidedAI/EasyOCR#254]
I've been trying to read some Sudokus and so far all digits have been recognized except 7.
Is this a font issue maybe? All the images I have tried, no 7 was recognized.

**Edit: Maybe related** #130 

## Example:
[Link to the image](https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Sudoku-by-L2G-20050714.svg/1200px-Sudoku-by-L2G-20050714.svg.png)
```shell script
 curl -o sudoku.png https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Sudoku-by-L2G-20050714.svg/1200px-Sudoku-by-L2G-20050714.svg.png
 easyocr -l en -f sudoku.png
```
```
([[42, 34], [100, 34], [100, 114], [42, 114]], '5', 0.9198901653289795)
([[174, 34], [234, 34], [234, 114], [174, 114]], '3', 0.5189616680145264)
([[704, 166], [762, 166], [762, 246], [704, 246]], '5', 0.8919380307197571)
([[44, 168], [104, 168], [104, 246], [44, 246]], '6', 0.8406975865364075)
([[568, 168], [630, 168], [630, 246], [568, 246]], '9', 0.7890614867210388)
([[445, 175], [499, 175], [499, 243], [445, 243]], '_', 0.8146840333938599)
([[176, 300], [234, 300], [234, 376], [176, 376]], '9', 0.8461765646934509)
([[968, 302], [1026, 302], [1026, 378], [968, 378]], '6', 0.9359095692634583)
([[44, 432], [102, 432], [102, 510], [44, 510]], '8', 0.9884797930717468)
([[1098, 432], [1156, 432], [1156, 510], [1098, 510]], '3', 0.5310271382331848)
([[572, 434], [630, 434], [630, 510], [572, 510]], '6', 0.9405879974365234)
([[46, 564], [108, 564], [108, 638], [46, 638]], '4', 0.6061235070228577)
([[702, 564], [762, 564], [762, 642], [702, 642]], '3', 0.617751955986023)
([[1100, 566], [1158, 566], [1158, 640], [1100, 640]], '_', 0.9189348220825195)
([[441, 569], [493, 569], [493, 637], [441, 637]], '8', 0.4214801788330078)
([[570, 694], [628, 694], [628, 772], [570, 772]], '2', 0.9453338384628296)
([[1098, 696], [1158, 696], [1158, 772], [1098, 772]], '6', 0.8925315737724304)
([[834, 826], [894, 826], [894, 906], [834, 906]], '2', 0.9729335308074951)
([[176, 830], [236, 830], [236, 906], [176, 906]], '6', 0.9366582036018372)
([[966, 830], [1024, 830], [1024, 904], [966, 904]], '8', 0.9889897704124451)
([[700, 956], [762, 956], [762, 1036], [700, 1036]], '9', 0.7338930368423462)
([[1098, 958], [1156, 958], [1156, 1036], [1098, 1036]], '5', 0.9352748394012451)
([[439, 961], [505, 961], [505, 1029], [439, 1029]], '4', 0.5053627490997314)
([[572, 962], [634, 962], [634, 1038], [572, 1038]], '_', 0.8581225872039795)
([[570, 1090], [630, 1090], [630, 1168], [570, 1168]], '8', 0.9891173839569092)
([[1096, 1090], [1154, 1090], [1154, 1166], [1096, 1166]], '9', 0.6340051293373108)
```

**Comment by rkcosmos** [comment]
try using allowlist = '0123456789'

**Comment by lagerfeuer** [comment]
@rkcosmos should have mentioned that I tried that, without success. Result is the same as above, minus the `_` false positives.

**Comment by rkcosmos** [comment]
one possible workaround is telling EasyOCR to use different model. For example, if you use 
`reader = easyocr.Reader(['ch_sim','en'])`, it's going to use simplified Chinese model. If `reader = easyocr.Reader(['ru','en'])`, it's Cyrillic model. All models support number 0123456789 and they are trained with different data/font. One model might be better than other. Just remember to use allowlist.

Note that EasyOCR is probably too general for your use case. For Sudoku, there might be better open source digit recognition model.

**Comment by lagerfeuer** [comment]
Tried both `ch_sim` and `ru`, neither worked. All of them seem to have a problem with the number 7.
Either that or it's the way the sevens appear in the Sudoku.

**Comment by poonyapat** [comment]
I tried reducing `text_threshold` to 0.5, using `allowlist` with 0-9, and blur with (3,3) kernel before OCR. Not sure why blurring help this issue but I tried and it worked.

**Comment by lagerfeuer** [comment]
@poonyapat good suggestion. using your settings, `7` is recognized, but still not everything. playing around with the parameters might lead me to a satisfying result.

**Comment by haiderasad** [comment]
> I tried reducing `text_threshold` to 0.5, using `allowlist` with 0-9, and blur with (3,3) kernel before OCR. Not sure why blurring help this issue but I tried and it worked.

how to set blur ? can you give example

**Comment by haiderasad** [comment]
> try using allowlist = '0123456789'

can you please tell if you found the solution to recognize separate digits? it only recognizes digits which are combined with letters
![image](https://user-images.githubusercontent.com/55244143/99962750-8d1f4f00-2db2-11eb-9650-c6fccadc24f8.png)

**Comment by nuiva** [comment]
I also encountered this issue and blurring helped. Here's a full example.

![test2.png](https://user-images.githubusercontent.com/34218315/120683387-3b185e00-c4a6-11eb-88b8-34d13eaaba9c.png)

```Python
import cv2          # opencv-python==4.5.2.52
import easyocr      # easyocr==1.3.2
img1 = cv2.imread("test2.png")
img2 = cv2.blur(img1, (3,3))
reader = easyocr.Reader(["en"])
results1 = reader.readtext(img1, allowlist="0123456789")
results2 = reader.readtext(img2, allowlist="0123456789")
print(results1) # []
print(results2) # [([[26, 0], [50, 0], [50, 30], [26, 30]], '7', 0.9999988079074598)]
```

**Comment by juanchosaravia** [comment]
I'm having a similar issue, here the image to recognize:
![image](https://user-images.githubusercontent.com/5606964/147856267-4578d103-2ca5-411e-be45-9498e0da43dd.png)

the result can't recognize there is a `7` there and it replaced 7 with a Z producing:
`YLJ-BZM-WTG`

**Comment by beuaaa** [comment]
I also encountered this issue and mag_ratio=2 worked.

`
results = reader.readtext(img, mag_ratio=2)
`

**Comment by FrLa2** [comment]
I'm not sure if my problem belongs here, but when I run readtext() nothing is found.

![_1_](https://github.com/JaidedAI/EasyOCR/assets/171917585/4723a7c2-9809-4516-b4fb-e8fb4b135bf5)


What do I have to do to get the 1 recognized?
Thank you very much!

**Comment by Ecationnet** [comment]
Resizing the image really helped me. I used cv2.resize() (it worked better than mag_ratio=2)

**Comment by ViniciusSerafim** [comment]
> I also encountered this issue and mag_ratio=2 worked.
> 
> `results = reader.readtext(img, mag_ratio=2)`

THANK YOU SO MUCH
