### ISSUE TITLE
Alpha-numeric detection 

### ISSUE THREAD

**Issue by sofiakhan** [JaidedAI/EasyOCR#256]
Hi,
Thanks for such an amazing OCR solution, 
I just had one query, as per my analysis it is not capable of handling alphanumeric words if they are longer than 4-5 chars. 

Is there anyway to do that?

**Comment by rkcosmos** [comment]
It's hard to build a model that covers all possible cases. I think you need to build custom dataset and retrain the model (we will support this feature in the future).
