### ISSUE TITLE
Unable to detect english(latin) letters on indian number plates.

### ISSUE THREAD

**Issue by developermastermind07** [JaidedAI/EasyOCR#259]
I want to use easyOCR for number detection of vehicle. But easyOCR was failing to detect. 
If possible can please guide me train the model using additional dataset?
Help will be appreciate.
![image1](https://user-images.githubusercontent.com/48270039/93045257-4dcad880-f674-11ea-9bf7-6bd6fbefe804.png)
EasyOCR output : 'KA03|1||9993'
Expected Output : 'KA03MN9993'

![image2](https://user-images.githubusercontent.com/48270039/93045325-7f43a400-f674-11ea-9a6f-980bb446a72c.png)
EasyOCR output : 'KA03|1$7979'
Expected o/p : KA03MS7979

![image3](https://user-images.githubusercontent.com/48270039/93045373-a39f8080-f674-11ea-996f-41304750c98d.png)
EasyOCR o/p : R 26B6
Expected O/p: HR 26 BG 0383

![image4](https://user-images.githubusercontent.com/48270039/93045444-d21d5b80-f674-11ea-8b5f-a7baa317b859.png)
EasyOCR o/p : B6?+ 3+5li0
Expected o/p : WB62 B 5170

**Comment by developermastermind07** [comment]
@EasyOCR team i have number plate dataset. Can you help me to add my dataset into EasyOCR model/
Thanks for your help

**Comment by muhk01** [comment]
> I want to use easyOCR for number detection of vehicle. But easyOCR was failing to detect.
> If possible can please guide me train the model using additional dataset?
> Help will be appreciate.
> ![image1](https://user-images.githubusercontent.com/48270039/93045257-4dcad880-f674-11ea-9bf7-6bd6fbefe804.png)
> EasyOCR output : 'KA03|1||9993'
> Expected Output : 'KA03MN9993'
> 
> ![image2](https://user-images.githubusercontent.com/48270039/93045325-7f43a400-f674-11ea-9a6f-980bb446a72c.png)
> EasyOCR output : 'KA03|1$7979'
> Expected o/p : KA03MS7979
> 
> ![image3](https://user-images.githubusercontent.com/48270039/93045373-a39f8080-f674-11ea-996f-41304750c98d.png)
> EasyOCR o/p : R 26B6
> Expected O/p: HR 26 BG 0383
> 
> ![image4](https://user-images.githubusercontent.com/48270039/93045444-d21d5b80-f674-11ea-8b5f-a7baa317b859.png)
> EasyOCR o/p : B6?+ 3+5li0
> Expected o/p : WB62 B 5170

to avoid uncessary character just add argument with allowlist, it will ignore character that may never exist in these plates, also you could adjust threshold and recognition width(per character/sentence)
reader.readtext(image_in, detail = 0, allowlist = '0123456789:-',width_ths = 1.5, text_threshold=0.8)

**Comment by developermastermind07** [comment]
> > I want to use easyOCR for number detection of vehicle. But easyOCR was failing to detect.
> > If possible can please guide me train the model using additional dataset?
> > Help will be appreciate.
> > ![image1](https://user-images.githubusercontent.com/48270039/93045257-4dcad880-f674-11ea-9bf7-6bd6fbefe804.png)
> > EasyOCR output : 'KA03|1||9993'
> > Expected Output : 'KA03MN9993'
> > ![image2](https://user-images.githubusercontent.com/48270039/93045325-7f43a400-f674-11ea-9a6f-980bb446a72c.png)
> > EasyOCR output : 'KA03|1$7979'
> > Expected o/p : KA03MS7979
> > ![image3](https://user-images.githubusercontent.com/48270039/93045373-a39f8080-f674-11ea-996f-41304750c98d.png)
> > EasyOCR o/p : R 26B6
> > Expected O/p: HR 26 BG 0383
> > ![image4](https://user-images.githubusercontent.com/48270039/93045444-d21d5b80-f674-11ea-8b5f-a7baa317b859.png)
> > EasyOCR o/p : B6?+ 3+5li0
> > Expected o/p : WB62 B 5170
> 
> to avoid uncessary character just add argument with allowlist, it will ignore character that may never exist in these plates, also you could adjust threshold and recognition width(per character/sentence)
> `reader.readtext(image_in, detail = 0, allowlist = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',width_ths = 1.5, text_threshold=0.8)`

**Comment by developermastermind07** [comment]
> > I want to use easyOCR for number detection of vehicle. But easyOCR was failing to detect.
> > If possible can please guide me train the model using additional dataset?
> > Help will be appreciate.
> > ![image1](https://user-images.githubusercontent.com/48270039/93045257-4dcad880-f674-11ea-9bf7-6bd6fbefe804.png)
> > EasyOCR output : 'KA03|1||9993'
> > Expected Output : 'KA03MN9993'
> > ![image2](https://user-images.githubusercontent.com/48270039/93045325-7f43a400-f674-11ea-9a6f-980bb446a72c.png)
> > EasyOCR output : 'KA03|1$7979'
> > Expected o/p : KA03MS7979
> > ![image3](https://user-images.githubusercontent.com/48270039/93045373-a39f8080-f674-11ea-996f-41304750c98d.png)
> > EasyOCR o/p : R 26B6
> > Expected O/p: HR 26 BG 0383
> > ![image4](https://user-images.githubusercontent.com/48270039/93045444-d21d5b80-f674-11ea-8b5f-a7baa317b859.png)
> > EasyOCR o/p : B6?+ 3+5li0
> > Expected o/p : WB62 B 5170
> 
> to avoid uncessary character just add argument with allowlist, it will ignore character that may never exist in these plates, also you could adjust threshold and recognition width(per character/sentence)
> `reader.readtext(image_in, detail = 0, allowlist = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ',width_ths = 1.5, text_threshold=0.8)`

I run with you recommendation. Performance is increased. 
Still for image no 2
EasyOCR o/p : KA0311S7979
Expected o/p : KA03MS7979

I think image3 is little bit tilted due to this EasyOCR is not able to detect characters. 
Now It giving o/p : ['R26B6', '0383']     
Expected o/p : HR26BG0383 
or Expected o/p HR26BG 0383
Not detecting H and not able to differentiate between G and 6

Image 1 giving correct results now.

Image 4 still not matching any character
EasyOCR o/p : IIB635160
Expected O/p : WB62 B 5170
Image4 can be ignored. This type of plate now not supported .

Help will appretiate. 
Can i add these images in training dataset and can i train latin dataset ?

**Comment by developermastermind07** [comment]
@muhk01  Can you please help me here ?

**Comment by muhk01** [comment]
> @muhk01 Can you please help me here ?
certain model has different accuracy for each font trained with, you could try to set different model like 'russian' model
`reader = easyocr.Reader(['ru']`
see does it has different performance in output.

**Comment by developermastermind07** [comment]
Thank you @muhk01  for your help .
Still OCR facing problem to detect M,H,N,Q

**Comment by muhk01** [comment]
> Thank you @muhk01 for your help .
> Still OCR facing problem to detect M,H,N,Q

i do not know, but in my opinion you just can not expect a perfect result of recognition from someone trained model, because from the dataset itself, i mean from font database itself it probably total different with a font you want to recognize with, you may contact this repository owner and ask how to do retrain with your own dataset.

**Comment by developermastermind07** [comment]
@rkcosmos Can you please guide me ?
How to train custom dataset using easyocr ?
Help will be appreciated..

**Comment by rkcosmos** [comment]
Our training pipeline is not open sourced yet. Please look into repos in reference section.
