### ISSUE TITLE
EasyOCR tutorials

### ISSUE THREAD

**Issue by jrosebr1** [JaidedAI/EasyOCR#260]
Hi EasyOCR team -- I just wanted to take a second and let you know how much I appreciate all the hard work put into this library. It's _easily_ the most intuitive OCR API I have used (and quite frankly, makes it hard to go back to Tesseract 😉 )

My name is Adrian, I run the popular computer vision, deep learning, and OpenCV blog, [PyImageSearch.com](https://www.pyimagesearch.com/). My apologies if this is not the correct place to post this, but I wanted to let you know that I just published a tutorial on "Getting started with EasyOCR for Optical Character Recognition":

https://www.pyimagesearch.com/2020/09/14/getting-started-with-easyocr-for-optical-character-recognition/

I would love to write more tutorials on EasyOCR in the future, so if there is a common question/use case/application that you see asked here on GitHub but you can't/don't want to include it as an example in the docs, please let me know, and I'll certainly see if I can write a tutorial on it to help the community.

Have a wonderful day and thank you again for all the incredible hard work that has gone into EasyOCR 😄

**Comment by rkcosmos** [comment]
Wow, thanks for the wonderful tutorial. It means a lot to us to know people are enjoying our work. I see common interests on license plate recognition. To do that efficiently, people need to use optional arguments like 'allowlist' or 'blocklist' (see full documentation [here](https://www.jaided.ai/easyocr/documentation) and most probably some post-processing. I currently don't have time to do the writing. (plus you are way better writer than me)

**Comment by ghandic** [comment]
@jrosebr1 you can actually combine Tesseract and CRAFT if you still want to dabble - this is the best way I've found to run on CPU - also worth pointing out tesseocr as it's much faster than pytesseract as you can front load the Tesseract models and just set the image and get the text.

**Comment by jrosebr1** [comment]
> I see common interests on license plate recognition. To do that efficiently, people need to use optional arguments like 'allowlist' or 'blocklist'

Thanks @rkcosmos. I actually have a tutorial publishing this coming Monday on ANPR. It uses Tesseract under the hood but I'll certainly look into creating an EasyOCR variant of it 😄 

> you can actually combine Tesseract and CRAFT if you still want to dabble

Thanks @ghandic, I'll look into that!

**Comment by SungmanHong** [comment]
Great, and I want to ask some questions

1) Tutorials for porting on iOS, Android(Converting for TFlite?)

2) python Live OCR using cam in laptop using pyQT or kivy UI? and change some network to simple network like efficiency net for live OCR

Thanks

**Comment by CrisMejiaRomo** [comment]
@jrosebr1 can you explain more the "prob"ability part in the tutorial?
How does it works?

**Comment by yusufsonmez** [comment]
Hello. I want to use blocklist in easyocr but when i want to block some symbols like -, easyocr print another symbol instead of - symbol.I don't want see any symbol instead of symbol that i blocked, i just want to delete this symbol. How can i do this?
