### ISSUE TITLE
Using result for auto translation

### ISSUE THREAD

**Issue by back2zion** [JaidedAI/EasyOCR#262]
Hello.
Thank you for making this great tool.
As a novice(only a month to code), for making webtoon auto translation system, I started to code using easyOCR. 
But I got stuck after watching the great result. 
My question is, how to use the result after OCR recognition. I want to use the text after being recognized. But I have no idea. 

my intention is 
1) recognize Korean text using easyOCR
2) translate Korean into English using Google Translator or Naver Papago API.
3) Let the translated results to be located on the speech bubble.

**Comment by rkcosmos** [comment]
I can only answer for EasyOCR part. Do you already get korean text?

**Comment by back2zion** [comment]
Ah. Yes. With EasyOCR, I could get Korean text. Thank you.
