### ISSUE TITLE
Recognize characters 

### ISSUE THREAD

**Issue by daniiki** [JaidedAI/EasyOCR#265]
Hi, can EasyOCR also recognize character sequences that arent words, i.e 'THMPGH'?
I want to train a model which recognizes dotted character sequences, but I dont know if EasyOCR is the right starting point for this problem. What do you recommend?

**Comment by amitbcp** [comment]
You might need to train your custom recognition model with similar type of fonts(dotted). I don't think the current default model was trained on such a font
