### ISSUE TITLE
Language Model for WordBeamSearch

### ISSUE THREAD

**Issue by amitbcp** [JaidedAI/EasyOCR#266]
In the wordbeamsearch decoding mode, the LM part is commented out.
Can you please point me to the sample LM that will work this ? In my custom implementation, I would want to include the LM. Currently I am have KenLM character models but I can make cone suited for EasyOCR.

Thanks in advance.

**Comment by amitbcp** [comment]
Used KenLM integration for bi-gram. closing the issue

**Comment by christegho** [comment]
Did you change the function [applyLM](https://github.com/JaidedAI/EasyOCR/blob/ea2db54101f83bc96637382228611120654f1dbd/easyocr/utils.py#L110) to make it work with KenLM?

**Comment by amitbcp** [comment]
I added a different function to integrate KenLM. though I hdpnt have the code handy as it was done as a part of by previous job. Though it was like training you own character model with it and using it for the beam options
