### ISSUE TITLE
10x speed improvement in WordBeamSearch Decoding

### ISSUE THREAD

**Issue by amitbcp** [JaidedAI/EasyOCR#267]
Hi EasyOCR team !

Thanks for open-sourcing the OCR tool. I have been working and customizing it for my use case for sometime now.
Recently while doing latency testing, I found that the ```wordbeamsearch``` decoding method takes a lot of time(infact more than the forward pass on cpu)

On digging deep the issue I found was with the use of ```simplify_label`` function 
here : https://github.com/JaidedAI/EasyOCR/blob/8af936ba1b2f3c230968dc1022d0cd3e9ca1efbb/easyocr/utils.py#L118

If you check line L169 & L189 , in utils.py, the function simplify_label is called ~ (168+5) times at every time-step.
I have done some modifications and wrote a competitive version for simplify label which is giving me 10x better performance on the decoding.

Can you please let me know, is there any particular for format in which I can give a PR for this ?

**Comment by rkcosmos** [comment]
No particular format. I still have to check it before accept PR though.

**Comment by rohitnairtech** [comment]
Is this addition taken?
