### ISSUE TITLE
Using newer models from @clovaai

### ISSUE THREAD

**Issue by rajat-008** [JaidedAI/EasyOCR#270]
I worked with the default models you've provided(for English) and wasn't able to achieve the desired accuracy. Is it currently possible to use newer models from @clovaai(https://drive.google.com/drive/folders/15WPsuPJDCzhp2SvYZLRj8mAlT3zmoAMW) without much refactoring?
Thanks.

**Comment by rkcosmos** [comment]
no, a lot of refactor is needed.

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).

**Comment by rajat-008** [comment]
Thank you @rkcosmos ! Will check it out.
