### ISSUE TITLE
install easyocr on jetson nano

### ISSUE THREAD

**Issue by nampqaime** [JaidedAI/EasyOCR#282]
Hi,

I'm trying to install package on jetson nano.
I had already installed opencv-python

![Screenshot from 2020-10-15 09-12-38](https://user-images.githubusercontent.com/72903355/96075583-8ceb8400-0ed5-11eb-98ad-f368722ed288.png)

But I get error like below image:

![Screenshot from 2020-10-15 09-12-17](https://user-images.githubusercontent.com/72903355/96075604-9b39a000-0ed5-11eb-9aed-545df4257409.png)

How to skip opencv-python when install processing

Thanks!

**Comment by Stevew7777** [comment]
I have same problem

Maybe solution here -  normally pytorch not ARM architecture compatible

https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-6-0-now-available/72048

**Comment by nampqaime** [comment]
Hi @Stevew7777 

I had already installed newest version pytorch but it's not work.

Have you fix this error?

**Comment by ManuelBu96** [comment]
Hi,
is this Problem fixed? I have try to install the Software since 4 hours and it will not work.

**Comment by Sanket-15** [comment]
I'm facing the same issue. Did anyone find a solution?

**Comment by fiosaint** [comment]
any idea how to solve this issue ?
