### ISSUE TITLE
Any tutorial to train / fine-tune the model for more fonts (new dataset)?

### ISSUE THREAD

**Issue by hahmad2008** [JaidedAI/EasyOCR#286]
Thanks for publishing this great EASYOCR model! 
I am wondering if I can find a tutorial to train EASYOCR or finetune it on a custom dataset ( where I need to add a complex background for texts and support new fonts).

What do you think? is there any link for that?

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
