### ISSUE TITLE
Numer recognition

### ISSUE THREAD

**Issue by hanifidemirel** [JaidedAI/EasyOCR#287]
Hi
![box](https://user-images.githubusercontent.com/7906786/96336178-6f115100-1086-11eb-878d-e1b98e22a916.jpg)

I have this kind of files which I grap from screen and here is my code:
`
    import easyocr
import time
import screenshot
import pyscreenshot as ImageGrab

def take_ss_cur_num():
    im = ImageGrab.grab(bbox=(1380, 122, 1438, 169))  # X1,Y1,X2,Y2

    # save image file
    im.save('box.jpg')

print(time.ctime(time.time()))
reader = easyocr.Reader(['en'])  # need to run only once to load model into memory

while 1:
    take_ss_cur_num()
    result = reader.readtext('box.jpg', detail=0, allowlist='0123456789')
    print(result)
    print(time.ctime(time.time()))`

Unfortunately EasyOCR cannot detect it %100. It fails espacially with digits. Is there anything I could do to improve its accuracy?
Thanks

**Comment by ghandic** [comment]
If you're just doing single digit recognition EasyOCR may not be the best solution to be using - since this is a screen grab you could just go for template matching as it's a much more controlled environment

**Comment by hanifidemirel** [comment]
> If you're just doing single digit recognition EasyOCR may not be the best solution to be using - since this is a screen grab you could just go for template matching as it's a much more controlled environment

Thanks. I did it as you said and results are better.

**Comment by ghandic** [comment]
No worries, could you close the issue? 😁

**Comment by miclejackson12** [comment]
Which template matching library are you using. I am not able to find any good scale independent template matching library in python.
