### ISSUE TITLE
Use without language

### ISSUE THREAD

**Issue by blaaaaaaa** [JaidedAI/EasyOCR#29]
Can it be used just to detect characters on screen without language context. Like usernames, random (latin) characters?
Would it also be possible to whitelist characters?

**Comment by rkcosmos** [comment]
Yes, default decoder is 'Greedy' which does not take any language context into account.

Whitelist or Blacklist specific characters is not on the API yet but I plan to implement it very soon. As of now, when you choose any languages, it whitelists all characters in the chosen languages.
