### ISSUE TITLE
'charmap' codec can't encode character '\u2588' in position 12: character maps to <undefined>

### ISSUE THREAD

**Issue by usmanfarooq619** [JaidedAI/EasyOCR#298]
While installing 
reader = easyocr.Reader(['en'])

gets an error

Progress: |--------------------------------------------------| 2.0% Complete

Traceback (most recent call last):
  File "f:\vscode_work\cnic_ocr\test.py", line 2, in <module>
    reader = easyocr.Reader(['ch_sim','en']) # need to run only once to load model into memory
  File "F:\anaconda3\lib\site-packages\easyocr\easyocr.py", line 244, in __init__
    download_and_unzip(model_url[model_file][0], model_file, self.model_storage_directory)
  File "F:\anaconda3\lib\site-packages\easyocr\utils.py", line 540, in download_and_unzip
    urlretrieve(url, zip_path,reporthook=printProgressBar(prefix = 'Progress:', suffix = 'Complete', length = 50))
  File "F:\anaconda3\lib\urllib\request.py", line 283, in urlretrieve
    reporthook(blocknum, bs, size)
  File "F:\anaconda3\lib\site-packages\easyocr\utils.py", line 640, in progress_hook
    print(f'\r{prefix} |{bar}| {percent}% {suffix}', end = printEnd)
  File "F:\anaconda3\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2588' in position 12: character maps to <undefined>

**Comment by CemraJC** [comment]
I had this issue. Make sure you set python's default encoding right:
`export PYTHONIOENCODING=utf-8`

**Comment by Bobb6000** [comment]
if that didn't work maybe do this
set PYTHONIOENCODING=utf-8

**Comment by Bobb6000** [comment]
[hello]

**Comment by Bobb6000** [comment]
["helo"]

**Comment by MihirD002** [comment]
> I had this issue. Make sure you set python's default encoding right: `export PYTHONIOENCODING=utf-8`

Where should I do that?
Can you please help? I'm stuck over there.

**Comment by CemraJC** [comment]
> > I had this issue. Make sure you set python's default encoding right: `export PYTHONIOENCODING=utf-8`
> 
> Where should I do that? Can you please help? I'm stuck over there.

Making the assumption that you're using bash, I would put it in your `.bashrc` or `.bash_profile` depending on your setup. If you're on Windows, I'm guessing you need to set an environment variable with this thing:
![image](https://github.com/JaidedAI/EasyOCR/assets/9857188/c1f3ed67-8718-477e-8c27-c149d7386835)

**Comment by MihirD002** [comment]
Okay, got it now. Thanks a lot!!

**Comment by MihirD002** [comment]
> > > I had this issue. Make sure you set python's default encoding right: `export PYTHONIOENCODING=utf-8`
> > 
> > 
> > Where should I do that? Can you please help? I'm stuck over there.
> 
> Making the assumption that you're using bash, I would put it in your `.bashrc` or `.bash_profile` depending on your setup.
> 
> If you're on Windows, I'm guessing you need to set an environment variable with this thing: ![image](https://user-images.githubusercontent.com/9857188/280555591-c1f3ed67-8718-477e-8c27-c149d7386835.png)

Okay, got it now. Thanks a lot!
