### ISSUE TITLE
Update list of words in Occitan

### ISSUE THREAD

**Issue by Mejans** [JaidedAI/EasyOCR#302]
Hello,

I put a 7zip archive here: https://github.com/Mejans/data-occitan
because it was too large to be sent with a PR.
Best regards

**Comment by supermamie** [comment]
It can totally be done via a PR.
I wanted to do it for you, but as it seems that occitan is not (yet) in the supported languages, there are more things to do than just update a file (at least add also a character list).
As you managed to upload your 7z file to git, you'll manage to upload those 2 files too.
The « right » way to do this (I think) is to create a fork of this project (that will be under your account), then upload the 2 files, and then create a pull request.

If you can not do it, I'll do it for you.
(But I'll need a list of characters)

**Comment by supermamie** [comment]
I did not think that my commit on my fork would appear here :grin: 
So now that this is displayed, just give me the list of characters and I'll make the pull request.

Side note : Is there a specific license with your list of words ?

**Comment by supermamie** [comment]
Here is the pull request : #321
