### ISSUE TITLE
How to get the coordinates of each word?

### ISSUE THREAD

**Issue by ybdesire** [JaidedAI/EasyOCR#303]
I want to get the coordinates of each character. Is it possible to locate each Chinese character?

**Comment by rkcosmos** [comment]
We don't have exact location of each characters. This [estimation](https://github.com/JaidedAI/EasyOCR/issues/311) may be useful for you.

**Comment by ybdesire** [comment]
Thansk @rkcosmos  for the update.

**Comment by victor-ab** [comment]
@rkcosmos I understand you don't have the exact location of each character. But is there a way to get the exact word location? Which argument can I change to separate all lines by spaces?
