### ISSUE TITLE
About CUDA out of memory issue

### ISSUE THREAD

**Issue by mijoo308** [JaidedAI/EasyOCR#306]
Hi.
First of all, thank you for your work on OCR.

I saw some issues about 'CUDA out of memory'  ( ex)  #82 )
I think it's because the size of image is big, is that right?
I have some idea to solve this problem with some preprocessing on image and postprocessing on  results.
And I think everyone will be able to use easyOCR without 'out of memory' problem.

Can I work on this issue?

Thank you :)

**Comment by rkcosmos** [comment]
How big is your GPU memory? It's more about the size of deep learning model than the size of your images.

**Comment by scizors** [comment]
for me also same
