### ISSUE TITLE
use with c#

### ISSUE THREAD

**Issue by masgh021** [JaidedAI/EasyOCR#308]
is it possible , use easy ocr with c# ???

**Comment by snowuyl** [comment]
Open eVsion provides C# library. 
https://www.euresys.com/en/Products/Machine-Vision-Software/Open-eVision-Libraries/EasyOCR

**Comment by masgh021** [comment]
Hello
i am interested to this position

**Comment by KhanRashidov** [comment]
> Open eVsion provides C# library. https://www.euresys.com/en/Products/Machine-Vision-Software/Open-eVision-Libraries/EasyOCR

Thanks

**Comment by blackholeearth** [comment]
Call python from c# ; 

https://github.com/pythonnet/pythonnet/
