### ISSUE TITLE
Estimate number of characters in textbox

### ISSUE THREAD

**Issue by adamfrees** [JaidedAI/EasyOCR#311]
Hello, thanks so much for all the work done on this repo!

I have an application where I am trying to extract a small amount of text from an image that has a lot of text on it - for instance, a date (MM/DD/YYYY) located on a large form.

I've found that this sort of problem really benefits from estimating the number of characters in each text box during the detection phase. That way, the recognition can prioritize text boxes that "look close" to the desired number of characters, rather than extracting all of the text and then finding the date after the fact.

The way that I've estimated the number of characters is to run `scipy.ndimage`'s `label` function on
`
cv2.threshold((textmap - linkmap) * segmap / 255.0, text_threshold, 1, 0)
`
for each textbox in `getDetBoxes_core` in `craft_utils.py`. At least in my use-case, this gives a pretty decent estimate.

Is this something that would be worth making a pull request for? I've found it useful, and it seems general enough that others might benefit from it as well.

**Comment by rkcosmos** [comment]
Sounds nice, I think other people can benefit from this addition. Can you make a PR that enable users to have this estimation via optional argument `estimate_char_no` in `detect` function (`easyocr.py`)? Something like 
```
detect( ..., estimate_char_no = True)
```
and modify the output of `detect` function to include your calculation. The default value of `estimate_char_no` has to be `False`  to maintain standard output format.
