### ISSUE TITLE
manually downloaded models and run the program question

### ISSUE THREAD

**Issue by 199907** [JaidedAI/EasyOCR#313]
![1](https://user-images.githubusercontent.com/50698345/99899593-8545a900-2ce5-11eb-890f-9f07a3b85264.png)
![2](https://user-images.githubusercontent.com/50698345/99899599-88d93000-2ce5-11eb-8b20-3dec70b9a82c.png)
I manually downloaded all the models, and the first time I ran the program, it still showed that I needed to download it.

**Comment by rkcosmos** [comment]
You put them in wrong directory. It should be  'your home directory/.EasyOCR/model'.

**Comment by 199907** [comment]
OK, thank you! I can run the program.

**Comment by iweixubin** [comment]
I'm in China, the network is very slow

Where can I download to the model？？
and Which directory to put in？？

when i pip install easyocr
D:\Tools\anaconda3\envs\pytorch\Lib\site-packages\easyocr
put the model in
D:\Tools\anaconda3\envs\pytorch\Lib\site-packages\easyocr\model ???

**Comment by 199907** [comment]
&nbsp; &nbsp; &nbsp; &nbsp; 你是本科生刚接触吗？可以通过访问github镜像网站的方式手动下载需要的model，解压后放到.../.EasyOCR/model&nbsp; 文件夹下，注意是EasyOCR前面有点。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "JaidedAI/EasyOCR"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月23日(星期一) 晚上11:03
收件人:&nbsp;"JaidedAI/EasyOCR"<EasyOCR@noreply.github.com&gt;;
抄送:&nbsp;"东北大学赵艳涛"<www.1935569858@foxmail.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [JaidedAI/EasyOCR] manually downloaded models and run the program question (#313)





 
I'm in China, the network is very slow
 
Where can I download to the model？？
 and Which directory to put in？？
 
when i pip install easyocr
 D:\Tools\anaconda3\envs\pytorch\Lib\site-packages\easyocr
 put the model in
 D:\Tools\anaconda3\envs\pytorch\Lib\site-packages\easyocr\model ???
