### ISSUE TITLE
read Japanese comic

### ISSUE THREAD

**Issue by iweixubin** [JaidedAI/EasyOCR#315]
![Japanese comic](https://64.media.tumblr.com/204a620faad53bfee6f6462447a9f857/tumblr_inline_nryfmlsdaN1rwuyyv_640.jpg)

``` py
import easyocr
reader = easyocr.Reader(['ja'])
result = reader.readtext('E:/ss.jpg', detail = 0)
print(result)
['襲', '|黙', 'ァた', '<', '舘', '義', '鰻', 'ぅ', '態', '鶏', '小加か', '怒:らな']
```

Japanese is vertical, right to left

How do I set parameters?

**Comment by moopene36607** [comment]
https://www.jaided.ai/easyocr/documentation
I think you could try to use 'detection' method and do some preprocessing according to the position of the character.
Then apply 'recognize' method.
