### ISSUE TITLE
Conda-forge recipe

### ISSUE THREAD

**Issue by owenlamont** [JaidedAI/EasyOCR#32]
This is an enhancement request - I was wondering if anyone had started on a conda-forge recipe or a conda recipe for any other channel? I'm happy to try and contribute that if not.

**Comment by rkcosmos** [comment]
I have not started it yet. I'm glad you can contribute this. Please update us in this issue if there is any progress.

**Comment by owenlamont** [comment]
No problem, I'll try to find some time to make and test a conda recipe this or next week. If there's any other conda fans that want to pick this up first feel free, I'll comment this once I start if not.
