### ISSUE TITLE
Dictionary output

### ISSUE THREAD

**Issue by A2va** [JaidedAI/EasyOCR#326]
I think it would be easier to understand if the output was in dictionary form.

**Comment by rkcosmos** [comment]
I don't quite understand. What do you mean by dictionary form?

**Comment by A2va** [comment]
If I take the output like this:
```python
[([[189, 75], [469, 75], [469, 165], [189, 165]], '愚园路', 0.3754989504814148)]
```
I think it's more simple to understand if its like this:
```python
{
'boxes':[[189, 75], [469, 75], [469, 165], [189, 165]]
'text:':愚园路
'confident':0.3754989504814148
}
```

**Comment by rkcosmos** [comment]
I see, that certainly looks better. Unfortunately, changing output format will affect too many people at this point. We might add an option for output format and set default to old list format... something like `read.readtext(filepath, output_format = 'dict')`.

**Comment by A2va** [comment]
Ok that looks good to me
