### ISSUE TITLE
The performance of the custom model is too bad.

### ISSUE THREAD

**Issue by xiayongk** [JaidedAI/EasyOCR#336]
Hello. I have a few questions.

I wanted to train the Korean model.
So, referring to https://github.com/Belval/TextRecognitionDataGenerator, I generated training data composed of words and sentences.
And I trained the Korean model by referring to https://github.com/clovaai/deep-text-recognition-benchmark.
The structure of the model is as follows. 
- **None - ResNet - BiLSTM - CTC** 
- input_channel = 1, output_channel = 512, hidden_size = 512, etc.
- model size also same!

After training, the validation and test results were over 94%.
However, the result of changing from EasyOCR to my model instead of korean.pth(downloaded model) was terrible.
I think the model structure is the same.
So I'm not sure what is the problem. :(

I would like to get some advice on what's mentioned above.

**Comment by shgidi** [comment]
Hi, I'm trying to do a similar process with hebrew. It's somehow tricky since there are many moving parts, but I think there are 2 items susceptible to mistake:
1. ordering of tokens should be the same in easy OCR definitions and in your training setting
2. Did you train on one word or more?

**Comment by kimlia545** [comment]
@shgidi @xiayongk 
Is the problem solved?
I had the same problem. 
what do you mean "ordering of tokens"?
Do I have to train at least 2 words?

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).

**Comment by masoudMZB** [comment]
Facing the same problem in Persian. I try to fix and report here
[rkcosmos](https://github.com/rkcosmos) I repeated finetuning same the note you prepared for the training recognition model [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md)  but still facing this problem. any suggestions? this problem is reporting many times.
