### ISSUE TITLE
Could we create models for reading special diagrams like network diagrams?

### ISSUE THREAD

**Issue by pranavlal** [JaidedAI/EasyOCR#339]
Hi,
Is it possible to add icons to an existing model or to perhaps train a new with network architecture diagram icons like the ones found at
https://aws.amazon.com/architecture/icons/

I am building a solution to read flowcharts and architecture diagrams. 

I suspect the right solution is to use object detectors but I am wondering if OCR can help here.

Pranav

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
