### ISSUE TITLE
Passing cv.imread object instead of file or filename to readtext

### ISSUE THREAD

**Issue by Johndirr** [JaidedAI/EasyOCR#34]
It would be nice to call readtext on an opencv img object instead on a file or filename.

**Comment by rkcosmos** [comment]
Looks doable to me. I'll add this feature later.

**Comment by MAAICV** [comment]
same wish here

**Comment by rayjan0114** [comment]
same wish here

**Comment by rkcosmos** [comment]
Done, it's now possible to do something like

```
img_cv = cv2.imread(file_name, cv2.IMREAD_COLOR)
result = reader.readtext(img_cv)
```
