### ISSUE TITLE
Terrible performance when trying to read single digit numbers. Performance improves significantly on using binary inverse thresholding, but not completely.

### ISSUE THREAD

**Issue by Arpanio** [JaidedAI/EasyOCR#341]
EasyOCR doesn't perform well when trying to read a page of purely single digit numbers. Replacing single digit numbers with at least 2 digits reverses this, with the reader recognizing almost all numbers correctly. I am using the allowlist string = '0123456789' to signal to the module that there are only digits present.

The poor performance improves significantly if the image is preprocessed using binary inverse thresholding. The improvement isn't perfect however, and some numbers are still not captured.

Test based on this image file: 
<img width="321" alt="test_numbers_singles" src="https://user-images.githubusercontent.com/7851954/103452682-dd4ed280-4cc9-11eb-8079-ee2ad036201f.PNG">

## Performance with no pre-processing:
```
import easyocr
import cv2 as cv

# English
reader = easyocr.Reader(['en'])

# Without pre-processing
filename = 'test_numbers_singles.PNG'
img = cv.imread(filename)
ocr = reader.readtext(img, allowlist='0123456789')
img_annotated = img.copy()
for elem in ocr:
    img_annotated = cv.line(img_annotated, tuple(elem[0][0]), tuple(elem[0][1]),
                            (0, 255, 0), 2)
    img_annotated = cv.line(img_annotated, tuple(elem[0][1]), tuple(elem[0][2]),
                            (0, 255, 0), 2)
    img_annotated = cv.line(img_annotated, tuple(elem[0][2]), tuple(elem[0][3]),
                            (0, 255, 0), 2)
    img_annotated = cv.line(img_annotated, tuple(elem[0][3]), tuple(elem[0][0]),
                            (0, 255, 0), 2)

cv.imshow(filename, img_annotated); cv.waitKey(0); cv.destroyAllWindows()
```

Result:
![out-of-box-ocr](https://user-images.githubusercontent.com/7851954/103453344-eee7a880-4cd0-11eb-8409-0a55964bd383.png)

## With pre-processing
```
# With inverse binary thresholding
ret, thresh = cv.threshold(img, 127, 255, cv.THRESH_BINARY_INV)
ocr = reader.readtext(thresh, allowlist='0123456789')
img_annotated = img.copy()
for elem in ocr:
    img_annotated = cv.line(img_annotated, tuple(elem[0][0]), tuple(elem[0][1]),
                            (0, 255, 0), 2)
    img_annotated = cv.line(img_annotated, tuple(elem[0][1]), tuple(elem[0][2]),
                            (0, 255, 0), 2)
    img_annotated = cv.line(img_annotated, tuple(elem[0][2]), tuple(elem[0][3]),
                            (0, 255, 0), 2)
    img_annotated = cv.line(img_annotated, tuple(elem[0][3]), tuple(elem[0][0]),
                            (0, 255, 0), 2)

cv.imshow(filename, img_annotated); cv.waitKey(0); cv.destroyAllWindows()
```

Result:
![inv-bin-thresholding-ocr](https://user-images.githubusercontent.com/7851954/103453371-3f5f0600-4cd1-11eb-99e8-c1587d2777b2.png)

Performance improves, but there are still omissions as well as false detection/recognition.

Repeating the above test with double digit numbers gives good performance out-of-box and almost perfect performance with the thresholding approach.

Is there a workaround for my use case?

**Comment by Arpanio** [comment]
Just discovered that using larger font-sizes improves performance significantly. Larger == font size 16.

**Comment by samayala22** [comment]
@Arpanio I had the same issue. Fixed it by blurring the image (used `blur = cv2.blur(img,(5,5))` with OpenCV) before running the OCR.

**Comment by Arpanio** [comment]
@samayala22 Thank you. I had experimented with different blurs/thresholding and found that in my case, binary inverse threshold worked best. The best performance still left out a lot of the numbers though.

I think it's an overfitting issue with Craft. I tried using a [packaged craft text detector](https://github.com/fcakyon/craft-text-detector) and had similar problems.

For my use case, I am expecting single numbers 90%+ of the time. I think a general solution would involve custom training on single numbers.

**Comment by crocagiles** [comment]
I had a massive performance increase by blurring, as some folks here mentioned, but also by adding a simple upscale:
```
scale_factor = 2
upscaled = cv2.resize(img_cropped, None, fx=scale_factor, fy=scale_factor, interpolation=cv2.INTER_LINEAR)
blur = cv2.blur(upscaled, (5, 5))
results = reader.readtext(blur , text_threshold=0.3)
```

**Comment by MicDZ** [comment]
I had a performance increase by making border.
```
extend_pixel = 50
extend_pic = cv2.copyMakeBorder(extend_pic, extend_pixel, extend_pixel, extend_pixel, extend_pixel, cv2.BORDER_CONSTANT, value=[0, 0, 0])
```

**Comment by IldarAltynbaev** [comment]
> I had a massive performance increase by blurring, as some folks here mentioned, but also by adding a simple upscale:
> 
> ```
> scale_factor = 2
> upscaled = cv2.resize(img_cropped, None, fx=scale_factor, fy=scale_factor, interpolation=cv2.INTER_LINEAR)
> blur = cv2.blur(upscaled, (5, 5))
> results = reader.readtext(blur , text_threshold=0.3)
> ```

Thank you a lot, mate!
Your idea solved the same problem I had
