### ISSUE TITLE
Digit Recognition

### ISSUE THREAD

**Issue by swork1** [JaidedAI/EasyOCR#343]
I am working on a project that only deals with digits (0-9). Currently, I am using ['te', 'en'] for the most consistent reading but I am still getting inaccurate readings. Is there any language that is trained better in recognizing digits?

Thanks!

**Comment by NataliaAssange** [comment]
> I am working on a project that only deals with digits (0-9). Currently, I am using ['te', 'en'] for the most consistent reading but I am still getting inaccurate readings. Is there any language that is trained better in recognizing digits?
> 
> Thanks!

Hi 
I have similar problems and I saw you closed it. How did you solve that?
Thank you!
