### ISSUE TITLE
Stuck at Downloading Recognition Model

### ISSUE THREAD

**Issue by takeruadelbert** [JaidedAI/EasyOCR#344]
Hi, thanks for your hardwork.
I would like to ask a solution about my problem.
I stuck at '**100.0% Complete Downloading recognition model ...**' which is inside **_docker_**.
I have been waiting for hours and it's still persist.
Could you please help me why about this problem?

_P.S. I am using Ubuntu 20.04 and Python 3.8_

![image](https://user-images.githubusercontent.com/17585173/103722404-76e7ee00-5002-11eb-9892-f8deeb208ce7.png)

**Comment by rkcosmos** [comment]
you can try download models manually. Download links and instruction are on readme file.

**Comment by takeruadelbert** [comment]
thank you for the solution! cheers

**Comment by animeesh** [comment]
Hi, thanks for the support could you help me out with which section of the readme consists of the information?
