### ISSUE TITLE
Exception has occurred: RuntimeError

### ISSUE THREAD

**Issue by JohnnyZhang0628** [JaidedAI/EasyOCR#35]
OS:win 10
python:3.8
torch:1.5.1
I am very happy that the author has open sourced this project.I try to debug it,but i got an exception .
my code
```
import easyocr
reader = easyocr.Reader(['ch_sim','en'],gpu=False)
reader.readtext('1.jpg')
print(reader)
```
my exception 
```
Exception has occurred: RuntimeError

        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
  File "D:\WorkSpace\Python\easy_orc_test\test.py", line 3, in <module>
    reader.readtext('1.jpg')
  File "<string>", line 1, in <module>
```

**Comment by JohnnyZhang0628** [comment]
I found another question . this project  almost used 8G RAM？
![捕1获](https://user-images.githubusercontent.com/28375774/86530131-c67d1e00-bee8-11ea-8ae2-f8276039e408.PNG)
![捕获](https://user-images.githubusercontent.com/28375774/86530135-cb41d200-bee8-11ea-8fc6-d5ed03c5e058.PNG)

**Comment by rkcosmos** [comment]
For the first problem, please see #33. About RAM, I am not sure about CPU version, but it needs around 2GB for GPU. Can you try fix the first problem and see how much RAM does it really need?

**Comment by JohnnyZhang0628** [comment]
@rkcosmos thanks your reply.For the first problem,i have solved.But i not understand why should do it?
if code must define a function,i suggest you modify your "readme.md"  file.
```
import easyocr
def main():
    read=easyocr.Reader(['ch_sim','en'],gpu=False)
    text =read.readtext('images/id_card.jpg')
    print(text)
    
if __name__ == '__main__':
    main()
```
For the second problem,it amolst used 5G RAM.I can accept it.
![微信图片_20200705202901](https://user-images.githubusercontent.com/28375774/86532750-d69ff800-befe-11ea-8dcd-04d84c251b5d.png)

**Comment by rkcosmos** [comment]
It's an issue with multiprocessing in Windows. I just update my code so default setting will not cause this error anymore.
