### ISSUE TITLE
Optimize for number plate recognition

### ISSUE THREAD

**Issue by Stevew7777** [JaidedAI/EasyOCR#351]
How would I optimize  easyocr to operate in just one language ( e.g. english ) to do number plate recognition/ANPR?

Can we make the OCR capability faster by stripping out other languages  or is this controlled  by passing it the language as a parameter?   I think this has great potential for number plate recognition, but it needs to be faster.

Thank you for your help.

**Comment by lerndeep** [comment]
@Stevew7777 for license plate detection and recognition I found one resource you can use https://github.com/bharatsubedi/ALPR-Yolov5

**Comment by Stevew7777** [comment]
Thank you, I will check it out.

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
