### ISSUE TITLE
latin.pth recognition model for azerbaijani does not detect characters other than english and german umlauts

### ISSUE THREAD

**Issue by kalai2033** [JaidedAI/EasyOCR#357]
Hi,
   Thanks for the great repo. I have a need to OCR different languages such as 

az - Azerbaijani 
cs - Czech 
da - Danish
de - Deutsch
en - English
es - Spanish, Castilian
et - Estonian
fi - Finnish
fr - French
hr - Croatian

All these languages use ''latin.pth'' model for recognition. I have 2 questions:

1)  It does not recognize characters other than English and german when I used the Azerbaijani recognition model. But, I could not read any special characters like 

For example, if I read an image  with the following Azerbaijani text after loading the model for Azerbaijan language ('az'):

**Ş** i r k **ə** t  n ü m a y **ə** n d **ə** s i 

it gives the output as

Siket nümayandesi

It misreads the characters highlighted in bold.

2) I have a use case  where I need to use both Cyrillic and Latin model together cause I don't know which language type of images I need to process for OCR. When i tried mixing Cyrillic and Latin languages, it was throwing errors. Is there any way where I could combine these two different language models for recognition?

Thanks in advance :)

**Comment by lukastryner** [comment]
Hello,
we have similar experience for Czech and Polish languages. We have found out that there are mising at least few Czech letters in `easyocr/config.py` - namely `č`, `ř`, which are then miss-predicted or not predicted at all. We have tried to add them there manually, but we've received dimension error of the pre-trained weights (so they were probably not included in the training at all?). Therefore we are also interested in the solution of this problem (how to add those letters, retrain the model, ...). ;)

**Comment by rkcosmos** [comment]
new model released in version 1.3.0.1. Characters in the new Latin model (latin_g2) are " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~ªÀÁÂÃÄÅÆÇÈÉÊËÌÍÎÏÐÑÒÓÔÕÖØÙÚÛÜÝÞßàáâãäåæçèéêëìíîïðñòóôõöøùúûüýþÿĀāĂăĄąĆćČčĎďĐđĒēĖėĘęĚěĞğĨĩĪīĮįİıĶķĹĺĻļĽľŁłŃńŅņŇňŒœŔŕŘřŚśŞşŠšŤťŨũŪūŮůŲųŸŹźŻżŽžƏƠơƯưȘșȚțə̇ḌḍḶḷṀṁṂṃṄṅṆṇṬṭẠạẢảẤấẦầẨẩẪẫẬậẮắẰằẲẳẴẵẶặẸẹẺẻẼẽẾếỀềỂểỄễỆệỈỉỊịỌọỎỏỐốỒồỔổỖỗỘộỚớỜờỞởỠỡỢợỤụỦủỨứỪừỬửỮữỰựỲỳỴỵỶỷỸỹ€". You can also use allowlist or blocklist to control which characters you want to use.
