### ISSUE TITLE
Uyghur Language

### ISSUE THREAD

**Issue by Abdusalamstd** [JaidedAI/EasyOCR#36]
I would like to help with the addition of the Uyghur Language ... what is needed to be done ?

**Comment by arulrajnet** [comment]
Already explained here

https://github.com/JaidedAI/EasyOCR/issues/25#issuecomment-653745636

**Comment by rkcosmos** [comment]
I'm not a language expert so you have to help me understand Uyghur language a bit. From first look, it looks like Arabic language. Let me ask a few question.

1. Is Uyghur using the same script as Arabic? Or are there additional script? 
2. I know that in Arabic there is a specific pattern when you write character next to each other to create a word. Is Uyghur using the same pattern?

**Comment by Abdusalamstd** [comment]
> I'm not a language expert so you have to help me understand Uyghur language a bit. From first look, it looks like Arabic language. Let me ask a few question.
> 
> 1. Is Uyghur using the same script as Arabic? Or are there additional script?
> 2. I know that in Arabic there is a specific pattern when you write character next to each other to create a word. Is Uyghur using the same pattern?

Reply: 1.There additional script in Uyghur,Not exactly the same.
2.Yes,Uyghur using the same pattern.

**Comment by rkcosmos** [comment]
According to Wikipedia, it seems like you have 4 set of alphabets.

1. Uyghur Arabic alphabet or UEY
2. Uyghur Cyrillic alphabet or USY
3. The Uyghur New Script or UYY
4. Uyghur Latin alphabet or ULY 

We currently have Latin model. Arabic and Cyrillic are on the way. If Uyghur use all 4 set of alphabet above, then it's not gonna be easy. You can create a pull request to add all characters and words (see #25 ), but I cannot promise to do it in the near future because my priority will have to go to popular language or set of languages that share most of characters together.

**Comment by Abdusalamstd** [comment]
> According to Wikipedia, it seems like you have 4 set of alphabets.
> 
> 1. Uyghur Arabic alphabet or UEY
> 2. Uyghur Cyrillic alphabet or USY
> 3. The Uyghur New Script or UYY
> 4. Uyghur Latin alphabet or ULY
> 
> We currently have Latin model. Arabic and Cyrillic are on the way. If Uyghur use all 4 set of alphabet above, then it's not gonna be easy. You can create a pull request to add all characters and words (see #25 ), but I cannot promise to do it in the near future because my priority will have to go to popular language or set of languages that share most of characters together.

Thanks for your reply!
Of the above four model, first model(Uyghur Arabic alphabet or UEY) is the most widely used. So just add first model(Uyghur Arabic alphabet or UEY) . I have finished the alphabet file "ug_char.txt", and now preparing the 'dict/ug.txt' common Uyghur words file.

**Comment by rkcosmos** [comment]
please make sure 'dict/ug.txt' has enough words (other languages has ~30000).

**Comment by hilaloytun** [comment]
> "ug_char.txt", and now preparing the 'dict/ug.tx

Hello, If it's not too much to ask, could you please share with me the "ug_char.txt", and "dict/ug.tx" files you prepared for Uygur, so that I can use  them for my language?

**Comment by Abdusalamstd** [comment]
> > "ug_char.txt", and now preparing the 'dict/ug.tx
> 
> Hello, If it's not too much to ask, could you please share with me the "ug_char.txt", and "dict/ug.tx" files you prepared for Uygur, so that I can use them for my language?

You can download it from this EasyOCR  project repository.
