### ISSUE TITLE
Vertical margins in the detected boxes from easyocr.detect don't have a consistent behavior

### ISSUE THREAD

**Issue by fxmarty** [JaidedAI/EasyOCR#360]
When setting `add_margin=0` (not sure about other cases), some boxes detected with `easyocr.detect` still have a border while some don't, as illustrated below.

## How to reproduce ##
Download
![花火 Fireworks 1997 iNT DVDRip XviD0316](https://user-images.githubusercontent.com/9808326/106395484-ca333d80-6402-11eb-8c27-2ed49cc0795b.png)

Execute
```python
import torch
from easyocr import Reader
import numpy as np
import cv2
import matplotlib.pyplot as plt

reader = Reader(['ja'])

filename = '/path/to/file.png' # change accordingly
img = cv2.imread(filename, 1)

# Here we add some white border to the image
h,w=img.shape[0:2]
border = 50
base_size=h+border,w+border,3
base=np.zeros(base_size,dtype=np.uint8) + 255
base[border//2:border//2 + h, border//2:border//2 + w]=img

# Detect boxes, without margins
result = reader.detect(base, add_margin=0)
```

Then execute
```python
k = result[0][0]
cv2.rectangle(base, (k[1], k[3]),
            (k[0], k[2]),
            (0,0,255),
            1)

plt.imshow(base)
plt.show()
```
and

```python
k = result[0][1]
cv2.rectangle(base, (k[1], k[3]),
            (k[0], k[2]),
            (0,0,255),
            1)

plt.imshow(base)
plt.show()
```

This returns
![image](https://user-images.githubusercontent.com/9808326/106395451-a243da00-6402-11eb-89aa-c697a0515a99.png)

and
![image](https://user-images.githubusercontent.com/9808326/106395470-b8519a80-6402-11eb-8e2a-2b42265b81b8.png)

As you can see, the first one *has* borders, while the second *do not*.

I guess it is not too big of an issue, and it can be solved manually, but still, it is not expected behavior here.

Thank you!

**Comment by rkcosmos** [comment]
`add_margin` is an extra margin in addition to the output from text detection. Text detection is deep learning-based algorithm and may introduce its own small margin.

**Comment by fxmarty** [comment]
I see, seems very reasonable. Thank you for your help.
