### ISSUE TITLE
Any tutorial to train / fine-tune the model for more fonts (new dataset)? Any Update?

### ISSUE THREAD

**Issue by hahmad2008** [JaidedAI/EasyOCR#365]
Thanks for publishing this great EASYOCR model!
I am wondering if I can find a tutorial to train EASYOCR or finetune it on a custom dataset ( where I need to add a complex background for texts and support new fonts).

What do you think? is there any link for that?

Any update?

**Comment by shgidi** [comment]
I think about writing such tutorial if there is interest and it's ok with author

**Comment by rakesh4real** [comment]
@shgidi how are you planning to do it. Can you please explain? Planning to take model and write your own training script?

**Comment by shgidi** [comment]
@rakesh4real Generally this repo is based on another [repo ](https://github.com/clovaai/deep-text-recognition-benchmark) as stated in README, which has a training script. You need to train it on your data (or generate data) and teark a few configurations to plug it into this repo. 
As said, I plan to write a tutorial about it.

**Comment by mjack3** [comment]
Hello @shgidi i have trained my own TPS-ResNet-BiLSTM-Attn OCR model from the original [repo](https://github.com/clovaai/deep-text-recognition-benchmark). Do you know how could I use it in this repo? Thanks

**Comment by shgidi** [comment]
@mjack3 In this repo the default is None-ResNet-BiLstm-CTC. Changing this structure will require extensive code changes. Also, hidden size is 512.

**Comment by mjack3** [comment]
@shgidi thank you! Just a last question. Whether i have trained a none-resnet-bilstm-ctc.pth in a 

**dict.txt > ABCABC** 
with a 
**vocab.txt > ABC**

Should i change something in this rwpository after to use the custom none-resnet-bilstm-ctc.pth?

Thanks!!

**Comment by mjack3** [comment]
@shgidi just a last question. If this repo use CRAFT and a none-resnet-bilstm-cyc.pth. Why is need specify a lang and a dict? I mean, the ocr network from the original repo, after training is enough if we set the default vocab.

**Comment by shgidi** [comment]
@mjack3 I don't 100% understand what you mean. If you use a language that the package supports it should work. You should change some configurations of the model file in the code - clearly the path, and also insert the mdsum of your model file in the right place

**Comment by mjack3** [comment]
@shgidi ok, i will try again (sorry my english is not my language)

1. Firstly i generated my own dataset using [TextRecognitionDataGenerator](https://github.com/Belval/TextRecognitionDataGenerator). Here i used my own dict.txt
2. Secondly, i trained my own OCR network using [deep-text-recognition-benchmark](https://github.com/clovaai/deep-text-recognition-benchmark).
3. Then i can do inference with no need of specify any language, just the characters/vocab in the [network.character](https://github.com/clovaai/deep-text-recognition-benchmark/blob/6dc16df598d986d0ee872816a3fc8ef5f6c11183/train.py#L239) 


My Question is, if this repository use the previous repositories (with CRAFT), why do i need specify any language if is not needed in the OCR repo?

Example:
reader = easyocr.Reader([**'en'**])

**Comment by LanzaMercado** [comment]
Hi, any news on this topics?

**Comment by groupgithub21** [comment]
If anyone has such a tutorial on finetuning of the models, do post it ?
Thanks

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).

**Comment by nadhirhasan** [comment]
I've recently created a notebook on finetuning EasyOCR, which I believe can provide you with a better understanding if you take a look.

EasyOCR finetuning: https://www.kaggle.com/code/nadhirhasan/let-s-finetune-easyocr-boom/notebook
Inference Notebook: https://www.kaggle.com/code/nadhirhasan/check-the-performance-of-our-finetuned-ocr-model

**Comment by EivindKjosbakken** [comment]
I wrote an article on [fine-tuning easy OCR on Medium](https://medium.com/towards-artificial-intelligence/how-to-fine-tune-easyocr-to-achieve-better-ocr-performance-1540f5076428), hopefully, this can be of help. Thank you to @rkcosmos for referring to [a useful note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md)
