### ISSUE TITLE
Error in downloading Languages in EasyOCR- OS Error and URL Error- Help 

### ISSUE THREAD

**Issue by thanveerkamal** [JaidedAI/EasyOCR#366]
I face this error, kindly help,  I am new to this OCR topic...

![Screen_11](https://user-images.githubusercontent.com/68006485/106903189-b39d2700-671f-11eb-8ecf-184afc983bf4.png)
![Screen_12](https://user-images.githubusercontent.com/68006485/106903198-b5ff8100-671f-11eb-9f06-279ebc8cb5dd.png)
![Screen_13](https://user-images.githubusercontent.com/68006485/106903199-b6981780-671f-11eb-9b63-a3cd72205663.png)

**Comment by rkcosmos** [comment]
there are manual download links in readme.
