### ISSUE TITLE
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.

### ISSUE THREAD

**Issue by Niotferdi** [JaidedAI/EasyOCR#370]
I enter the command `easyocr -l ru en -f pic.png --detail = 1 --gpu = true` and then I get the message `CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU. `, and then, in the task manager, the increased load on the CPU is displayed, instead of the increased load on the GPU.
My graphics card is GTX 1080 ti, it supports CUDA. But easyocr can't use GPUs.

**Comment by rkcosmos** [comment]
make sure you install pytorch properly. Please follow the official pytorch installation guide. You may want to check your GPU driver as well.

**Comment by FinalSh4re** [comment]
Nvidia provides a step by step guide to setup cuda on your machine:

1. Linux: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
2. Windows: https://docs.nvidia.com/cuda/cuda-installation-guide-microsoft-windows/index.html

**Comment by sifeizhai2017** [comment]
what if i am using a mac without a nvidia display card?

**Comment by spsrathor** [comment]
what if I am using Colab..??

**Comment by FinalSh4re** [comment]
As far as I know GPU computing is disabled on Google Colab by default . To activate cuda support go to: 

```
Runtime > Change runtime type
```
and select GPU. Your code should now be able to make use of the graphics card.

**Comment by michel-ch** [comment]
> i think your code don't use your display card. If easyocr experiencing the error let him use reader = easyocr.Reader(['en'],bool = True)

pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117
