### ISSUE TITLE
Small mistake in group_text_box() method

### ISSUE THREAD

**Issue by chamecall** [JaidedAI/EasyOCR#372]
Hi there.
There is a small mistake in [this line](https://github.com/JaidedAI/EasyOCR/blob/7c94caa2a2933617dd9b7d0c6dd6d356b1309c50/easyocr/utils.py#L479).
Here we are comparing distance between boxes `abs(box[0]-x_max)` with a box **height** multiplied by width coeff `width_ths *(box[3]-box[2])` instead of a box **width**.
So all that needs to be changed is to replace `box[3]-box[2]` with `box[1]-box[0]`.

**Comment by rkcosmos** [comment]
that's intentional.
