### ISSUE TITLE
How to generate model for natural language

### ISSUE THREAD

**Issue by arulrajnet** [JaidedAI/EasyOCR#38]
Hi

I have characters file and dict file for a natural/spoken language. How to generate pytorch model (pth file) for it.

**Comment by rkcosmos** [comment]
What is character for 'natural' language?

**Comment by arulrajnet** [comment]
Hi Rakpong

I am adding characters file in [easyocr/character/](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/character) folder and adding word list file in [easyocr/dict/](https://github.com/JaidedAI/EasyOCR/tree/master/easyocr/dict) folder for a spoken language. Now I want to generate model file for that. You have generated those files and uploaded in GDrive. For example this is for [Thai](https://drive.google.com/file/d/14BEuxcfmS0qWi3m9RsxwcUsjavM3rFMa/view?usp=sharing)

I am asking, how to generate those model files for newly adding language?

@rkcosmos

**Comment by rkcosmos** [comment]
The process involves several steps that I am not open-source it yet. Maybe I'll do it in the future.
