### ISSUE TITLE
Vertical recognition

### ISSUE THREAD

**Issue by miliadis** [JaidedAI/EasyOCR#382]
Hi there,

I think there are few issues with vertical words.

Shouldn't this function https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/easyocr.py#L344 output `max_width` as well in order to update `max_width = max(max_width, imgH)` in the next line ? It seems that if there is a long vertical word then it's capped by imgH and recognition is usually wrong.

Also, I realized that images are cropped and resized in here https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/easyocr.py#L341 based on their ratio which makes long image crops, that is h >> w, very small (their width is squeezed a lot). Then, these resized images are rotated (90, 180 and 270) in https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/easyocr.py#L344. I think the images should be rotated before they get resized.

**Comment by johan456789** [comment]
This can be closed now that the PR is merged?

**Comment by miliadis** [comment]
Yes, thank you.
