### ISSUE TITLE
How change to my ready custom network 

### ISSUE THREAD

**Issue by mjack3** [JaidedAI/EasyOCR#388]
Hello.

I have trained a None-ResNet-BiLSTM-CTC network with the classes 0123456789abcdefghijklmnopqrstuvwxyzñ-  in the original repo, using the data generator mentioned in this repository.

How could i use my own .pth it in this repository? I am working on it but i cant get it

**Comment by kimlia545** [comment]
How did you use the custom model?

**Comment by Rosyuso** [comment]
hey, i have the same problem,Have you solved it?

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
