### ISSUE TITLE
TypeError: super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by mateuszwosinski** [JaidedAI/EasyOCR#393]
While initializing model according to README, I've got the following error:
![Zrzut ekranu z 2021-03-12 07-27-35](https://user-images.githubusercontent.com/53553338/110901518-b8e42780-8304-11eb-8bf0-6d378719748f.png)

**Comment by rkcosmos** [comment]
Do you still have this problem? We never see this error before.
