### ISSUE TITLE
Perform OCR multiple images at the same time?

### ISSUE THREAD

**Issue by harsh-miv** [JaidedAI/EasyOCR#394]
I am using easyocr on a GPU, but the overall time taken for my dataset is large and my GPU are not being fully utilized, is there a way to group together images and using GPU to its max extent?

**Comment by rkcosmos** [comment]
try adjusting batchsize (see [documentation](https://www.jaided.ai/easyocr/documentation/) )

**Comment by alexander-soare** [comment]
@rkcosmos thanks for picking up on this. It's not clear to me how to pass in a batch of images corresponding to batch size. I have tried with a list bit I get the misleading `NameError: name 'LOGGER' is not defined` error.

**Comment by sangeethkumar1997** [comment]
@rkcosmos result_batch = reader.readtext(i,detail = 0,batch_size=64) 

i is of shape (64, 256, 256, 3) , But it is expecting np array of len(img.shape) less than or equal to 3.

UnboundLocalError: local variable 'img' referenced before assignment

**Comment by rkcosmos** [comment]
Input image has to be one image (not array of images). This `batch_size` means EasyOCR will create batch of several text boxes to be recognized at the same time internally. Batch of several input images is not supported.

**Comment by sangeethkumar1997** [comment]
@SamSamhuns That would be great!

**Comment by SamSamhuns** [comment]
#458 PR has been created for the batched image inference for text detection as well, @rkcosmos  please have a look
