### ISSUE TITLE
Error: Could not initialize NNPACK! Reason: Unsupported hardware.

### ISSUE THREAD

**Issue by kaisark** [JaidedAI/EasyOCR#397]
I ran into the following error running easyocr example on Ubuntu18 inside VirtualBox (Ubuntu18-VirtualBox). Is virtualization supported?

Python 3.7.9 (default, Aug 31 2020, 12:42:55) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import easyocr
>>> reader = easyocr.Reader(['ch_sim','en']) # need to run only once to load model into memory
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
>>> result = reader.readtext('chinese.jpg')
[W NNPACK.cpp:80] Could not initialize NNPACK! Reason: Unsupported hardware.
>>>

**Comment by rkcosmos** [comment]
Sorry, we didn't do any test on VirtualBox.
