### ISSUE TITLE
Wrong OCR Result

### ISSUE THREAD

**Issue by Biswasahu7** [JaidedAI/EasyOCR#398]
Hi Team,
I am passing one jpg image to easycore to extract the number, but result is not coming accurately.

My Original image number is: 2140093603AT

Easycore result is coming: 2.1400136030.

Note plase help me on this how can I train our own dataset in easyocr.

**Comment by rkcosmos** [comment]
try `allowlist` and `blocklist`.

**Comment by RamanHacks** [comment]
Do check out [UCR](https://github.com/DocYard-ai/UCR) library or [MMOCR](https://github.com/open-mmlab/mmocr) if you want to train with your own dataset!

**Comment by hahmad2008** [comment]
@RamanHacks Is there any direct and simple tutorial to train MMOCR you shared in a new language?
