### ISSUE TITLE
web demo 

### ISSUE THREAD

**Issue by linpan** [JaidedAI/EasyOCR#40]
I can help web demo for better experience.

**Comment by rkcosmos** [comment]
Sure, please send a PR.

**Comment by swuecho** [comment]
tried the demo with some random pic, the accuracy is quite well, but very slow with CPU only. 

for web demo, the machine might cost a lot with GPU i guess.

**Comment by rkcosmos** [comment]
Yes, initially I wanted to create a demo on website too. ... I think what @linpan suggest is like flask app browser demo that can run locally. It is quite common in Chinese repo.

**Comment by rkcosmos** [comment]
done by #176
