### ISSUE TITLE
Lower accuracy when selecting english and kannada togehter

### ISSUE THREAD

**Issue by rajat-008** [JaidedAI/EasyOCR#401]
Hey!
Firstly great project!
I was trying EasyOCR in two modes-
1. only english - the accuracy is good but also attempts to predict kannada
2. kannada and english- the accuracy drops and the prediction for english too is very bad
The results are for the same image.
Any ideas on how I can resolve this issue?

**Comment by rkcosmos** [comment]
We used different models for english only and kannada+english. You might want to run the same image twice, get two set of prediction and compare confident score of each text box.

**Comment by rajat-008** [comment]
Oh, so this is why there's this discrepancy.
Thanks a lot.
It makes much more sense now.
