### ISSUE TITLE
Segmentation Fault 11 when trying to import package or even running EasyOCR in terminal

### ISSUE THREAD

**Issue by adityashukzy** [JaidedAI/EasyOCR#402]
**System Specs:**
Macbook Air 2017
macOS Big Sur

**Problem**
I did `pip install easyocr` and installed easyocr. I see it in my pip list but when I try to do import easyocr it throws a `Segmentation Fault: 11`. I tried opening the Python interpreter in the terminal and trying `import easyocr` to which I got the same segfault (I tried importing another package which worked perfectly). Then I tried just running the command `easyocr` on terminal and I got the same result.

This leads me to believe that the problem isn't with my code or anything but rather with easyocr's compatibility with macOS.

I uninstalled and reinstalled easyocr through pip but to no avail. This seems to be an issue with easyocr although I am no expert so feel free to correct me. If I'm doing something wrong or haven't provided some critical information, let me know so I can better describe the exact nature of the problem.

**Comment by rkcosmos** [comment]
Do you have another file called `easyocr.py` in your system? You can also try to install directly from github by enter `pip install git+git://github.com/jaidedai/easyocr.git` in terminal.
