### ISSUE TITLE
Generation2 model files does not work with Pytorch 1.4

### ISSUE THREAD

**Issue by suyanzhe** [JaidedAI/EasyOCR#405]
Trying to load generation 2 models with `reader = easyocr.Reader(['en'], download_enabled=False)` yields the following error with PyTorch 1.4:
`RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:132)`

**Comment by rkcosmos** [comment]
thanks for the report.

**Comment by SuJiaKuan** [comment]
Same issue for me. Update PyTorch 1.7 will resolve the problem.
