### ISSUE TITLE
It can't be recognized correctly on MAC M1

### ISSUE THREAD

**Issue by huwei1024** [JaidedAI/EasyOCR#406]
It can't be recognized correctly on MAC M1, but it works normally on windows.

**Comment by rkcosmos** [comment]
Thanks for the report, we don't have access to M1 for testing. We don't have a plan to support M1 yet.

**Comment by baihaqi-htp** [comment]
Hi, is it still not supporting on Mac M1?

**Comment by minusplusminus** [comment]
Got it working with installing from source

```
brew install openblas gfortran
brew install xz # To pick up liblzma
prefix=$(brew --prefix)
export LDFLAGS="-L$prefix/opt/xz/lib $LDFLAGS"
export CPPFLAGS="-I$prefix/opt/xz/include $CPPFLAGS"
export PKG_CONFIG_PATH="$prefix/opt/xz/lib/pkgconfig:$PKG_CONFIG_PATH"
PYTHON_CONFIGURE_OPTS="--enable-shared" pyenv install 3.9.5 


export OPENBLAS=/opt/homebrew/opt/openblas/lib/
pip3 install torchvision torch scikit-image pillow  pybind11  pythran
pip3 install numpy --compile --pre  
pip3 install scipy --compile --pre 
python3 setup.py install
```

**Comment by pannous** [comment]
Works out of the box on M1 now, but doesn't make use of tensorflow-macos (?)

**Comment by bhuiyanmobasshir94** [comment]
Can anyone write the complete solution on how to work with Mac M1? Thank you.

**Comment by bhuiyanmobasshir94** [comment]
My application stops while using the `readtext` function on Mac M1

**Comment by abyesilyurt** [comment]
Turning off quantization in `easyocr.Reader` fixes this problem on M1.
```
self.ocr_reader = easyocr.Reader(["en"], gpu=False, quantize=False)
```
