### ISSUE TITLE
Can we run EasyOCR to just predict numbers with highest accuracy by removing english characters?

### ISSUE THREAD

**Issue by sgupta65lti** [JaidedAI/EasyOCR#407]
First of all, Thanks to the developer team at EasyOCR for their great efforts!
I need a little help here.
I am trying to use EasyOCR to extract numbers from images which are like OCR-A font along with usual numbers. if there could be a way to remove predictions for english letters, i think my task will be done.
Thanks again!

**Comment by samayala22** [comment]
Hello, if you only want numbers to be recognized:  

```python
result = reader.readtext(input, allowlist ='0123456789')
```
