### ISSUE TITLE
image type and resolution

### ISSUE THREAD

**Issue by ideastudios** [JaidedAI/EasyOCR#408]
Hi bro,
your code is very useful for me to fit some image problem but I have some question about the detail.
1. what kinf of type of image your can recongnise?
2. do you have some limit about image quality?

feel free to contact me: mcy18001169893@163.com

thx!

**Comment by ChinmayBH** [comment]
Hello! I am curious to know what is the answer to 2nd question.EasyOCR trouble when resolution drops. So I wonder if there is any threshold image quality or resolution above which we will surely get output?Thanks!
