### ISSUE TITLE
Missing information while extracting text from similar images

### ISSUE THREAD

**Issue by RishikMani** [JaidedAI/EasyOCR#412]
I have similar set of images from which I am trying to extract. On some images it is working good but on certain it misses necessary information. The images have texts written on them in German.

In the first image the information "Verkauft" could not be extracted, while in the next image it was extracted. I had such images and roughly only 50% of times the text "Verkauft" is extracted.

![Sischu 17](https://user-images.githubusercontent.com/27825015/113287491-f3caf100-92ed-11eb-9bad-6686263cd220.JPG)

![Sischu 4](https://user-images.githubusercontent.com/27825015/113287558-09401b00-92ee-11eb-86fc-7992d036fe85.JPG)

What could be the probable cause of this? Does anyone have any input on this?

**Comment by samayala22** [comment]
Try this: 
```python
result = reader.readtext(img,detail=0,rotation_info=[90, 180 ,270])
```
It will rotate the textboxes and return the one with the best confidence score. I tried it on the first image and it worked perfectly.

**Comment by RishikMani** [comment]
Thank you for this amazing reply. It helped me.
