### ISSUE TITLE
Help to recognize this images

### ISSUE THREAD

**Issue by mjack3** [JaidedAI/EasyOCR#413]
Hey there, I am trying to get information from images

![image](https://user-images.githubusercontent.com/37028633/113571204-39512c00-9616-11eb-96b7-deb9276aaf87.png)
![image](https://user-images.githubusercontent.com/37028633/113571546-dad87d80-9616-11eb-8719-6ee5d884c90b.png)

I need to get the long number just in the middle of the label (down of system text in the second example). For this example, i would need:
First image: **08** **0235804**
Second image **08** and **3559364**
But CRAFT can't recognize the zone with the numbers. how could i get it?

Actually i am trying this code

`eader.readtext(image, decoder="greedy", beamWidth=5, batch_size=8,
                                     workers=4, allowlist="0123456789", blocklist=None, detail=1,
                                     rotation_info=[-30, -15, 15, 30], paragraph=False, min_size=1,
                                     contrast_ths=0.1, adjust_contrast=0.5, filter_ths=0.003,
                                     text_threshold=0.025, low_text=0.4, link_threshold=0.4,
                                     canvas_size=1280, mag_ratio=1.5,
                                     slope_ths=0, ycenter_ths=0, height_ths=0,
                                     width_ths=0, add_margin=0.1)`

**Comment by rkcosmos** [comment]
Is it possible to have an image with higher resolution? Eligible values in `rotation_info` are 90,180,270 (see https://www.jaided.ai/easyocr/documentation/) and `beamWidth` is not used for `greedy` decoder so you can skip that.

**Comment by mjack3** [comment]
At the moment is not possible. And thank you for ur indications about beamsearch and rotation info

**Comment by RamanHacks** [comment]
You can try [UCR](https://github.com/DocYard-ai/UCR#readme) library to see if the results are any better.

**Comment by mjack3** [comment]
@RamanHacks i didnot know this repo.
