### ISSUE TITLE
Columns of text are being merged in OCR result. How to read text from columns without merging bounding boxes?

### ISSUE THREAD

**Issue by farazk86** [JaidedAI/EasyOCR#414]
Hi,

I want to perform OCR on the following image:

![23_1](https://user-images.githubusercontent.com/33456896/113884113-a26fa580-97b6-11eb-8cff-917dd393b572.jpg)

As can be seen, there are 3 columns of the main text. Which should be 3 separate bounding boxes. But the output is merging all 3 and reading them as one, for example the output from ``reader.readtext(img, detail=0, paragraph=True, decoder='beamsearch') ``is:

> Peter; Chris and Sarah were London (Tfl) to extend the extension is Thousands of delighted to join Harriet Bakerloo line from Elephant to people travel from; to and

I even tried changing the margin parameters to prevent combining the bounding boxes:
```python
text = reader.readtext(img, detail=0, paragraph=True, decoder='beamsearch', add_margin=0, width_ths=0)
```
and 
```python
text = reader.readtext(img, detail=0, paragraph=True, decoder='beamsearch', add_margin=0, width_ths=1)
```

both produce the same output, that merge the columns. 

What can I do to prevent this merging and consider these as separate bounding boxes?

Thank you

**Comment by rkcosmos** [comment]
With `paragraph=True`, `width_ths` is not being used. The code is currently using another parameter (`x_ths` in utils.py) which unfortunately is not accessible via standard api at the moment. I'll add this in the next release.

**Comment by farazk86** [comment]
> With `paragraph=True`, `width_ths` is not being used. The code is currently using another parameter (`x_ths` in utils.py) which unfortunately is not accessible via standard api at the moment. I'll add this in the next release.

Thanks for the reply. Since this parameter is not visible to me, would it be possible to let me know when is the next release expected?

Thanks

**Comment by RamanHacks** [comment]
You can use newly release [layout-parser](https://github.com/Layout-Parser/layout-parser) library for parsing paragraphs into different chunks, then paragraph=True won't be required.

**Comment by farazk86** [comment]
> You can use newly release [layout-parser](https://github.com/Layout-Parser/layout-parser) library for parsing paragraphs into different chunks, then paragraph=True won't be required.

Thats very helpful, thank you. But it depends on Detectron2, which is Linux only and does not work on Windows, unless I'm mistaken,.

**Comment by rkcosmos** [comment]
next release is within 1 week.

**Comment by rkcosmos** [comment]
Last code update allow you to use both `x_ths` and `width_ths` to control merging behaviour when setting `paragraph=True`. Setting both to zero should give you desirable outcome. You can install the latest version by `pip install git+git://github.com/jaidedai/easyocr.git`. Pip version will be updated soon after some tests.

**Comment by farazk86** [comment]
> Last code update allow you to use both `x_ths` and `width_ths` to control merging behaviour when setting `paragraph=True`. Setting both to zero should give you desirable outcome. You can install the latest version by `pip install git+git://github.com/jaidedai/easyocr.git`. Pip version will be updated soon after some tests.

Hi, 
with the new update, I am still getting the same result. The image shown above is getting its text boxes merged.

**Comment by rkcosmos** [comment]
Here is my test on your image.

![Screenshot from 2021-05-07 10-07-12](https://user-images.githubusercontent.com/12238328/117392360-2040e100-af1c-11eb-8a8c-5d96f6ff9b97.png)

**Comment by farazk86** [comment]
> Here is my test on your image.
> 
> ![Screenshot from 2021-05-07 10-07-12](https://user-images.githubusercontent.com/12238328/117392360-2040e100-af1c-11eb-8a8c-5d96f6ff9b97.png)

Thanks, thats the expected correct result. And the reason I wasn't getting this result is that I was missing the ``x_ths`` parameter. What is this parameter? Its not in the [API documentation](https://www.jaided.ai/easyocr/documentation/)??

**Comment by rkcosmos** [comment]
I just updated [API documentation](https://www.jaided.ai/easyocr/documentation/).
