### ISSUE TITLE
Arguments and vertical Japanese text

### ISSUE THREAD

**Issue by TrocelengStudios** [JaidedAI/EasyOCR#416]
I have used EasyOCR successfully a few times now, however I'm running into issues. Firstly, a guide recommended using a "paragraph" argument. Putting "--paragraph=1" into my script caused an error called "Unrecognized arguments" and that error persisted on every variation I tried. Typing "easyocr -h" tells me that the options I can use are language, input file, detail of output and if I want to use GPU. These options seem very bare bones and in contrast to guides.

Also, Japanese vertical text does not work. It only grabs the uppermost character of each column and puts it on its own line in the output (which is very annoying even when it does manage to grab the text correctly). Can that be fixed? I tried downloading the bigger japanese.pth and replacing the one in the install directory, but the program deleted it. Is it not compatible with the latest git download? Did I get the wrong version? Is there even a way to check version? The standard "--version" did absolutely nothing.

One last thing, how do I make it stop pestering me about my two different GPUs?

To clarify, I'm using Windows 10's CMD to run EasyOCR.

**Comment by rkcosmos** [comment]
Sorry, not all arguments are accessible from command line yet. I'll update this in the next release within a week. As for vertical text, we don't have a model for that yet. We have a plan to support that but it's take a while. What is the warning about 2 gpus?

**Comment by TrocelengStudios** [comment]
Thanks for the answer, I don't always get those.

The warning is this: 

c:\users\datam\appdata\local\programs\python\python38\lib\site-packages\torch\nn\parallel\data_parallel.py:30: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 1 which
    has less than 75% of the memory or cores of GPU 0. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))

I'm afraid that if I set my 1070 as not visible I can't use it on some other software that doesn't yet work on Ampere. The GPUs in my system are a 3060 ti and a 1070.

Is there are any kind of ETA for vertical text? I have an app on my phone that can read vertical text but it's less accurate than EasyOCR and on mobile, which is a more limited environment.

**Comment by mudzap** [comment]
> Sorry, not all arguments are accessible from command line yet. I'll update this in the next release within a week. As for vertical text, we don't have a model for that yet. We have a plan to support that but it's take a while. What is the warning about 2 gpus?

What is the current limiting factor for the vertical text model? I'm not that familiar with ML, but I'm interested. From what I see, CRAFT works fine for vertical text.

**Comment by rkcosmos** [comment]
@TrocelengStudios  Last update allow argument setting from command line. You can install the latest version by `pip install git+git://github.com/jaidedai/easyocr.git`. Pip version will be updated soon after some tests. 

@mudzap EasyOCR is composed of 2 main parts, detection and recognition. CRAFT is doing fine for detection part but I still need a new recognition model for vertical text.

**Comment by abhishekvermasg** [comment]
@rkcosmos How do I contribute to this repo? I can fix the vertical text problem you are having.

**Comment by TrocelengStudios** [comment]
Thank you for the update, I'll look into getting as much ouf this OCR and I think settings will help.

Thinking of it, is the problem with vertical text a problem with the model itself, so that there would need to be a "ja-JP-ver" or a simpler formatting issue that could be done without changing the model? I'm fine with either, just would like for this to work for all kinds of Japanese text.
