### ISSUE TITLE
Cuda appears to be in use even when setting gpu=False

### ISSUE THREAD

**Issue by alexander-soare** [JaidedAI/EasyOCR#417]
I noticed this because I was already using up 95% of my GPU memory for another task. Then when I ran `reader.readtext` I got a `RuntimeError: cuda runtime error (2) : out of memory`.

This is how I create `reader`:

```
self.reader = easyocr.Reader(['en'], gpu=False)
```
and I can confirm that I get the following warning:

```
Using CPU. Note: This module is much faster with a GPU.
```

**Comment by rkcosmos** [comment]
thanks for the report, we'll investigate this issue.

**Comment by rkcosmos** [comment]
I found a [line](https://github.com/JaidedAI/EasyOCR/blob/3d0012d5932dccd1a1dc459322bbd1011ff09802/easyocr/recognition.py#L103]) causing this issue. According to a discussion in [pytorch's issue](https://github.com/pytorch/pytorch/issues/49401). The program is not actually consuming GPU memory but it is the effect of something else we do not have control. I understand this cuda runtime error is disturbing but I don't have an immediate/clean solution. I notice that the memory being used (or wrongly reported??? by `nvidia-smi`) in this case is relatively small (~700MiB in my case).

**Comment by alexander-soare** [comment]
I think it was pretty small. I just had something else running that was
using 99% memory which was the whole motivation for using CPU with EasyOCR
at the time.

**Comment by akshayklr057** [comment]
For me its using approximately 1GB of my GPU. Is there a way to resolve this?
