### ISSUE TITLE
I want to use a custom model

### ISSUE THREAD

**Issue by kimlia545** [JaidedAI/EasyOCR#420]
I want to use English as it is and only change the Korean model.
I put the files(korean_g3.yaml and korean_g3.pth) in the folder(user_network)

code
reader = easyocr.Reader(['korean_g3','en'], gpu=False, recog_network="korean_g3")

Some errors have occurred
1) ValueError: Korean_g3 is only compatible with English, try lang_list=korean_g3, en
2) AttributeError: module ‘korean_g3' has no attribute 'Model’
3) size mismatch for SequenceModeling.0.rnn.weight_ih_l0: copying a param with shape torch.Size([1024, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).

Thank you

**Comment by Rosyuso** [comment]
hi,where did you get the yaml file? i used  [https://github.com/clovaai/deep-text-recognition-benchmark](url) to train my dataset as recommended,but there's no yaml file exported.

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
