### ISSUE TITLE
Silence pytorch CUDA messages

### ISSUE THREAD

**Issue by thislooksfun** [JaidedAI/EasyOCR#421]
I want to be able to use easyocr in a pipeline using stdin/stdout, but parsing the output is non-trivial because of the warning message "CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU." (I don't have CUDA available atm unfortunately). Is there a way to silence this message to get clean output? I tried setting `verbose = False` in `easyocr.Reader` but that didn't work.

**Comment by rkcosmos** [comment]
ok, I'll make `verbose=False` suppress CUDA warning in the next version.

**Comment by rkcosmos** [comment]
repository updated, try latest version with `pip install git+git://github.com/jaidedai/easyocr.git` or wait a few week for official release.
