### ISSUE TITLE
How can I improve the recognition accuracy?

### ISSUE THREAD

**Issue by codingforpleasure** [JaidedAI/EasyOCR#424]
I have noticed I have used the identical model for both images  but with different scale I get a different result:

![question](https://user-images.githubusercontent.com/1729719/116984449-f0070180-acd3-11eb-828a-d811a39c0d17.png)

For some reason both the comma and equal sign is getting ignored for a small text,
Is there a way to get a more accurate result without up scaling the image?

I'd like to hear about other efficient different approaches,
any suggestion will be helpful

Thank you

**Comment by WiKC73** [comment]
You can adjust some parameters, for example:
import easyocr
reader = easyocr.Reader(['en'])
result = reader.readtext(width_ths=2)
