### ISSUE TITLE
Speed up the inference of easyocr model in GPU

### ISSUE THREAD

**Issue by uditdixit11** [JaidedAI/EasyOCR#426]
First, Thanks to the great efforts of developer team at EasyOCR!

I really need a help from you. Please help me providing info

How do I increase the speed of Easyocr model inference in GPU ? Can we use the techniques like TensorRT  or converting model into ONNX model to increase its speed ? Please help

**Comment by kbrajwani** [comment]
Hey @rkcosmos Can you tell me what's going wrong here? i have given a batch_size but time is increased.
![image](https://user-images.githubusercontent.com/29722986/119218834-187a6280-bb00-11eb-882e-046d5a76eaee.png)

**Comment by rkcosmos** [comment]
It depends on number of text box in the image. If the input image has a lot of text boxes, having batch_size>1 should give you a speedup. If you have only a few boxes in the image, it will be slower because there's a head start for parallelization.
