### ISSUE TITLE
Dynamic input size to train?

### ISSUE THREAD

**Issue by mjack3** [JaidedAI/EasyOCR#427]
Hello @rkcosmos , did you used a dynamic width in the training phase? Something like you did in the inference in this point

https://github.com/JaidedAI/EasyOCR/blob/ebc51fe33f2c3469dd4471141adc13b877c584a1/easyocr/easyocr.py#L317

or are you training with fixed width like 100 (by default) in the training repository?

**Comment by rkcosmos** [comment]
fixed width with padding for smaller images.
