### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by Dam2000** [JaidedAI/EasyOCR#432]
Hi, 

I'm using your OCR solution to replace my older one (Tesseract) because yours is easier to take hand and give better results in my case but i get a crash when i'm doing : result = reader.readtext(img). This  crash only happens when i try to treat image who have big resolution. I got a gtx 970 with 4gb of memory but the message seems to told me i have not enough memory to treat a big image (Exemple:  2500x3500 pixels). Is the only solution is to resize and reduce the size of the image because i have no problem with smaller image ? How to deal with loose of information due to resize ? 

Thanks 

Damien

**Comment by rkcosmos** [comment]
I think you need to resize. If you don't want to lose any information, crop the image and pass them to EasyOCR one by one.
