### ISSUE TITLE
Language detection?

### ISSUE THREAD

**Issue by jeremyevith** [JaidedAI/EasyOCR#433]
EasyOCR relies on loading user defined language model, what if we are not sure about the language on input image? is there any algorithm or network that can be used to detect the language before passing to EasyOCR? or do we need to train a big multi-lingual model that can recognize characters from different language at once?

**Comment by rkcosmos** [comment]
I think the proper approach is creating another network to detect language before passing to EasyOCR. I would be happy if anyone can point to any existing open source solutions.

**Comment by bertsky** [comment]
> I think the proper approach is creating another network to detect language before passing to EasyOCR. I would be happy if anyone can point to any existing open source solutions.

Tesseract [has this](https://tesseract-ocr.github.io/docs/Combined_Orientation_and_Script_Detection_using_the_Tesseract_OCR_Engine.pdf), but it's based on its pre-LSTM ("legacy" / single-char classifier) model [osd](https://github.com/tesseract-ocr/tessdata/raw/master/osd.traineddata), which contains a (somewhat) representative subset of various scripts:

<details><summary>see full character list here</summary>
<p>
के और अपने आज था न धं धा सा व आम मे थी प्रबं धन ० ई प्र जी थे सी ए आ दी दे आई नि म त धर्म उ बु ध २ ८ र क्षेत्र मै अ र्थ अल शि क्षा समी ओ सुर एस धार ध्य स ल क्ष्मी एम वी आर क्षण क्ष ओं टी अप क्षर पी एन य आउट सु सम वृ क विवि द इ धर ऐ ३ ह ला वि धों यू परी ग ४ धी धे कु क्ष्य यु सं ६ पा धान ५ प क्षक मि थुन ७ मु सुवि थ बं पि थल ऊ ओवर मं थन धू मा वीं अं ब धारा ऑन र्धन ९ पृ वें क्षे दु क्षकों धाम बे गु आन जु क्षों ओगे ऽ अपे वै अव धु अँ आरटी धक आं धीर ती र्धा आँ अन धारी ध्द आइ स्प अर कं ओन श्र सू सि धो क्षु في و ى لا لى صو ر ئي ن نو ما بر لمشا كا ت يا لمو ضو ع مشا هد ة بو بة م خر لعا ب ل ه ي لذ تا لر ية يد قا جو جد ء كة خا سا مو د ثا ني لعر بية لة لجو نا مر ض حة جر مة با يل ذ لك كو عا هو عد لبر يو له بنا قد سم ئد لخا لتو س غا تو ث علا لمر تر به عر ق لحا حو لي نت لسا عة لو ف ز نه بي لمد ضا فة لد سيا ش لقا قو طا شر سة لها طر ك شا جا يم ئية حد تك ير لنا كر سلا مي ص سر مية ها فر فا شو ط مسا لقر لبا لفر ضي ين هر ند سو تي يت لما مد لبو لشا يز لتر فو صر نك لغا تها نسا نها لحر معا هم كم خو يه حا بد عو لشر لية نيا صا وإ لز صد بأ عما لفا قة سي قر نة لجا ته نى غر نية ملا للا لسو مه بإ منا طو تد حر ليا عي عية مآ تأ للأ تنا ثر فأ 人 中 有 大 国 在 工 用 年 生 上 了 要 务 产 建 下 方 于 开 本 出 日 民 电 加 者 内 展 子 图 面 事 月 看 重 查 最 自 农 目 回 表 入 后 度 力 天 版 名 及 专 南 复 路 更 案 各 导 口 考 山 客 车 户 县 友 施 片 十 女 万 西 果 如 也 无 由 里 手 置 集 土 园 据 四 转 都 布 正 支 册 击 从 整 色 而 已 码 王 食 备 五 百 周 因 身 乡 世 先 参 免 两 才 星 老 去 声 又 石 未 己 春 干 帮 把 历 盘 存 卫 巴 反 争 克 众 团 属 铁 围 再 带 象 申 吧 极 男 居 木 士 足 层 白 夫 岛 走 币 致 止 献 升 毒 算 七 她 太 几 啊 史 套 田 革 概 央 甘 竞 失 死 双 角 罗 千 古 丰 席 故 互 且 希 夏 享 九 厂 届 陆 占 抓 母 血 饰 昨 予 虫 曲 岁 季 略 另 署 童 架 猪 牙 峰 朱 早 启 固 仓 赖 幕 困 肌 圈 缺 左 尿 甲 异 右 凡 午 齐 鲁 罪 乙 奉 甜 巨 皮 吸 董 肉 勇 丁 践 廉 束 逐 桌 妻 拿 腾 牛 久 魔 钟 虽 瓜 捷 毛 脚 辆 某 舞 靠 末 驾 鹏 斤 甚 旺 君 欠 酸 奋 腐 孕 陷 嘉 禽 尊 肤 轴 趣 狐 拆 楚 丙 寄 廖 狠 墅 柔 覆 砖 勘 勤 瓦 睡 卓 旭 触 替 幸 圆 呆 兄 旁 蛋 孟 蜂 缸 萨 刀 井 妮 壬 枪 寞 韦 募 佩 卢 丹 腰 體 泵 崔 盾 跃 丈 蝶 锯 碑 寺 尺 歹 呈 暑 奶 舱 玻 鑫 晰 吻 阱 孝 萎 萝 耳 嘴 宪 虾 蟹 姑 鼱 允 酬 孤 粤 鼻 垂 厉 吊 巢 奸 囊 岳 〇 邑 靶 勿 丑 屈 虐 帝 俺 麦 焕 衷 畏 屯 乾 炳 乃 芦 岔 蛛 雾 昵 荤 姆 劫 蚕 丢 赌 擎 咽 衰 幽 矛 扼 肚 胁 屬 矮 肇 夕 圃 蝴 夸 睾 巷 敷 酰 宰 膀 尹 酶 丸 胰 晕 氏 弄 罢 韭 肝 咱 妨 卸 虞 晒 尧 垒 丐 蔓 勾 豚 罩 鹰 汞 爬 夷 凸 掘 耒 丘 娩 耽 璐 屠 伽 坠 舅 舌 臣 饱 尸 禺 屡 摹 蠢 幺 脾 昂 莴 妃 叽 砸 坤 毗 靴 弧 岂 厘 裔 冉 魉 匾 酐 蚌 柄 斥 苋 肴 蘖 腺 虔 瞩 辜 啤 辕 盎 昏 卤 腋 舰 姗 姊 岙 巫 廓 奢 姝 數 咀 爪 挚 毋 膏 囧 栖 矢 國 甬 猴 匪 拷 蜀 窟 夯 歼 肽 匆 昧 辗 庸 禾 袤 荚 串 驽 堕 發 秭 и в н а с е д л я п о к т ч г з у б ь р м й ц х ж ю κ α τ ο ν ε σ ρ ש ל א ת ה ב י מ ר ק の る て し す と ト ま イ ス ク っ れ ア も プ ん く タ あ コ メ つ ロ レ マ カ せ ィ ム み ウ チ ち ュ わ や セ ョ エ へ オ ャ ナ ろ ケ ワ ヘ モ ノ ォ ね ゃ ょ ァ ヒ ユ ひ ヤ ﾌ ｸ ｽ ヶ ぬ ﾛ ｺ ｶ ﾀ ｻ ﾒ ﾋ ﾍ ﾏ ｹ ｱ ゥ ｷ ゅ ﾑ ﾁ ヌ ｵ ｬ ﾅ ｳ ヽ ﾓ ﾔ ヲ ｪ ﾇ ｫ ゝ ｾ ಮ ಹಾ ಉ ಸಂ ಪ ದ ಕ ಡ ವ ರ ಇ ತ ರೆ ಗ ಳು ನ ಸ ದು ಮಾ ಡಿ ಳ ದೆ ಹ ಟ ನ್ನು ನಿ ರು ದಿ ಕೆ ಲ ವು ಸಾ ರಾ ತಿ ಬ ಲಿ ಅ ಣ ಲ್ಲಿ ಪ್ರ ವಾ ಜ ನೆ ಆ ನಾ ವಿ ಕು ರಿ ಯಾ ಕಾ ಗಿ ಸಿ ಸು ಎ ಲ್ಲ ಯ ಶ ದಾ ಡು ಗೆ ಲಾ ತೆ ೦ ಗು ಳಿ 다 고 니 로 인 보 리 수 도 어 대 그 나 신 구 라 요 회 있 동 여 용 내 화 국 품 호 오 업 모 실 러 금 포 되 통 크 거 와 님 료 출 역 남 타 토 김 종 태 려 결 래 력 노 외 했 버 때 직 별 담 며 근 었 격 날 립 불 티 림 두 올 플 코 론 택 답 길 규 총 패 른 랑 열 겨 머 따 잡 절 걸 몰 누 됩 견 클 황 락 얼 엔 논 굴 억 랜 벌 팅 댓 랩 럽 쿠 링 져 봉 였 샵 냐 숙 냄 셔 왔 먹 략 엄 ㅋ 궁 폭 칼 랙 릴 층 끝 털 랍 켜 징 꾸 셨 슈 극 쳐 염 램 셀 닉 렸 융 붙 념 팔 딸 큐 돼 롯 캠 균 됐 찍 졌 땅 꿈 롭 납 났 렬 엑 ㅠ 탐 몽 짱 콩 퇴 꺼 닙 낙 찜 홀 봤 딱 컬 엽 괴 퀵 뢰 낌 탑 굿 띠 엠 랭 촛 떨 룡 킬 봐 쌀 낮 얻 쌈 쏘 봅 슘 럴 쪼 ㅜ 끄 깜 숲 렵 랬 롱 톤 톱 셜 벗 냈 ㅇ 쿨 눌 팸 렘 핍 폼 낼 렴 퀴 녁 옆 멸 짧 됨 팝 걱 랫 짤 닐 컵 깔 횟 ㄱ 굳 겸 팁 핀 렀 닛 붉 돕 툴 훨 쫑 벼 끊 뽀 굶 뇌 켰 ㅅ 겼 굵 똥 쩌 쩔 껴 ㄹ 쩍 꿀 겔 닮 톨 쉴 ㅁ ㅂ 탓 탱 곁 놨 땀 ㄴ 캄 찔 쿵 댁 뀐 껏 뽑 꽤 땡 겹 귤 죤 콕 끗 퐁 퀸 깝 쭉 ㄷ 쿡 쪄 꿨 싹 놔 칵 겪 껍 덥 찡 딜 뽕 껄 탬 렐 냉 젖 낱 궂 옹 꿍 탤 꿋 쨌 엎 쏭 뗄 꼈 뀜 쎌 쑹 멈 귄 껀 뵙 굼 깥 휼 켈 왁 ㉠ h e o a n d r 2 s 3 y u 0 m 5 c 4 6 8 7 p g 9 t i l ரு ன் அ த ம் வ ல் க ய ఈ లు గు ర్ ఉ గా ప్ర వ చ నం క నా న గ ఇ త ర ద న్ కు అ ని లో టి డ చి డి ఆ స య ము వి యా మా దు రా నే ను కి తి రు డు కా ణ సి కో ది సు పు దా చు సం పా తా బ న్న వు రం ప రి మ చే ఎ ట లా హ ల వా జ సా తు లి చె యి వే తో อ บ น ด ย ก ว ม ห า ล ะ ง ร er v en S B R b ei an te T w G H E P ar ও ২ ০ ৭ ৮ না এ আ বং ১ সং র বাং লা ৬ ৩ বা ক ৪ থা ৯ প্র ধান ম় পর পার ৫ টি স শু ব্ল গ ত প টা উ গু ল কার ণ ম য পা য়া পুর স্ব র্ণ বি মা ব ব্যা বার রর গ্রহ সা ধার ইং দর পন থ শ ন গর হ য়ার প্ত অ গো ৩৬ ধা ধ লি ট পূ ণা জ কা নে অি এি লো খা সাং ধ্য গা প্রা বাি ণ্ড নর লোর পুৰ രു ന്ന മ ല യാ ത ക ള് ന് യ ക്കു വി വ ര ങ്ങ മാ ന പ ല് സ ട 
</p>
</details>

This basically runs over a minimum number of characters (for the requested image/segment), trying to simultaneously detect their orientation (flip/reflect – i.e. 0° / 90° / 180° / 270°) and main script and picks the one with the strongest aggregated confidence over the next best candidate (if strong enough). 

IMHO It does not work reliably though. But the principle could of course be transferred to line-based recognizers with better coverage/robustness, too. The only problem I see with LSTMs is that the parameter space will become quite large (and sparse!) if you allow a significant number of characters from each of the major writing systems.

**Comment by bertsky** [comment]
And Kraken also [used to have this](https://github.com/mittagessen/kraken/blob/edfefd9c210a347e9d802a124aaa498a80262c66/kraken/pageseg.py#L412-L438), the model file is [still available](https://github.com/mittagessen/kraken-models/tree/master/clstm/script-detection). I don't know why it's been abandoned.

**Comment by ShankarParimi** [comment]
How can we detect the languages present in the input image? any conclusion on this ^?

**Comment by ShankarParimi** [comment]
@rkcosmos can auto language detection support be added to easyOCR, if yes i am intersted to contribute! kindly let me know.
