### ISSUE TITLE
Not detecting Single characters

### ISSUE THREAD

**Issue by ghareesh** [JaidedAI/EasyOCR#442]
Hi Team..
I see this is not detecting single characters.. Is there a way to set option for this?  Check "1" or "2" under Qty field in attachment for mentioned issue

![Screenshot 2021-05-31 at 7 24 19 PM](https://user-images.githubusercontent.com/53309257/120204398-613fc300-c246-11eb-9d2b-c8a42c4c5378.png)
Please help!!

**Comment by rkcosmos** [comment]
Single character is hard to detect. Try adjusting `text_threshold` and `low_text` arguments.
