### ISSUE TITLE
Text block detection

### ISSUE THREAD

**Issue by ghareesh** [JaidedAI/EasyOCR#443]
Hi Team..
Is there a way to detect text blocks using this tool? 

![image](https://user-images.githubusercontent.com/53309257/120204603-a237d780-c246-11eb-9cb4-b31915f7ccb7.png)

In example above, I need  the entire text content to be detected as a block (which is address) than separate text..

Any help will be appreciated!!

**Comment by rkcosmos** [comment]
use argument `paragraph`, see [documentation](https://www.jaided.ai/easyocr/documentation/).
