### ISSUE TITLE
Export model to ONNX

### ISSUE THREAD

**Issue by luozhouyang** [JaidedAI/EasyOCR#444]
Any plans to export models to ONNX?

**Comment by SamSamhuns** [comment]
I've made a PR for exporting the craft detector to onnx at #478. You can use the export.py script in that PR. 

However, exporting the recognition model in its current form still has some problems, so if anyone else can help with that, that'd be amazing.

**Comment by wCheddar** [comment]
For the `vgg_model` I think the fix is simple. Just replace the adaptative pooling layer with:

```python
class AvgLayer(nn.Module):
     def forward(self, input):
        return input.mean(3, keepdim=True)
```

I do not think I will have time to do a proper pr but the above should help someone.

**Comment by ziyeZzz** [comment]
Has anyone transferred the recognition model successfully?
