### ISSUE TITLE
In the case of  identity card recognition, sometimes it infers the last 'x' to '8'

### ISSUE THREAD

**Issue by dyther** [JaidedAI/EasyOCR#449]
Thanks for your  great work, it performs high-accuracy, but I found In the case of  identity card recognition, sometimes it infers the last 'x' to '8' .
How can i increse the accuracy of digit recognition?

**Comment by SamSamhuns** [comment]
In the `readtext` function call, change the decoder to `beamsearch` and increase `beamWidth` to see if results are improved.
