### ISSUE TITLE
[Bug] Colab is not working

### ISSUE THREAD

**Issue by MohamedAliRashad** [JaidedAI/EasyOCR#453]
I don't know if it is a DNS problem from my side or not

![Screenshot from 2021-06-10 09-56-42](https://user-images.githubusercontent.com/26205298/121487241-2ec66080-c9d2-11eb-8147-7d0550407d60.png)

**Comment by rkcosmos** [comment]
thanks for the report, I'm asking @korakot.

**Comment by rkcosmos** [comment]
fixed
