### ISSUE TITLE
Reformatting & beautifying code with pep8

### ISSUE THREAD

**Issue by SamSamhuns** [JaidedAI/EasyOCR#455]
Hi there @rkcosmos, just noticed there are a lot of unused imports and some code formatting that could be done better. I think it might be a lot easier to maintain. I'd like to help grow the project and let me know you want me to make a PR that you can verify. 

However, if you think the current format is fine, no issues at all. 

Plus, I have also edited the code to accept a batch of images for the detection part, let me know if you want me to create a PR for that as well. I can do these in stages so that you can verify the changes. 

<img width="873" alt="Screen Shot 2021-06-11 at 10 33 57 AM" src="https://user-images.githubusercontent.com/13418507/121641751-a498fd80-caa0-11eb-9f9c-c6df88ff40b5.png">

Anyway thanks for this awesome project!

**Comment by rkcosmos** [comment]
thanks, I'm looking at your PR. I will respond there.
