### ISSUE TITLE
GPU support issue

### ISSUE THREAD

**Issue by yfzhanggithub** [JaidedAI/EasyOCR#46]
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
what is the cuda version support please?
cudatoolkit: 10.1
Python: 3.7.7
EasyOCR: 1.1

**Comment by rkcosmos** [comment]
Do you have multiple GPU? Can you try gpu = 'cuda:0'? (see #22)

**Comment by rkcosmos** [comment]
This should be fixed by #50 .

**Comment by cvelas11** [comment]
I am trying to run easyocr in a different GPU than cuda:0 and get the same error message "module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:6"
