### ISSUE TITLE
Very useful but slow

### ISSUE THREAD

**Issue by seghier** [JaidedAI/EasyOCR#462]
Thank you very much for this, it is very very useful,but slow , can you make it faster with cpu?
and thank you many times.
And please add support to detect rotated texts
I test this in your website and it detect horizontal texts only, and i want detect just the texts in the black areas.

![image](https://user-images.githubusercontent.com/6026588/121971611-68ec8500-cd79-11eb-82f7-7ada614b5eda.png)

![image](https://user-images.githubusercontent.com/6026588/121971618-70139300-cd79-11eb-9214-6b07636c8dbe.png)

**Comment by rkcosmos** [comment]
open source version actually have 'rotation_info' argument for this issue.
