### ISSUE TITLE
FineTune easyOCR

### ISSUE THREAD

**Issue by groupgithub21** [JaidedAI/EasyOCR#465]
I signed up with http://www.jaided.ai/projects/finetune and there exists an option to fine tune models for one's usage. 

![image](https://user-images.githubusercontent.com/79553071/122410032-2d8aca00-cfb6-11eb-9cb2-0b8019b85630.png)

Is one able to do via code by ourselves from using the repo or is it part of an enterprise solution only ? 
In any case, We want to be able to have an option to fine-tune.
Irregardless, Keep the Good Work with your rep. :+1:

**Comment by rkcosmos** [comment]
Please see [this note](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
