### ISSUE TITLE
Add a simple model

### ISSUE THREAD

**Issue by keeganNull** [JaidedAI/EasyOCR#467]
I tried to use this package to finish a program to recognize the phone number. So I just need the program to recognize 10 numbers. I tried to add the "ch_sim" model and filter the answer to get the phone number,
But you know, it's too slow. So I really suggest that you can update a new model work for number recognition.
Btw this package is very easy for me to complete a model easily. I will recommend this package to others.

**Comment by rkcosmos** [comment]
Noted.
