### ISSUE TITLE
Model Combination

### ISSUE THREAD

**Issue by KEVIN666666666** [JaidedAI/EasyOCR#469]
Hi EasyOCR,

Thank you for the great repository! You guys are doing an amazing project!

For my project scenario, I need to detect all the French and Arabic in the input image.
I noticed that all language detection models are the same, using the CRAFT-MLT model. The difference for multi-languages is in the recognition model.

So I am considering can I combine the Arabic recognition model and the Latin recognition model?
To solve the problem, there are two plans in my mind:
1. use some technic to make the Arabic recognition model and the Latin recognition model into one model.
2. after detection, use the detection results first through the Arabic recognition model and then through the Latin recognition model.

Which plan you think is likely to solve the problem? And any suggestions?

Regards,
Kevin

**Comment by rkcosmos** [comment]
Second plan is much easier.
