### ISSUE TITLE
Web demo gives better results than code

### ISSUE THREAD

**Issue by herobd** [JaidedAI/EasyOCR#470]
I downloaded the most recent code and ran it on an example image (attached). It returned no results (no detection?). However, running the same image on the web demo correctly detected all the text.
I can run the code on other non-trivial images (scans) and it works successfully.
Is this just a version difference? If so, what commit is the web demo based on?
![test2](https://user-images.githubusercontent.com/2364417/123010000-00099c00-d37b-11eb-9dca-3ff0e830b80f.png)

**Comment by herobd** [comment]
It appeats that Scikit image was reading the image in as uint16 with a maximum value of 65279. I'm not sure why (something may be up with the image as I've generated it). But normalizing the image back to 255 seems to have fixed the issue.

**Comment by KirtoXX** [comment]
could u please offer more infos?

**Comment by KirtoXX** [comment]
i met the same problems
