### ISSUE TITLE
The file cannot be found by running after packaging with pyinstaller

### ISSUE THREAD

**Issue by yqchilde** [JaidedAI/EasyOCR#473]
I don't know if there are any friends like me. After packing with pyinstaller, I couldn't find the file. The specific error report is as follows:

```python
Traceback (most recent call last):
  File "main.py", line 363, in main
  File "captcha/easy_ocr.py", line 46, in easy_ocr
  File "easyocr/easyocr.py", line 199, in __init__
  File "easyocr/easyocr.py", line 256, in setLanguageList
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/v7/4z00fvss71n435b2g4xvymjr0000gn/T/_MEIUYXJ9t/easyocr/character/ch_sim_char.txt'
```

**Comment by neo125874** [comment]
@yqchilde hello, did you got this work?

**Comment by yqchilde** [comment]
> @yqchilde hello, did you get this work?

Not yet. I've given up for the time being.

**Comment by neo125874** [comment]
@yqchilde found the problem, just put the whole easyocr lib to dist folder; 
it just cause of the pyinstaller didn't move the import module & anything you need in the project.

**Comment by yqchilde** [comment]
@neo125874 Hello, I copied the easyocr folder to the dist directory (in venv), but there was still an error that the file could not be found.

**Comment by maxpaynestory** [comment]
> I don't know if there are any friends like me. After packing with pyinstaller, I couldn't find the file. The specific error report is as follows:
> 
> ```python
> Traceback (most recent call last):
>   File "main.py", line 363, in main
>   File "captcha/easy_ocr.py", line 46, in easy_ocr
>   File "easyocr/easyocr.py", line 199, in __init__
>   File "easyocr/easyocr.py", line 256, in setLanguageList
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/v7/4z00fvss71n435b2g4xvymjr0000gn/T/_MEIUYXJ9t/easyocr/character/ch_sim_char.txt'
> ```

Yes i am facing the same problem with pyinstaller created executable

**Comment by maxpaynestory** [comment]
**--collect-all easyocr** have solved my problem

```
pyinstaller -F desktop_app.py --collect-all easyocr
```

**Comment by AtharvaKher1596** [comment]
> **--collect-all easyocr** has solved my problem
> 
> ```
> pyinstaller -F desktop_app.py --collect-all easyocr
> ```

It worked for me thank you

**Comment by qarimbas** [comment]
--collect-all easyocr    
parameter worked for me!

**Comment by Sudaiii** [comment]
> --collect-all easyocr parameter worked for me!

Any ideas how to do this if using a .spec file?
