### ISSUE TITLE
__array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by Ismail-Maj** [JaidedAI/EasyOCR#476]
problem persists on each version of EasyOCR.  
this is related to pillow updating to 8.3.0 (very recently) see this issue https://github.com/python-pillow/Pillow/issues/5571

if someone wants a temporary fix just change this line in requirements.txt
```
Pillow
->
Pillow == 8.2.0
```

**Comment by fdonnangelo** [comment]
We are having the same issue!
Thank you for the temporary solution, it worked just fine.

**Comment by amar-verma** [comment]
I was facing the same issue. This helped. Thanks.

**Comment by rkcosmos** [comment]
thanks @Ismail-Maj , I updated the requirements.txt.

**Comment by Noly1990** [comment]
thanks @Ismail-Maj , it works
