### ISSUE TITLE
Model deployment on mobile phones

### ISSUE THREAD

**Issue by rasha-salim** [JaidedAI/EasyOCR#479]
Hello everyone,
I need to deploy easyOCR and use it on an Android device and I couldn't find any resources for that.
I have seen the custom_model.md but not sure if this would help since I don't want to train my custom model.
Thanks

**Comment by bit-scientist** [comment]
Hello, @rasha-salim and @huzaifah-here. Have you eventually deployed on mobile? Could you share your experience on that? Thanks a lot.
