### ISSUE TITLE
training of all models

### ISSUE THREAD

**Issue by jinfagang** [JaidedAI/EasyOCR#48]
Does there any training scripts of CRAFT model on any launguage dataset?

**Comment by rkcosmos** [comment]
for question about CRAFT, please ask in their [official repository](https://github.com/clovaai/CRAFT-pytorch)

**Comment by jinfagang** [comment]
@rkcosmos  Obviously why am asking is CRAFT doesn't provide training, how do u train the model custom? Will u opensource that part?

**Comment by rkcosmos** [comment]
I'm using their pretrain. It's good enough for general language.

**Comment by rkcosmos** [comment]
There is also this [project](https://github.com/backtime92/CRAFT-Reimplementation).
