### ISSUE TITLE
reader = easyocr.Reader(['en'], detection='DB', recognition = 'Transformer')

### ISSUE THREAD

**Issue by xzsong** [JaidedAI/EasyOCR#480]
hi,
i have just used EasyOCR, it's very helpful for my work. But i found, when the simple chinese characters are very close to each other, EasyOCR would not work very well. I know DB and Transformer are more powerful and when they can be used in EasyOCR?
thank you for your all hard work!

**Comment by rkcosmos** [comment]
I cannot promise a timeframe for that. We are working to improve EasyOCR in many aspects.
