### ISSUE TITLE
installing on jetson nano with cuda support

### ISSUE THREAD

**Issue by MaxEmilJan** [JaidedAI/EasyOCR#491]
Hello,
I am trying to install and use the easyocr package on my NVIDIA Jetson Nano. I want to do text recognition, while recording images with a camera simultaneously. Therefore the processing has to be as fast as possible, which is why I need GPU support and can't use e.g. tesseract.
I am using a fresh JetPack 4.5 image (Ubuntu 18.04 LTS) and updated && upgraded existing packages.
First I tried to install the package by the recommended command:
~~~
pip3 install easyocr
~~~
This is running successfully and i can import the module. However, as soon as I want to use
~~~
easyocr.Reader(['en'], gpu=True)
~~~
the following warning appears:
~~~
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
~~~
According to some research, this message shows up because of pytorch.
So I tried again but this time I installed the desired version of pytorch myself.
I followed this guide:
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048
So I did the following:
~~~
wget https://nvidia.box.com/shared/static/p57jwntv436lfrd78inwl7iml6p13fzh.whl -O torch-1.9.0-cp36-cp36m-linux_aarch64.whl
sudo apt-get install python3-pip libopenblas-base libopenmpi-dev 
pip3 install Cython
pip3 install torch-1.9.0-cp36-cp36m-linux_aarch64.whl
~~~
To validate that pytorch was successfully installed and CUDA is supported, I importet it in python3 and ran the following command:
~~~
>>> import torch
>>> print(torch.__version__)
1.8.0
>>> print("CUDA available: " + str(torch.cuda.is_available()))
CUDA available: True
>>> print("cuDNN version: " + str(torch.backends.cudnn.version()))
cuDNN version: 8000
~~~
Since CUDA seems to be available to torch after this installation, everything worked I guess.
So I continued by trying to install easyocr again. This time the installation didn't finished successfully. It says that the directory "torch/cuda" does not exist.
~~~
pip3 install easyocr
Collecting easyocr
  Downloading https://files.pythonhosted.org/packages/9d/b4/6a402a7ec3890e94313a7d2804190713e2c942371b39c7ccd9070280bc36/easyocr-1.3.2-py3-none-any.whl (63.2MB)
    100% |████████████████████████████████| 63.2MB 8.5kB/s 
Collecting scikit-image (from easyocr)
  Downloading https://files.pythonhosted.org/packages/54/fd/c1b0bb8f6f12ef9b4ee8d7674dac82cd482886f8b5cd165631efa533e237/scikit-image-0.17.2.tar.gz (29.8MB)
    100% |████████████████████████████████| 29.8MB 17kB/s 
Collecting scipy (from easyocr)
  Downloading https://files.pythonhosted.org/packages/aa/d5/dd06fe0e274e579e1dff21aa021219c039df40e39709fabe559faed072a5/scipy-1.5.4.tar.gz (25.2MB)
    100% |████████████████████████████████| 25.2MB 20kB/s 
Collecting torch (from easyocr)
  Downloading https://files.pythonhosted.org/packages/f8/02/880b468bd382dc79896eaecbeb8ce95e9c4b99a24902874a2cef0b562cea/torch-0.1.2.post2.tar.gz (128kB)
    100% |████████████████████████████████| 133kB 2.8MB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/torch.egg-info
    writing pip-egg-info/torch.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/torch.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/torch.egg-info/requires.txt
    writing top-level names to pip-egg-info/torch.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/torch.egg-info/SOURCES.txt'
    error: package directory 'torch/cuda' does not exist
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-lwbg5n17/torch/
~~~
This error seems to appear because the pip3 command downloaded torch-0.1.2.post2.tar.gz. According to this post, this specific version of torch does not support CUDA.
https://github.com/lukemelas/EfficientNet-PyTorch/issues/243

I think if it would be possible to install easyocr without trying to install torch 0.1.2 in the process, the package could run with cuda support, since I installed torch 1.9.0 successfully.

Is it possible to edit the setup.py file during a pip3 installation process? So I could skip the torch installation?
Or did someone had the same problem with installing easyocr on the Jetson Nano and can help me out?

Thanks in advance.
This is my first issue on GitHub. So if I missed anything important or you need more information please just ask.

**Comment by MaxEmilJan** [comment]
it was solved by updating pip with the following commands:
~~~
wget https://bootstrap.pypa.io/get-pip.py
sudo python3 get-pip.py
rm get-pip.py
~~~

After that I could install easyocr via pip and it seems to work with gpu support now.

**Comment by voltagedivision** [comment]
Hi did you ever successfully get this to work? Running OCR with EasyOCR but it is awfully slow and inaccurate.
