### ISSUE TITLE
illegal instruction (core dumped)  in Raspberry Pi 4b

### ISSUE THREAD

**Issue by Noly1990** [JaidedAI/EasyOCR#494]
system info : Linux ubuntu 5.4.0-1041-raspi #45-Ubuntu SMP PREEMPT Thu Jul 15 01:17:56 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
easyocr version 1.4
device Raspberry Pi 4b 4gb memory
only show message   illegal instruction (core dumped)

**Comment by neektwothousand** [comment]
i'm using an older version of pytorch (1.8) to fix the issue

gdb output with 1.9:
```
Thread 1 "python" received signal SIGILL, Illegal instruction.
0x0000007ff3c41fc8 in exec_blas () from ~/.local/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
```

**Comment by zhenglisai** [comment]
i used pytorch 1.8.1 to fix this issue
