### ISSUE TITLE
Detecting individual words

### ISSUE THREAD

**Issue by shahurvi84** [JaidedAI/EasyOCR#497]
Hi,
Thanks for the code. I followed all instructions and was able to execute code. However, I wanted to check if we can extract individual words instead of continuous words. e.g. from example that is provided, the text "Reduce your risk of coronavirus infection" was extracted, but can we get something like "Reduce", "your", "risk", "of", "coronavirus", "infection".

Thanks in advance

**Comment by amarv3142** [comment]
@shahurvi84 You can try adjusting parameter width_ths of readtext function which decides whether to merge two adjacent bounding boxes based on distance between them. width_ths=0 might get you the desired result in your case.
Incase, you are using paragraph=True, then you need to adjust x_ths. 

P.S. I haven't tried it myself. So not 100% sure of the above solution.

**Comment by kimlia545** [comment]
@shahurvi84 
check this site https://www.jaided.ai/easyocr/documentation/

width_ths (float, default = 0.5) - Maximum horizontal distance to merge boxes.
ex) result = reader.readtext(width_ths=0.1)
