### ISSUE TITLE
How to recognize numbers only?

### ISSUE THREAD

**Issue by sh2hh** [JaidedAI/EasyOCR#503]
My text contains just numbers.In order to improve accuracy of recognition,how to recognize numbers only?

**Comment by SamSamhuns** [comment]
Use the `allowlist` parameter, when calling the readtext method of the reader object

`reader.readtext('image.jpg', allowlist = '0123456789')`

**Comment by sh2hh** [comment]
thanks a lot！



---Original---
From: ***@***.***&gt;
Date: Sun, Aug 1, 2021 22:24 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JaidedAI/EasyOCR] How to recognize numbers only? (#503)




 
Use the allowlist parameter, when calling the readtext method of the reader object
 
reader.readtext('image.jpg', allowlist = '0123456789')

**Comment by PiotrCzapla** [comment]
@sh2hh  you could close the ticket if it works for you.
