### ISSUE TITLE
Overlapping boxes do not merge - Solution proposal

### ISSUE THREAD

**Issue by Odas-cieux** [JaidedAI/EasyOCR#504]
When two boxes following each other overlap, they are not merged by easyocr currently.

Example:
![overlapping boxes example](https://i.imgur.com/Ml8P0HZ.png) _currently_
![overlapping boxes example](https://i.imgur.com/jROSKfL.png) _the proposed fix_

Currently, to decide if two boxes following each other should be merged, the **absolute** difference between the max x coordinate of the first box and the min x coordinate of the second box must be below a threshold. Taking the **absolute** means that strongly overlapping boxes sometimes do not get merged.

An easy solution would be to remove the second `abs` from line 479 of easyocr/utils.py. 
Before:
`if (abs(np.mean(b_height) - box[5]) < height_ths*np.mean(b_height)) and (abs(box[0]-x_max) < width_ths *(box[3]-box[2])):`
After:
` if (abs(np.mean(b_height) - box[5]) < height_ths*np.mean(b_height)) and ((box[0]-x_max) < width_ths *(box[3]-box[2])): `
The only change is that the **absolute** value is no longer calculated in the second condition.

**Comment by amroghoneim** [comment]
I tried this and it didn't work for me. Overlapping boxes are still not merged. Am I missing something?

**Comment by rkcosmos** [comment]
looks good, do you want to make a PR for this?

**Comment by Odas-cieux** [comment]
Thank you for your interest in this issue.
If I have to yes, but I would rather let you handle this.
My solution is simple and I don't know its limits.

**Comment by strobelTha** [comment]
Hey,
I took the liberty to create a PR for this.
