### ISSUE TITLE
Problem about Convert the recognition torch model to Onnx

### ISSUE THREAD

**Issue by RyanCCC** [JaidedAI/EasyOCR#506]
Hello, when I convert the recognition model to onnx model, a problem occured like this:
![image](https://user-images.githubusercontent.com/27406337/128452784-f5bfdccb-9c0c-4f72-9fd0-7261126ae849.png)
Code:
```python
torch.onnx.export(model,
                        (torch.from_numpy(np.array(image)), torch.from_numpy(np.array(text_for_pred))),
                        './recogniction.onnx',
                        export_params=True,
                        opset_version=9,
                        do_constant_folding=True,
                        # input_names=['input','text']
                    )
```
How to solve this problem? Thanks

**Comment by Manishsinghrajput98** [comment]
@RyanCCC  could you please share the training steps ?
i want to train own recognition model using my dataset .
training start with this repository but iteration/epoch not increase

could you please help me

**Comment by RyanCCC** [comment]
> @RyanCCC could you please share the training steps ?
> i want to train own recognition model using my dataset .
> training start with this repository but iteration/epoch not increase
> 
> could you please help me

sorry, I only use this model to test my data. Thx.

**Comment by ziyeZzz** [comment]
@RyanCCC Have you transferred successfully?

**Comment by Manishsinghrajput98** [comment]
Yes
