### ISSUE TITLE
Heatmaps

### ISSUE THREAD

**Issue by alikaz3mi** [JaidedAI/EasyOCR#508]
Hello, Is it possible to get heatmaps from EasyOCR?
Thank you in advance.

**Comment by duranbe** [comment]
Since EasyOCR is based on CRAFT, i think so but it will need some modification in the codebase

**Comment by PiotrCzapla** [comment]
Out of curiosity why do you need heat maps if you have bounding boxes?

**Comment by duranbe** [comment]
I suppose it's to extract the bounding box for each character using the methode described in the CRAFT paper 

![image](https://user-images.githubusercontent.com/26261086/132123118-57c8ce23-fa96-40a2-9b64-600f22dab09b.png)

https://arxiv.org/pdf/1904.01941.pdf

But maybe EasyOCR already have this feature ?

**Comment by alikaz3mi** [comment]
@PiotrCzapla 
> Out of curiosity why do you need heat maps if you have bounding boxes?
I wanted to find out what causes the model's failure in some of my photos.

**Comment by PiotrCzapla** [comment]
thx, It make sense especially when text isn't in straight lines I can see heatmaps being used for example to replace a scanned text with different text preserving the original shape. (like this feature in google translate). Thank you for the paper I will readup.
