### ISSUE TITLE
Some digit's are split into multiple parts

### ISSUE THREAD

**Issue by loharmain** [JaidedAI/EasyOCR#510]
So far I'm having very good results with 90% of the pictures that are similar (from same game and same coords). However, sometimes I experience digits being read and split into multiple parts. For example:

![example](https://user-images.githubusercontent.com/87022227/128643281-74035766-f0bb-4d3a-a6c9-9eb448730d35.png)

Becomes: ['56,383,248', '781', '150', '1,482,146', '3,890', '32,']

For some reason 32,781 are seperated?

As said before in 90% very similar cases there are no issues.

I'm using `.readtext(crop, detail = 0)`

**Comment by Manishsinghrajput98** [comment]
@loharmain could you please share the training steps ?
 i want to train own recognition model using my dataset .
training start with this repository but iteration/epoch not increase 

could you please help me

**Comment by rkcosmos** [comment]
try different setting such as changing `width_ths`. See https://www.jaided.ai/easyocr/documentation/
