### ISSUE TITLE
thanks you so much for your valuable code .. but i have checked your code give this error 

### ISSUE THREAD

**Issue by Manishsinghrajput98** [JaidedAI/EasyOCR#516]
ValueError: Usecols do not match columns, columns expected but not found: ['words']

30 minutes before this code run well ..
but after some time this code give this type of error 

please check 
ValueError: Usecols do not match columns, columns expected but not found: ['words']

**Comment by Manishsinghrajput98** [comment]
sorry it works now. the problem is my csv files

**Comment by Manishsinghrajput98** [comment]
one more question
i have train my model on google colab free gpu machine. 

but it always run on cpu 

how can i use GPU machine 
"torch.cuda.amp.GradScaler is enabled, but CUDA is not available.  Disabling.

**Comment by fengjinhanzhenshuai** [comment]
when I train on my data,the trainer.ipynb give the same type of error
ValueError: Usecols do not match columns, columns expected but not found: ['filename']
Can you tell me how to fix it?Thanks in advance!

**Comment by Manishsinghrajput98** [comment]
try this one 

complete custom easy ocr recognition model training tutorial

https://www.youtube.com/watch?v=-j3TbyceShY
