### ISSUE TITLE
Training for Urdu fonts

### ISSUE THREAD

**Issue by sameearif88** [JaidedAI/EasyOCR#517]
Hello, I am training EasyOCR for Urdu font such as Jameel Noori Nastalique. I have dataset in which each image is a Urdu sentence. E.g a training image is:
![1](https://user-images.githubusercontent.com/68158136/129275188-558dedda-f802-49bd-be25-d4c29c9ded12.png)
And the ground truth for the image is:
بعد نجی ٹی وی سے گفتگو کرتے ہوئے وزیر خارجہ شاہ محمود قریشی نے بتایا کہ ملاقات
How should i proceed for this kind of training data, since in the example used each image had a single word. Plus should I mirror the images since Urdu is from right to left and the image will be processed left to right?

Thank you

**Comment by rkcosmos** [comment]
Please see data structure in https://github.com/JaidedAI/EasyOCR/releases/download/v1.4/en_sample.zip. And no you don't need to flip images.
