### ISSUE TITLE
How to train the recognition model？

### ISSUE THREAD

**Issue by yourstar9** [JaidedAI/EasyOCR#520]
I have a set of pictures, but the recognition accuracy of the existing model is not high. How can I train my own recognition model?

**Comment by NinaM31** [comment]
[This](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md) specifies the steps for training your own recognition model. and the trainer repo is [here](https://github.com/JaidedAI/EasyOCR/tree/master/trainer) after you change the `config.py` to match where you store your data, run the `trainer.ipynb`.

**Comment by ckcollab** [comment]
Apologies if this is a dumb question: I've successfully generated images with TRDG and put them in `all_data` and some in `all_data/en_val` along with a `labels.csv` matching the example given in the docs.

However, I get this error in iPython notebook:

```
/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/utils/data/dataset.py in __init__(self, datasets)
    236         super(ConcatDataset, self).__init__()
    237         # Cannot verify that datasets is Sized
--> 238         assert len(datasets) > 0, 'datasets should not be an empty iterable'  # type: ignore[arg-type]
    239         self.datasets = list(datasets)
    240         for d in self.datasets:
AssertionError: datasets should not be an empty iterable
```

For reference, here's how I'm generating data (maybe helpful to someone else) .. this generates 1,000 datapoints

```py
# I put this next to the notebook, in:
# trainer/generate_imgs_and_labels_csv.py

import csv
import glob
import os

from trdg.generators import GeneratorFromRandom


output_dirs = ["all_data/", "all_data/en_val"]

for output_dir in output_dirs:
    generator = GeneratorFromRandom(
        fonts=glob.glob("fonts/*"),
        count=1000,
    )

    with open(os.path.join(output_dir, "labels.csv"), 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        # write csv header
        writer.writerow(["filename", "words"])
        for i, (img, label) in enumerate(generator):
            img.save(f"{output_dir}/{i}.jpg")
            writer.writerow([f"{i}.jpg", label])

```

**Comment by NinaM31** [comment]
The images inside `all_data` put them inside `en_train_filtered`, and keep `all_data\val` as is. 
all_data needs 2 foldes val and train. 
``` 
all_data
     |---- val
     |---- en_train_filtered
```
In config.yaml, reference the train folder:
![image](https://user-images.githubusercontent.com/57009004/131238743-3e820d42-6b0c-4e50-963d-87de08028cf9.png)

**Comment by Manishsinghrajput98** [comment]
complete custom easy ocr recognition model training tutorial

https://www.youtube.com/watch?v=-j3TbyceShY

**Comment by ronaldaug** [comment]
> The images inside `all_data` put them inside `en_train_filtered`, and keep `all_data\val` as is.
> all_data needs 2 foldes val and train.

What is the difference between `val` and `en_train_filtered` ? Are they both should have the same content?
