### ISSUE TITLE
Can I optimize EasyOCR for images only contain alphanumeric characters?

### ISSUE THREAD

**Issue by p-i-** [JaidedAI/EasyOCR#523]
I'm dealing with images containing only alphanumeric ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890

Is it possible to optimize easyOCR for this?

Is there any information available regarding benchmarking/latency?

What recognition time might I expect for a 640x480 image?

Is there documented any science of minimizing recognition time?

PS Please do consider a Gitter chatroom; my apologies for clogging up the issue tracker with an enquiry.

**Comment by p-i-** [comment]
Would I need to supply training data to build the model?
I only have a couple of hundred images.

There's another restriction: I'm trying to pull out a single word from each image. And the total set of allowed words is ~100.
However things like font/color may vary.

If there is an engineer out there willing to consider taking on the task as a contract, please message me pipad.org@gmail.com

**Comment by rkcosmos** [comment]
I'll have my associate contact you.
