### ISSUE TITLE
Some numbers are missing when I use "en"

### ISSUE THREAD

**Issue by CapitaineNemo** [JaidedAI/EasyOCR#524]
You can see my input page and output page. Remarked as red, they are missing or not right.
Input page:
![image](https://user-images.githubusercontent.com/25415402/130989354-f65df262-b45c-48f6-9d51-06dba36e9e78.png)

Output page:
![image](https://user-images.githubusercontent.com/25415402/130989530-b98bb00f-7a54-42a3-a18e-dd95d6894006.png)

**Comment by rkcosmos** [comment]
try above solution in #533.
