### ISSUE TITLE
Question regarding training custom model

### ISSUE THREAD

**Issue by pankaja0285** [JaidedAI/EasyOCR#530]
To the concerned,
  * Just took a look at your training custom model section 
  * Reviewed the sample dataset and corresponding pth file. I see in your data set each jpg contained is one single word. I am not sure how to go about generating such a dataset in my case from P&ID engineering diagrams (printed not hand drawn/written). 
  * What do you suggest in my case? 
  * How to go about?
  * Currently
  --  some of the vertical text in the diagram is not getting detected - this just using whatever default detector and recognizer models that EasyOCR downloads on readtext.
  -- also there are overlapping detections, for e.g. I have a valve part that has the tag 14-HV-334-02, sometimes the detections are 14-, HV-334 (with -02 not all detected) or may be with overlap as 14-HV and HV-334-02 or some combination of...
  
  Please advise. I can post screen shots, if you need.

**Comment by Manishsinghrajput98** [comment]
complete custom easy ocr recognition model training tutorial  

https://www.youtube.com/watch?v=-j3TbyceShY

**Comment by rkcosmos** [comment]
Your problem is the detector part. We don't support retraining of the text detector yet. You can try adjusting detector's parameters (Parameter set 3 in `readtext` method, see https://jaided.ai/easyocr/documentation/)
