### ISSUE TITLE
TypeError: '>' not supported between instances of 'list' and 'int'

### ISSUE THREAD

**Issue by amroghoneim** [JaidedAI/EasyOCR#537]
My code is 

```
horziontal_list, free_list = reader.detect(np.array(img_main))
result = reader.recognize(img_cv_grey = np.array(img_main), horizontal_list=horziontal_list, free_list=free_list)    
```
where img_main is a PIL image

Traceback (most recent call last):
  File "~/ocr_testing.py", line 58, in <module>
    result = reader.recognize(img_cv_grey = np.array(img_main), horizontal_list=horziontal_list, free_list=free_list)
  File "~\Python\Python38\lib\site-packages\easyocr\easyocr.py", line 325, in recognize
    image_list, max_width = get_image_list(h_list, f_list, img_cv_grey, model_height = imgH)
  File "~\Python\Python38\lib\site-packages\easyocr\utils.py", line 559, in get_image_list
    x_min = max(0,box[0])
TypeError: '>' not supported between instances of 'list' and 'int'

**Comment by rkcosmos** [comment]
Can you print the dimension of `np.array(img_main)`? Is it in RGB or grayscale?

**Comment by amroghoneim** [comment]
(461, 820)
it's grayscale

**Comment by rkcosmos** [comment]
For a reason to be investigated, there is 1 redundant []. The quick fix is to do

`horziontal_list, free_list = reader.detect(np.array(img_main))`
`result = reader.recognize(img_cv_grey = np.array(img_main), horizontal_list=horziontal_list[0], free_list=free_list[0]) `

**Comment by amroghoneim** [comment]
Thanks!
