### ISSUE TITLE
About output confident level

### ISSUE THREAD

**Issue by pingchesu** [JaidedAI/EasyOCR#538]
Really thanks for this awesome project!!

I am now using easyocr to solve our problem.

However, I have question about confident level.

According to your project code, confident level will be generated by `custom_mean` function [custom_mean](https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/recognition.py#L148).

Is there any reference or literature about this formula ?

**Comment by rkcosmos** [comment]
no literature about this. It is an empirical calculation that makes most sense to general cases.
