### ISSUE TITLE
Pillow<8.3.0 in requirements.txt results in a conflict

### ISSUE THREAD

**Issue by louis-van-der-stam** [JaidedAI/EasyOCR#544]
Is there a reason for having this restriction? Would be good if the requirement mentions only a lower bound...

**Comment by purplesword** [comment]
Same question here. Especially there are security vulnerabilities on Pillow lower versions and the dependabot alerts about it and recommends to raise to >=8.3.2.

**Comment by rkcosmos** [comment]
Pillow 8.3.1 was buggy. I'll remove this restriction.

**Comment by louis-van-der-stam** [comment]
Thanks! Any idea on when the next release is made? Currently my project has easyocr is pinned to 1.4 and I would like to lift that restriction.

**Comment by Rijgersberg** [comment]
I would like to echo the request for a new release. We fixed the conflict by explicitly stating `easyocr!=1.4.1` in our requirements file.
