### ISSUE TITLE
minor bug when migrating from 1.4 to 1.4.1. 

### ISSUE THREAD

**Issue by beecadox** [JaidedAI/EasyOCR#547]
As stated in the 'What's new' section, in Version 1.4.1:
> Extend rotation_info argument to support all possible angle (thanksabde0103, see PR)

I run the detection and recognition on this specific [image](https://drive.google.com/file/d/1eSymuZlO1J4wib68RQ84_2exTZv2lii_/view?usp=sharing). As you can see in order to get all the text a 90 degree and a 270 degree rotation is needed. For both versions I run the line below: 

```
 result = reader.recognize(np.array(im.convert('L')), merged_list, free_list[0], rotation_info=[0, 90, 180, 270])
```

The results I am getting from one version to another are totally different.
Version 1.4:

```
([[145, 0], [882, 0], [882, 101], [145, 101]], 'EUROPEAN LAWYERS', 0.9799557536771372)
([[911, 107], [1014, 107], [1014, 906], [911, 906]], 'BARREAUX EUROPEENS', 0.646282488832031)
([[4, 124], [108, 124], [108, 876], [4, 876]], 'EUROPEAN BARS', 0.6906238763445064)
([[185, 401], [841, 401], [841, 583], [185, 583]], 'CCBE', 0.9803938127024359)
([[150, 893], [881, 893], [881, 1010], [150, 1010]], 'AVOCATS EUROPEENS', 0.7165664042811335)
```

Version 1.4.1:

```
[
 ([[145, 0], [882, 0], [882, 101], [145, 101]], 'EUROPEAN LAWYERS', 0.9799557536771372),
 ([[911, 107], [1014, 107], [1014, 906], [911, 906]], 'SNJJdo&n: XnVaudva', 0.09454260329171453),
 ([[4, 124], [108, 124], [108, 876], [4, 876]], 'EUROPEAN BARS', 0.9971172987203192),
 ([[185, 401], [841, 401], [841, 583], [185, 583]], '7833', 0.4892914593219757),
 ([[150, 893], [881, 893], [881, 1010], [150, 1010]], 'SNJAdoHn] SLVDOAV', 0.06483533410458987)]
```

When just using `rotation_info = [270]` I get all the text right but 'BARREAUX EUROPEENS'. When using `rotation_info = [90]` I get all the text right but 'EUROPEAN BARS'. Which means that when giving one element other than 0 in rotation_info it gives the right results for the horizontal text as well. But the thing is that I need both the 90 and 270 rotation and when the elements are 2+ in rotation_info I only get the results for the last element which was not an issue in version 1.4. 

For now I am just going to use Version 1.4, but needed to inform of that minor bug.

**Comment by rkcosmos** [comment]
thanks, we are investigating this issue.
