### ISSUE TITLE
Recognition result is not good when using allowlist

### ISSUE THREAD

**Issue by vneseresearcher** [JaidedAI/EasyOCR#548]
Hi all,

When using allowlist to recognize specific characters, I have a problem as follows: characters not in allowlist will be recognized as one of characters in allowlist.  How to ignore those characters?

**Comment by rkcosmos** [comment]
We don't have an option to do that. You can allow all characters and get rid unwanted characters after OCR.

**Comment by Sorokopudov** [comment]
Hi! Does the EasyOCR model currently operate in the same way regarding the allowlist feature? Specifically, when encountering a character not in the allowlist, will the model always choose the most similar character from the allowlist, or are there instances where it will completely ignore a character if it's not included in the allowlist?
