### ISSUE TITLE
Is it possible to find the distance between two words for example how many spaces are between them? Decreasing the width_ths in detect method worked, but at some other places it is not working very well especially when there is a number and word together. E.g. test 80 is detected as one work, however test test are detected as two words. 

### ISSUE THREAD

**Issue by warraich-a** [JaidedAI/EasyOCR#559]

**Comment by warraich-a** [comment]
Is it possible to find the distance between two words for example how many spaces are between them? Decreasing the width_ths in detect method worked, but at some other places it is not working very well especially when there is a number and word together. E.g. test 80 is detected as one work, however test test are detected as two words.

**Comment by rkcosmos** [comment]
We don't have a built-in function for your purpose. You can do post-processing by detecting space and separate words after OCR.
