### ISSUE TITLE
Persian Language (Farsi)

### ISSUE THREAD

**Issue by frisbeegrammer** [JaidedAI/EasyOCR#56]
Hi , i read you'r description about adding new language here #25 
I would like to add Farsi Language (Fa) with adding ~20000 words.
is this okay to start and train model or should i add more words and then create a PR ?

**Comment by rkcosmos** [comment]
Take your time, I'm not in rush.

**Comment by rkcosmos** [comment]
Farsi is now supported in v1.1.6. To use last version, you need to uninstall first
`pip uninstall easyocr`

and install directly from source code
`pip install git+git://github.com/jaidedai/easyocr.git`

please try and feedback.
