### ISSUE TITLE
Newbie Question : how to produce Output as TXT file

### ISSUE THREAD

**Issue by kucingkembar** [JaidedAI/EasyOCR#569]
hi, sorry for the very newbie question, and my broken English,
I am not a python programmer, so installing to this "working state" is quite miraculous for me,
for the info, I use windows 10 and use "easyocr.exe" using cmd and this is the result:
```
([[384, 46], [862, 46], [862, 124], [384, 124]], '元旱安,好久不旯', 0.5539275336640896)
```
(later i learn about "--detail 0")
my question is "how to sent the result to TXT file"? 
i tried 
`
easyocr.exe  -l ch_sim -f Source.jpeg > result.txt
`
but the result is error

thanks for the great job, and thank for reading, have a nice day

**Comment by kucingkembar** [comment]
never mind, I found the way

**Comment by ghjkq** [comment]
> неважно, я нашел способ

не оставляй топик так открыто бро, мне тоже нужен ответ на этот вопрос
