### ISSUE TITLE
Detected short number

### ISSUE THREAD

**Issue by sas9mba** [JaidedAI/EasyOCR#570]
Hello. I have image:
![cell](https://user-images.githubusercontent.com/20105785/137730636-f16acbe0-31a4-4fe5-9231-761038b326b7.png)
but easyOCR do not work.
I try use `detect` with diferrent parameters, but method return empty.
then i tried to make my simple-detector:
```
     def recognition_number(self, img: np.ndarray) -> str:
        image = self._filtration(img)
        thresh = cv2.adaptiveThreshold(image, 255, cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY_INV, 3, 1)
        cnts, _ = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
        ox = [i[0][0] for i in cnts[0]]
        oy = [i[0][1] for i in cnts[0]]
        data = self.reader.recognize(image, horizontal_list=[[min(ox), max(ox), min(oy), max(oy)]], free_list=[], allowlist="1234567890.,")
        return "".join([el[1] for el in data])
```
this solved the problem and now the number is recognized.
is it possible to do something with a easyOCR `detect`?

**Comment by rkcosmos** [comment]
If you already have cropped image, use

`result = reader.readtext(image)`

Text detector doesn't work well when image is already cropped or having short string of characters.
