### ISSUE TITLE
can't recognize this  very simple and clear picture with a number

### ISSUE THREAD

**Issue by Zeen-x** [JaidedAI/EasyOCR#571]
![cropped_4](https://user-images.githubusercontent.com/49156890/137738940-c60491f3-efa8-4c8c-83cc-af5e829791f8.png)

python3.8 with easyocr==1.4.1 model `english_g2`

```python
import easyocr

reader = easyocr.Reader(['en'], gpu=False)
result = reader.readtext("./image/cropped_4.png")
print(result)
```

this stdout
```
Using CPU. Note: This module is much faster with a GPU.
[]
```
All the other numbers can be correctly identified

**Comment by rkcosmos** [comment]
try
`result = reader.recognize("./image/cropped_4.png")`

**Comment by aamster** [comment]
what is different about `recognize` and `readtext`? Why does it fail with `readtext` but returns correctly with `recognize` ?
