### ISSUE TITLE
always download model itself.

### ISSUE THREAD

**Issue by q1208c** [JaidedAI/EasyOCR#574]
I am new to EasyOCR.
As the example in Readme.MD, using pip install easyocr, and runing the example.
I download the model from model hub, and put into ~/.EasyOCR/model,
```
$ ls -1 ~/.EasyOCR/model/
english_g2.zip
temp.zip
zh_sim_g2.zip
```
but, each time I run the code, it always show the downloading. 
My network is not good, so, the download always interrupted.

```
$ python3 test1.py
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Downloading detection model, please wait. This may take several minutes depending upon your network connection.
Progress: |████----------------------------------------------| 10.0% Complet
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    reader = easyocr.Reader(['ch_sim','en']) # this needs to run only once to load the model into memory
  File "/usr/local/lib/python3.6/site-packages/easyocr/easyocr.py", line 90, in __init__
    download_and_unzip(detection_models[detector_model]['url'], detection_models[detector_model]['filename'], self.model_storage_directory, verbose)
  File "/usr/local/lib/python3.6/site-packages/easyocr/utils.py", line 586, in download_and_unzip
    urlretrieve(url, zip_path, reporthook=reporthook)
  File "/usr/lib64/python3.6/urllib/request.py", line 289, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 9188135 out of 77251756 bytes>
```
Is there any wrong ? 
Do I need unzip the file ?

**Comment by pronoym99** [comment]
Unzip both the text detection models and the language models and keep them within the same directory. Mention the path of this directory while creating a ```easyocr.Reader``` by specifying the ```model_storage_directory``` parameter. Finally, set ```download_enabled``` to ```False```. The last step is the most important because Easyocr will always prefer to download models from its online repository instead of searching the local file system.

**Comment by q1208c** [comment]
> Unzip both the text detection models and the language models and keep them within the same directory. Mention the path of this directory while creating a `easyocr.Reader` object by specifying the `model_storage_directory` parameter. Finally, set `download_enabled` to `False`. The last step is the most important because Easyocr will always prefer to download models from its online repository instead of searching the local file system.

Thank for your help. It's working now.

**Comment by SidharthRamachandran** [comment]
> Unzip both the text detection models and the language models and keep them within the same directory. Mention the path of this directory while creating a `easyocr.Reader` object by specifying the `model_storage_directory` parameter. Finally, set `download_enabled` to `False`. The last step is the most important because Easyocr will always prefer to download models from its online repository instead of searching the local file system.

Hi, I have downloaded the language detection model and the text detection model from modelhub. The unzipped models were copied to a folder (within the flask application) and the relative path to the folder containing these two models were specified as you mentioned. However , it shows  " FileNotFoundError: Missing path/craft_mlt25k.pth and downloads disabled". Is there a fix?

**Comment by pronoym99** [comment]
Since you specifically mentioned a Flask application, I can't be much sure about the resolution. Instead of the relative file path, try using the **absolute file path** if possible. As always set the `download_enabled` parameter to `False`. See if it works or not.

**Comment by TheEliteAnalyst** [comment]
@SidharthRamachandran Not sure if you solved the issue, to download "craft_mlt25k.pth", it is available in the following link. Hope that helps.
https://gitcode.net/mirrors/JaidedAI/EasyOCR/-/blob/v1.1.7/easyocr/easyocr.py
![image](https://user-images.githubusercontent.com/7199786/153492599-3c93ae76-b8db-42ac-91f6-091cc8b54730.png)
