### ISSUE TITLE
Failed to detect and determine text with confidence.

### ISSUE THREAD

**Issue by AvekIA** [JaidedAI/EasyOCR#579]
![useful_img_1](https://user-images.githubusercontent.com/72162626/139280406-d60d721d-fba7-40cb-841b-a7458e967e56.jpg)
I have a well uniform writting on a led screen.
2 problematics:
- evolving light
- black and green background changing row by row

With an adaptive treshold and by analyzing the row one by one, we should be able to get good images with easy text to detect. 
We get some good results:

![archivage_results](https://user-images.githubusercontent.com/72162626/139282640-e9874604-bc90-48ee-98b9-bbc6f6bc5ac2.jpg)

![poste_results](https://user-images.githubusercontent.com/72162626/139282681-e7a899e5-9ef0-4ec3-a7c9-3f4555fdd806.jpg)

And some bad results:

![zdmc_results](https://user-images.githubusercontent.com/72162626/139281876-1cc54ad3-6c24-48e6-b529-e2ad28c12fe5.jpg)

![results_act_dec](https://user-images.githubusercontent.com/72162626/139281909-08b09aa6-5c69-4bcd-9be4-678b381ea37d.jpg)

I feel like the neural network could use some new characters and noise, is there an easy way to add images on a pre-trained maybe ? Or maybe there are some tricks that I didn't saw on how to improve the detection ?

[stackoverflow link](https://stackoverflow.com/questions/69705008/difficulty-to-use-cv2-adaptivethreshold-with-the-reflection-problematic)

**Comment by NinaM31** [comment]
AvekIA have you tried training a custom model?  [these are the steps](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md).
You can specify the characters you care about [inside the config file](https://github.com/JaidedAI/EasyOCR/tree/master/trainer) when training the model, which hopefully will solve your character issues, you'll also need a dataset that closely resembles the task you are trying to solve, the steps of training a custom model provides a suggestion on how to generating your own synthetic dataset, if you already have a dataset you can use it instead.

**Comment by AvekIA** [comment]
I did a custom model, it's better for some text but not useful for some others, still in progress but it progress ! :)
Thank you for the advices.
