### ISSUE TITLE
Model file not found

### ISSUE THREAD

**Issue by lodenrogue** [JaidedAI/EasyOCR#58]
Trying to run the example and I get this error:

```
>>> import easyocr
>>> reader = easyocr.Reader(['en'])
CUDA not available - defaulting to CPU. Note: This module is much faster with a GPU.
Downloading detection model, please wait
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/myuser/.local/lib/python3.8/site-packages/easyocr/easyocr.py", line 168, in __init__
    urllib.request.urlretrieve(model_url['detector'][0] , DETECTOR_PATH)
  File "/usr/lib/python3.8/urllib/request.py", line 257, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: '/home/myuser/.EasyOCR/model/craft_mlt_25k.pth'
```

**Comment by rkcosmos** [comment]
Not sure what happened. You can also download files manually. See links on README.

**Comment by snoop2head** [comment]
@rkcosmos 
Actually, this happened to me also. 

It is resolved pretty easily, by manually downloading file from google drive, placing on the directory that appeared on the console.

But will it be more convenient for allowing users to place models on project directory, instead of the root directory?

**Comment by rkcosmos** [comment]
I was in project directory before I accept this PR #45 . It is the standard practice to store additional file in home directory because if program is installed system-wide. User without root-privilege can still download and save new model.

**Comment by jibaku** [comment]
I created the directory and the line worked:
```mkdir -p /home/myuser/.EasyOCR/model```

**Comment by rkcosmos** [comment]
Thank you. I added a line to create that directory if not exist.

**Comment by zhyf1019** [comment]
> @rkcosmos
> Actually, this happened to me also.
> 
> It is resolved pretty easily, by manually downloading file from google drive, placing on the directory that appeared on the console.
> 
> But will it be more convenient for allowing users to place models on project directory, instead of the root directory?

Dear,snoop2head:
Would you please tell me the downloading link?
