### ISSUE TITLE
ValueError: Usecols do not match columns, columns expected but not found: ['words']

### ISSUE THREAD

**Issue by aswa123** [JaidedAI/EasyOCR#580]
This error occur in dataset.py file
line 149
self.df = pd.read_csv(os.path.join(root,'labels.csv'), sep='^([^,]+),', engine='python', usecols=['filename', 'words'], keep_default_na=False)

anyone know why?
Thanks.

**Comment by NinaM31** [comment]
Hello aswa123
does your labels.csv follows this [model hub](https://jaided.ai/easyocr/modelhub/) example? 
The below image is a snippet of how it should look like. Notice the header.
![image](https://user-images.githubusercontent.com/57009004/139573496-29567da0-f5ae-473b-8f89-d34a73297b9c.png)
if not you have two options:
1- added it manually in the csv.
2- or add this `names=['filename', 'words']` instead of `usecols=['filename', 'words']`.
Hopefully this will solve your problem.

**Comment by aswa123** [comment]
Thank you for your reply but after I change that I got the new error.

(EasyOCR-master) swap@pop-os:~/Downloads/EasyOCR-master/trainer$ python trainer.py 
Filtering the images containing characters which are not in opt.character
Filtering the images whose label is longer than opt.batch_max_length
--------------------------------------------------------------------------------
dataset_root: all_data
opt.select_data: ['en_train_filtered']
opt.batch_ratio: ['1']
--------------------------------------------------------------------------------
dataset_root:    all_data        dataset: en_train_filtered
all_data/en_train_filtered
Traceback (most recent call last):
  File "pandas/_libs/index.pyx", line 121, in pandas._libs.index.IndexEngine._get_loc_duplicates
TypeError: '<' not supported between instances of 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 103, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 125, in pandas._libs.index.IndexEngine._get_loc_duplicates
KeyError: 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "trainer.py", line 32, in <module>
    train(opt, amp=False)
  File "/home/swap/Downloads/EasyOCR-master/trainer/train.py", line 41, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "/home/swap/Downloads/EasyOCR-master/trainer/dataset.py", line 56, in __init__
    _dataset, _dataset_log = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "/home/swap/Downloads/EasyOCR-master/trainer/dataset.py", line 132, in hierarchical_dataset
    dataset = OCRDataset(dirpath, opt)
  File "/home/swap/Downloads/EasyOCR-master/trainer/dataset.py", line 159, in __init__
    label = self.df.at[index,'words']
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexing.py", line 2273, in __getitem__
    return self.obj.loc[key]
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexing.py", line 925, in __getitem__
    return self._getitem_tuple(key)
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexing.py", line 1100, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexing.py", line 838, in _getitem_lowerdim
    section = self._getitem_axis(key, axis=i)
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexing.py", line 1164, in _getitem_axis
    return self._get_label(key, axis=axis)
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _get_label
    return self.obj.xs(label, axis=axis)
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/generic.py", line 3776, in xs
    loc = index.get_loc(key)
  File "/home/swap/miniconda3/envs/EasyOCR-master/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 0

**Comment by aswa123** [comment]
I did second change.

**Comment by NinaM31** [comment]
Since I can't really see how your CSV file looks like but reading your Error and going through the code it might be that you have delimiters at the end of each line, add `index_col=False` to force pandas to not use the first column as the index.

```
self.df = pd.read_csv(os.path.join(root,'labels.csv'), sep='^([^,]+),', engine='python', names=['filename', 'words'],  index_col=False, keep_default_na=False)
```

**Comment by aswa123** [comment]
@NinaM31  Thank you for your help
I got it! I made it!

It works!
sorry to bother you but how do I test the model to see the validation score and visualization?

**Comment by NinaM31** [comment]
your welcome awa123 (ﾉ◕ヮ◕)ﾉ*:･ﾟ✧
- The visualization is something you need to implement yourself. 
- The validation score is being printed as the model is training, and also when the model is done training, the result will be saved inside `saved_models\experiment_name\`.

In the snippet below the model trains for `300000` epochs and every `20000` epochs  it will print the validation score results.
![image](https://user-images.githubusercontent.com/57009004/139820676-8247b86d-6218-4437-a4a0-edd85b38e820.png)
If you reduce the training epochs make sure to also reduce the valInterval, to be able to see the results.

**Comment by makarov-infocraft** [comment]
I probably found the cause of the error. If you used a dataset from here: https://jaided.ai/easyocr/modelhub /  
It is necessary to remove ";" in  labels.csv

**Comment by MayurGowda01** [comment]
> I probably found the cause of the error. If you used a dataset from here: https://jaided.ai/easyocr/modelhub / It is necessary to remove ";" in labels.csv

what does this mean
I'm getting the above mentioned error and tried all the above mentioned ways but still getting the error.

**Comment by krishnatejakt11** [comment]
> Since I can't really see how your CSV file looks like but reading your Error and going through the code it might be that you have delimiters at the end of each line, add `index_col=False` to force pandas to not use the first column as the index.
> 
> ```
> self.df = pd.read_csv(os.path.join(root,'labels.csv'), sep='^([^,]+),', engine='python', names=['filename', 'words'],  index_col=False, keep_default_na=False)
> ```

this is not working for me could you please help

**Comment by vravikumar1** [comment]
> Hello aswa123 does your labels.csv follows this [model hub](https://jaided.ai/easyocr/modelhub/) example? The below image is a snippet of how it should look like. Notice the header. ![image](https://user-images.githubusercontent.com/57009004/139573496-29567da0-f5ae-473b-8f89-d34a73297b9c.png) if not you have two options: 1- added it manually in the csv. 2- or add this `names=['filename', 'words']` instead of `usecols=['filename', 'words']`. Hopefully this will solve your problem.

Using names instead of usecols solved it for me!! Thank you!

**Comment by Hermann12** [comment]
This is still a bug! If I read the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html) it said clearly _For example, a valid list-like usecols parameter would be [0, 1, 2] or ['foo', 'bar', 'baz']._
If I use it as described I get **ValueError:** _Usecols do not match columns, columns expected but not found: ['Col3', 'Col1']_.

**Comment by KAKkkdkkakkda** [comment]
> Since I can't really see how your CSV file looks like but reading your Error and going through the code it might be that you have delimiters at the end of each line, add `index_col=False` to force pandas to not use the first column as the index.
> 
> ```
> self.df = pd.read_csv(os.path.join(root,'labels.csv'), sep='^([^,]+),', engine='python', names=['filename', 'words'],  index_col=False, keep_default_na=False)
> ```

Hi! Unfortunately, nothing resolved this error for me, could you please help with identifying its cause? I have a csv dataset which has headers like in the picture
![фыфы](https://github.com/JaidedAI/EasyOCR/assets/175065473/19c1b07b-afb9-4b64-8d97-daae3657f3fa)

inside visual studio it has headers like this: filename;words  

I tried replacing separator inside dataset.OCRDataset function to ';' and I also tried replacing ';' inside csv with '^([^,]+),'. but nothing works. I also ensured that there are no indents inside csv headers, so I am really confused whats going on
