### ISSUE TITLE
PyInstaller attempted relative import with no known parent package

### ISSUE THREAD

**Issue by sky-chy** [JaidedAI/EasyOCR#585]
Running the python script directly in pycharm is normal, but when I use pyinstaller to package this program and run the exe file, the console prompts the following. How can I solve this problem?

easyocr  __version__ = '1.4.1'

`
Traceback (most recent call last):
  File "main.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "easyocr.py", line 3, in <module>
ImportError: attempted relative import with no known parent package
`
![1](https://user-images.githubusercontent.com/41139710/140619496-65e705a0-b66b-42da-8dba-aa6232f93d8c.png)

**Comment by sky-chy** [comment]
easyocr 
__version__ = '1.4.1'

**Comment by etu7912a48** [comment]
Struggling with the same problem.
