### ISSUE TITLE
Not predicting new images

### ISSUE THREAD

**Issue by saribolagh** [JaidedAI/EasyOCR#594]
I trained the EasyOCR from scratch on my own data. When doing ocr on the test data I realized very strange behavior. For example for the following image it predicts  "INSTANTANEOUS TRIPPING UNIT", but the image contains only RST . I checked and the training data there is INSTANTANEOUS TRIPPING UNIT but not  RST .  If I look at the training data, it seems that an image that contains RST, similar to the attached image, has been wrongly labelled as " INSTANTANEOUS TRIPPING UNIT". So it seems that what happens is that the model just maps the given image to the most similar image in the training set and uses it's linked text as the output of OCR ( like classification), which has nothing to do with OCRing.
 This is my training config:

- Transformation: 'None'
- FeatureExtraction: 'ResNet' 
- SequenceModeling: 'BiLSTM'
- Prediction: 'Attn' 
- num_fiducial: 20
- input_channel: 1
- output_channel: 128
- hidden_size: 128 
- decode: 'greedy'
- new_prediction: False
- freeze_FeatureFxtraction: False
- freeze_SequenceModeling: False

What I am doing wrong here?

![RST](https://user-images.githubusercontent.com/2463175/141448468-f175acac-4a2d-4d81-9c0e-ec46d26ac23c.JPG)
,

**Comment by rkcosmos** [comment]
I suspect 2 potential problems. 1. you probably overfit your data. 2. you use attention layer while the default is ctc. I don't remember exactly if you have to modify/reconfig some part of code to get that work.
