### ISSUE TITLE
combine Arabic with English in same image

### ISSUE THREAD

**Issue by abdoelsayed2016** [JaidedAI/EasyOCR#595]
@rkcosmos 
I face some problems with I combine Arabic with English
like this image 
![image](https://user-images.githubusercontent.com/27821589/142275289-f3111045-624d-4d5a-ab6c-e76964430d28.png)

```

import easyocr
from PIL import Image

img = Image.open('data/full_eval/3_0.tif')

reader = easyocr.Reader(['en','ar']) # this needs to run only once to load the model into memory
result = reader.readtext(img, detail = 0)

print(result)
```

the result is : ['؟٦ ٨٧٨٥٥٣ ٥٣٨٥٣ ٧٥٧٣'] 
when I remove ar from Reader function 
the output is  right 
I need tar and English because some lines have two languages.

do u have any solution for that 
thanks

**Comment by rkcosmos** [comment]
Your image has small margin, can you try using `recognize` function instead of `readtext`?

**Comment by abdoelsayed2016** [comment]
this is the output : [[[[0, 0], [632, 0], [632, 69], [0, 69]], 'Vnur nrner nunher is', 0.45912601567407024]]

**Comment by rkcosmos** [comment]
Can you try add some margin to your image before sending to EasyOCR? It is either margin issue or English in Arabic model is not trained well.
