### ISSUE TITLE
Import easyocr :  No module named 'easyocr'

### ISSUE THREAD

**Issue by Sanjaygowda66** [JaidedAI/EasyOCR#596]
I installed pytorch using this code 
`!pip install torch==1.8.1+cpu torchvision==0.9.1+cpu torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html`
then i installed easyocr using `!pip install easyocr` command
not able to import the easyocr module even after re-starting the kernal `import easyocr`
Python 3.8.10

**Comment by Laveen-exe** [comment]
!pip3 install torch torchvision torchaudio
!pip install easyocr
!pip install opencv-python-headless==4.1.2.30

**Comment by SachinYadav2** [comment]
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='download.pytorch.org', port=443): Read timed out.

**Comment by SachinYadav2** [comment]
How to fix a error

**Comment by SachinYadav2** [comment]
file size in !pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio===0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
