### ISSUE TITLE
Downloading detection model too slow

### ISSUE THREAD

**Issue by LiHangBing** [JaidedAI/EasyOCR#601]
Hi, I when I run a code in Windows, it display "Downloading detection model, please wait. This may take several minutes depending upon your network connection." 
Then it keep downloading for a long time.
even though I plug a VPN , its progress is very slow
I just use "pip install easyocr" to install
And the code is here:

# 
import easyocr
# 
reader = easyocr.Reader(['en']) 
# 
result = reader.readtext('1.jpg')
# 
result

**Comment by krisiney** [comment]
Hi, I have met the same problem. If you are in China, just manually download the model and put it into the cache folder. I use Mac, the path is /Users/krisiney/.EasyOCR/model/english_g2.pth. Not quite sure about the cache path on Win.

Hope that helps.

**Comment by Azleal** [comment]
> Hi, I have met the same problem. If you are in China, just manually download the model and put it into the cache folder. I use Mac, the path is /Users/krisiney/.EasyOCR/model/english_g2.pth. Not quite sure about the cache path on Win.
> 
> Hope that helps.

also remember to download Text Detection Models(CRAFT) to model path
