### ISSUE TITLE
Combining paragraph=TRUE and keeping confidence score

### ISSUE THREAD

**Issue by TomBenson27** [JaidedAI/EasyOCR#603]
Hi, 

Thanks for building this library! 

I had a couple of questions. 

I am trying to use easyOCR and extract language from GSV images, but I am having issues with quality and performance (if anyone had any suggestions for GSV extraction, would be great). But when I use paragraph=TRUE, it gives me a better representation of the text box I'm extracting, but I lose the confidence score -- any chance to keep it? 

Also, I am still a little convinced but adding multiple languages into one model. If i want to extract all the Arabic, Swedish, and English, for instance, how do i know which text box is English or Arabic? Or is it better to run the models individually and use the confidence score to understand if its closer to Arabic to English etc?

Thank you,
Tom

**Comment by gogohanyi** [comment]
Hello, have you solved these? I also have the same problems as I want to extract text in english, korean, and traditional chinese at the same time. Should I compare the confidence scores?
Besides, want to get confident score even when using paragraph option as well.

**Comment by joel1895** [comment]
Hey, how can we keep confidence scores while keeping the Paragraph=True?

**Comment by usama-axcelerate** [comment]
Any update?

**Comment by rokopi-byte** [comment]
+1
