### ISSUE TITLE
Kernel Died When Using EasyOCR

### ISSUE THREAD

**Issue by selenvrl** [JaidedAI/EasyOCR#606]
I followed all necessary instructions. I installed PyTorch for Windows. I am using Python version 3.9.7. However, I tried all versions of easyocr, but every time I import it, the kernel died. When I uninstall this library, the kernel is working again.

I don't get any error in easyocr installation. Can anyone help who knows the source of this problem?

N: Re-running Python is not a solution that works.
    Uninstalling and reinstalling the library is not the solution.
    kernel  is not died in any other library.

**Comment by chen-qj** [comment]
Have you tried the solutioin in #630

**Comment by AbdirayimovS** [comment]
I am also having such issues. Last week when i used easyocr it was okey. I  re-installed opencv-python specific version(4.5.4.60). I also installed the latest opencv-python version too. What may be an issue with?
