### ISSUE TITLE
Citation of EasyOCR

### ISSUE THREAD

**Issue by DuongTran1708** [JaidedAI/EasyOCR#609]
Dear authors, 

In case of we want to cite your work in our paper:
- How can we cite?
- What is bibliography we have to use?

Hope to see your respond soon.

Regards,

**Comment by joaossmacedo** [comment]
Does anyone know how EasyOCR should be cited?

**Comment by ecnuljzhang** [comment]
I have the same question.

**Comment by Davo00** [comment]
@rkcosmos why did you close this issue without any answers?

**Comment by mariameraz** [comment]
Hi, I'm using EasyOCR in my project too and I'd like to cite your work properly. My plan for now is to include a citation linked to this repo, but I'm wondering if is there a preferred citation you'd recommend instead of or in addition to citing the repo? Thanks in advance!
