### ISSUE TITLE
Get coordinates of every word detected.

### ISSUE THREAD

**Issue by Akhilesh64** [JaidedAI/EasyOCR#610]
Hi, is it possible to get coordinates of every word detected. The default reader.readtext provides bounding box coordinates of a group of words. Can the single words coordinates be extracted somehow ?

**Comment by Drij77** [comment]
You can check layout parser pdf format

**Comment by Akhilesh64** [comment]
@Drij77 Thanks for the suggestion. Will look into it.

@rkcosmos Is this possible ?

**Comment by rkcosmos** [comment]
You can try setting argument `width_ths` and `height_ths` to zero. This way EasyOCR will not try to group words into a line.

**Comment by Akhilesh64** [comment]
@rkcosmos Thanks this helped settle the problem.
