### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Model:

### ISSUE THREAD

**Issue by Jitesh4389** [JaidedAI/EasyOCR#611]
Missing key(s) in state_dict: "FeatureExtraction.ConvNet.0.weight", "FeatureExtraction.ConvNet.0.bias", "FeatureExtraction.ConvNet.3.weight", "FeatureExtraction.ConvNet.3.bias", "FeatureExtraction.ConvNet.6.weight", "FeatureExtraction.ConvNet.6.bias", "FeatureExtraction.ConvNet.8.weight", "FeatureExtraction.ConvNet.8.bias", "FeatureExtraction.ConvNet.11.weight", "FeatureExtraction.ConvNet.12.weight", "FeatureExtraction.ConvNet.12.bias", "FeatureExtraction.ConvNet.12.running_mean", "FeatureExtraction.ConvNet.12.running_var", "FeatureExtraction.ConvNet.14.weight", "FeatureExtraction.ConvNet.15.weight", "FeatureExtraction.ConvNet.15.bias", "FeatureExtraction.ConvNet.15.running_mean", "FeatureExtraction.ConvNet.15.running_var", "FeatureExtraction.ConvNet.18.weight", "FeatureExtraction.ConvNet.18.bias". 
	Unexpected key(s) in state_dict: "FeatureExtraction.ConvNet.conv0_1.weight", "FeatureExtraction.ConvNet.bn0_1.weight", "FeatureExtraction.ConvNet.bn0_1.bias", "FeatureExtraction.ConvNet.bn0_1.running_mean", "FeatureExtraction.ConvNet.bn0_1.running_var", "FeatureExtraction.ConvNet.bn0_1.num_batches_tracked", "FeatureExtraction.ConvNet.conv0_2.weight", "FeatureExtraction.ConvNet.bn0_2.weight", "FeatureExtraction.ConvNet.bn0_2.bias", "FeatureExtraction.ConvNet.bn0_2.running_mean", "FeatureExtraction.ConvNet.bn0_2.running_var", "FeatureExtraction.ConvNet.bn0_2.num_batches_tracked", "FeatureExtraction.ConvNet.layer1.0.conv1.weight", "FeatureExtraction.ConvNet.layer1.0.bn1.weight", "FeatureExtraction.ConvNet.layer1.0.bn1.bias", "FeatureExtraction.ConvNet.layer1.0.bn1.running_mean", "FeatureExtraction.ConvNet.layer1.0.bn1.running_var", "FeatureExtraction.ConvNet.layer1.0.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer1.0.conv2.weight", "FeatureExtraction.ConvNet.layer1.0.bn2.weight", "FeatureExtraction.ConvNet.layer1.0.bn2.bias", "FeatureExtraction.ConvNet.layer1.0.bn2.running_mean", "FeatureExtraction.ConvNet.layer1.0.bn2.running_var", "FeatureExtraction.ConvNet.layer1.0.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer1.0.downsample.0.weight", "FeatureExtraction.ConvNet.layer1.0.downsample.1.weight", "FeatureExtraction.ConvNet.layer1.0.downsample.1.bias", "FeatureExtraction.ConvNet.layer1.0.downsample.1.running_mean", "FeatureExtraction.ConvNet.layer1.0.downsample.1.running_var", "FeatureExtraction.ConvNet.layer1.0.downsample.1.num_batches_tracked", "FeatureExtraction.ConvNet.conv1.weight", "FeatureExtraction.ConvNet.bn1.weight", "FeatureExtraction.ConvNet.bn1.bias", "FeatureExtraction.ConvNet.bn1.running_mean", "FeatureExtraction.ConvNet.bn1.running_var", "FeatureExtraction.ConvNet.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer2.0.conv1.weight", "FeatureExtraction.ConvNet.layer2.0.bn1.weight", "FeatureExtraction.ConvNet.layer2.0.bn1.bias", "FeatureExtraction.ConvNet.layer2.0.bn1.running_mean", "FeatureExtraction.ConvNet.layer2.0.bn1.running_var", "FeatureExtraction.ConvNet.layer2.0.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer2.0.conv2.weight", "FeatureExtraction.ConvNet.layer2.0.bn2.weight", "FeatureExtraction.ConvNet.layer2.0.bn2.bias", "FeatureExtraction.ConvNet.layer2.0.bn2.running_mean", "FeatureExtraction.ConvNet.layer2.0.bn2.running_var", "FeatureExtraction.ConvNet.layer2.0.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer2.0.downsample.0.weight", "FeatureExtraction.ConvNet.layer2.0.downsample.1.weight", "FeatureExtraction.ConvNet.layer2.0.downsample.1.bias", "FeatureExtraction.ConvNet.layer2.0.downsample.1.running_mean", "FeatureExtraction.ConvNet.layer2.0.downsample.1.running_var", "FeatureExtraction.ConvNet.layer2.0.downsample.1.num_batches_tracked", "FeatureExtraction.ConvNet.layer2.1.conv1.weight", "FeatureExtraction.ConvNet.layer2.1.bn1.weight", "FeatureExtraction.ConvNet.layer2.1.bn1.bias", "FeatureExtraction.ConvNet.layer2.1.bn1.running_mean", "FeatureExtraction.ConvNet.layer2.1.bn1.running_var", "FeatureExtraction.ConvNet.layer2.1.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer2.1.conv2.weight", "FeatureExtraction.ConvNet.layer2.1.bn2.weight", "FeatureExtraction.ConvNet.layer2.1.bn2.bias", "FeatureExtraction.ConvNet.layer2.1.bn2.running_mean", "FeatureExtraction.ConvNet.layer2.1.bn2.running_var", "FeatureExtraction.ConvNet.layer2.1.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.conv2.weight", "FeatureExtraction.ConvNet.bn2.weight", "FeatureExtraction.ConvNet.bn2.bias", "FeatureExtraction.ConvNet.bn2.running_mean", "FeatureExtraction.ConvNet.bn2.running_var", "FeatureExtraction.ConvNet.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.0.conv1.weight", "FeatureExtraction.ConvNet.layer3.0.bn1.weight", "FeatureExtraction.ConvNet.layer3.0.bn1.bias", "FeatureExtraction.ConvNet.layer3.0.bn1.running_mean", "FeatureExtraction.ConvNet.layer3.0.bn1.running_var", "FeatureExtraction.ConvNet.layer3.0.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.0.conv2.weight", "FeatureExtraction.ConvNet.layer3.0.bn2.weight", "FeatureExtraction.ConvNet.layer3.0.bn2.bias", "FeatureExtraction.ConvNet.layer3.0.bn2.running_mean", "FeatureExtraction.ConvNet.layer3.0.bn2.running_var", "FeatureExtraction.ConvNet.layer3.0.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.0.downsample.0.weight", "FeatureExtraction.ConvNet.layer3.0.downsample.1.weight", "FeatureExtraction.ConvNet.layer3.0.downsample.1.bias", "FeatureExtraction.ConvNet.layer3.0.downsample.1.running_mean", "FeatureExtraction.ConvNet.layer3.0.downsample.1.running_var", "FeatureExtraction.ConvNet.layer3.0.downsample.1.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.1.conv1.weight", "FeatureExtraction.ConvNet.layer3.1.bn1.weight", "FeatureExtraction.ConvNet.layer3.1.bn1.bias", "FeatureExtraction.ConvNet.layer3.1.bn1.running_mean", "FeatureExtraction.ConvNet.layer3.1.bn1.running_var", "FeatureExtraction.ConvNet.layer3.1.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.1.conv2.weight", "FeatureExtraction.ConvNet.layer3.1.bn2.weight", "FeatureExtraction.ConvNet.layer3.1.bn2.bias", "FeatureExtraction.ConvNet.layer3.1.bn2.running_mean", "FeatureExtraction.ConvNet.layer3.1.bn2.running_var", "FeatureExtraction.ConvNet.layer3.1.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.2.conv1.weight", "FeatureExtraction.ConvNet.layer3.2.bn1.weight", "FeatureExtraction.ConvNet.layer3.2.bn1.bias", "FeatureExtraction.ConvNet.layer3.2.bn1.running_mean", "FeatureExtraction.ConvNet.layer3.2.bn1.running_var", "FeatureExtraction.ConvNet.layer3.2.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.2.conv2.weight", "FeatureExtraction.ConvNet.layer3.2.bn2.weight", "FeatureExtraction.ConvNet.layer3.2.bn2.bias", "FeatureExtraction.ConvNet.layer3.2.bn2.running_mean", "FeatureExtraction.ConvNet.layer3.2.bn2.running_var", "FeatureExtraction.ConvNet.layer3.2.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.3.conv1.weight", "FeatureExtraction.ConvNet.layer3.3.bn1.weight", "FeatureExtraction.ConvNet.layer3.3.bn1.bias", "FeatureExtraction.ConvNet.layer3.3.bn1.running_mean", "FeatureExtraction.ConvNet.layer3.3.bn1.running_var", "FeatureExtraction.ConvNet.layer3.3.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.3.conv2.weight", "FeatureExtraction.ConvNet.layer3.3.bn2.weight", "FeatureExtraction.ConvNet.layer3.3.bn2.bias", "FeatureExtraction.ConvNet.layer3.3.bn2.running_mean", "FeatureExtraction.ConvNet.layer3.3.bn2.running_var", "FeatureExtraction.ConvNet.layer3.3.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.4.conv1.weight", "FeatureExtraction.ConvNet.layer3.4.bn1.weight", "FeatureExtraction.ConvNet.layer3.4.bn1.bias", "FeatureExtraction.ConvNet.layer3.4.bn1.running_mean", "FeatureExtraction.ConvNet.layer3.4.bn1.running_var", "FeatureExtraction.ConvNet.layer3.4.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer3.4.conv2.weight", "FeatureExtraction.ConvNet.layer3.4.bn2.weight", "FeatureExtraction.ConvNet.layer3.4.bn2.bias", "FeatureExtraction.ConvNet.layer3.4.bn2.running_mean", "FeatureExtraction.ConvNet.layer3.4.bn2.running_var", "FeatureExtraction.ConvNet.layer3.4.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.conv3.weight", "FeatureExtraction.ConvNet.bn3.weight", "FeatureExtraction.ConvNet.bn3.bias", "FeatureExtraction.ConvNet.bn3.running_mean", "FeatureExtraction.ConvNet.bn3.running_var", "FeatureExtraction.ConvNet.bn3.num_batches_tracked", "FeatureExtraction.ConvNet.layer4.0.conv1.weight", "FeatureExtraction.ConvNet.layer4.0.bn1.weight", "FeatureExtraction.ConvNet.layer4.0.bn1.bias", "FeatureExtraction.ConvNet.layer4.0.bn1.running_mean", "FeatureExtraction.ConvNet.layer4.0.bn1.running_var", "FeatureExtraction.ConvNet.layer4.0.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer4.0.conv2.weight", "FeatureExtraction.ConvNet.layer4.0.bn2.weight", "FeatureExtraction.ConvNet.layer4.0.bn2.bias", "FeatureExtraction.ConvNet.layer4.0.bn2.running_mean", "FeatureExtraction.ConvNet.layer4.0.bn2.running_var", "FeatureExtraction.ConvNet.layer4.0.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer4.1.conv1.weight", "FeatureExtraction.ConvNet.layer4.1.bn1.weight", "FeatureExtraction.ConvNet.layer4.1.bn1.bias", "FeatureExtraction.ConvNet.layer4.1.bn1.running_mean", "FeatureExtraction.ConvNet.layer4.1.bn1.running_var", "FeatureExtraction.ConvNet.layer4.1.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer4.1.conv2.weight", "FeatureExtraction.ConvNet.layer4.1.bn2.weight", "FeatureExtraction.ConvNet.layer4.1.bn2.bias", "FeatureExtraction.ConvNet.layer4.1.bn2.running_mean", "FeatureExtraction.ConvNet.layer4.1.bn2.running_var", "FeatureExtraction.ConvNet.layer4.1.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer4.2.conv1.weight", "FeatureExtraction.ConvNet.layer4.2.bn1.weight", "FeatureExtraction.ConvNet.layer4.2.bn1.bias", "FeatureExtraction.ConvNet.layer4.2.bn1.running_mean", "FeatureExtraction.ConvNet.layer4.2.bn1.running_var", "FeatureExtraction.ConvNet.layer4.2.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer4.2.conv2.weight", "FeatureExtraction.ConvNet.layer4.2.bn2.weight", "FeatureExtraction.ConvNet.layer4.2.bn2.bias", "FeatureExtraction.ConvNet.layer4.2.bn2.running_mean", "FeatureExtraction.ConvNet.layer4.2.bn2.running_var", "FeatureExtraction.ConvNet.layer4.2.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.conv4_1.weight", "FeatureExtraction.ConvNet.bn4_1.weight", "FeatureExtraction.ConvNet.bn4_1.bias", "FeatureExtraction.ConvNet.bn4_1.running_mean", "FeatureExtraction.ConvNet.bn4_1.running_var", "FeatureExtraction.ConvNet.bn4_1.num_batches_tracked", "FeatureExtraction.ConvNet.conv4_2.weight", "FeatureExtraction.ConvNet.bn4_2.weight", "FeatureExtraction.ConvNet.bn4_2.bias", "FeatureExtraction.ConvNet.bn4_2.running_mean", "FeatureExtraction.ConvNet.bn4_2.running_var", "FeatureExtraction.ConvNet.bn4_2.num_batches_tracked". 
	size mismatch for SequenceModeling.0.rnn.weight_ih_l0: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.0.rnn.weight_hh_l0: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.0.rnn.bias_ih_l0: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.0.rnn.bias_hh_l0: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.0.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.0.rnn.weight_hh_l0_reverse: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.0.rnn.bias_ih_l0_reverse: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.0.rnn.bias_hh_l0_reverse: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.0.linear.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for SequenceModeling.0.linear.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for SequenceModeling.1.rnn.weight_ih_l0: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.1.rnn.weight_hh_l0: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.1.rnn.bias_ih_l0: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.1.rnn.bias_hh_l0: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.1.rnn.weight_ih_l0_reverse: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.1.rnn.weight_hh_l0_reverse: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([1024, 256]).
	size mismatch for SequenceModeling.1.rnn.bias_ih_l0_reverse: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.1.rnn.bias_hh_l0_reverse: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([1024]).
	size mismatch for SequenceModeling.1.linear.weight: copying a param with shape torch.Size([512, 1024]) from checkpoint, the shape in current model is torch.Size([256, 512]).
	size mismatch for SequenceModeling.1.linear.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([256]).
	size mismatch for Prediction.weight: copying a param with shape torch.Size([188, 512]) from checkpoint, the shape in current model is torch.Size([188, 256]).

**Comment by Jitesh4389** [comment]
the model trained on Hindi  data set go error when custom load model

**Comment by Lucas-Mantuan** [comment]
@Jitesh4389 Hello! Could you solve this problem?

**Comment by donjuanpond** [comment]
Hey there @Lucas-Mantuan in case you're wondering after two years (and for the sake of everyone else coming accross this thread), @BlueTi 's solution worked perfectly for me, and I was having the same error as Jitesh.
