### ISSUE TITLE
turning to exe file

### ISSUE THREAD

**Issue by Yusima523** [JaidedAI/EasyOCR#612]
Hi, I'm from japan!

I made a project that recognize the number from a screenshot with EasyOCR. I wanted to make exe file to give this project to my friend, but whenever I change it into exe file and move it the next Error comes up. 

FileNotFounsError:  [Errno 2] No such file or directory: C:\\Users\\username\\AppData\\Local\\Temp\\_MEIxxxxxx\\easyocr\\character\\en_char.txt

I did it with pyinstaller. Does it usually work or not?

**Comment by WiiliamC** [comment]
You need to copy the whole easyocr to your _MEIxxxxxx folder:
https://github.com/JaidedAI/EasyOCR/issues/585

**Comment by mrblue6ix** [comment]
@WiiliamC 
Hi, this is a late reply but hopefully you still see this.

How do I copy easyocr to the _MEIxxxxx folder?
I guess I have to do this in the spec file for the program, is that right?
I'm unsure where I'd add it and what to add exactly to the spec file

Thanks
