### ISSUE TITLE
ModuleNotFoundError: No module named 'easyocr'

### ISSUE THREAD

**Issue by harshitkd** [JaidedAI/EasyOCR#614]
Hey,
I tried every method to install easyocr. I installed PyTorch without GPU 
`pip3 install torch torchvision torchaudio` 
and then I tried `pip install easyocr` but still I got an error, afterwards from one of the solved issues I tried 
`pip uninstall easyocr`
`pip install git+git://github.com/jaidedai/easyocr.git` but still unable to import easyocr.

And also firstly when I run the command `pip uninstall easyocr`, it showed me **WARNING: Skipping easyocr as it is not installed.**
@rkcosmos please help through this problem

**Comment by krisiney** [comment]
Did you use anaconda? If you might have several python env on your machine

**Comment by harshitkd** [comment]
No.

**Comment by ammar3010** [comment]
@harshitkd did you find any solution to this? I am stuck at the same problem

**Comment by harshitkd** [comment]
Hey I faced these problem two times one when I installed PyTorch with CUDA 11.3 and later without using it because my laptop didn't support it at that time. So check if your system supports it or not.

And if you have already checked it, I tried to reboot the environment and then it worked for me, maybe you can also go for it! :)

Let me know if you still face any problem.
