### ISSUE TITLE
CPU-Only easyocr Dockerfile optimization

### ISSUE THREAD

**Issue by Terminazor** [JaidedAI/EasyOCR#618]
I have to deploy easyOCR on a device without a GPU and with only limited disk-space. So I would like to make a Dockerfile image where easyOCR is only usable in CPU-mode and where the image uses up as little disk space as possible. The dockerfile looks like this:

```
FROM ubuntu:20.10

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y  git \   
    && apt-get install -y python3 \
    python3-pip \
    python3-opencv \
    && pip3 install \
    websockets \    
    && apt-get clean && rm -rf /var/lib/apt/lists/* 
RUN pip3 install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
RUN pip3 install git+git://github.com/jaidedai/easyocr.git
ADD img.jpg img.jpg
COPY test.py test.py
CMD ["python3", "test.py"]
```
The pythonfile test.py is (with a locally saved image that contains some text):
```
import cv2
from easyocr import Reader

img_cv = cv2.imread("img.jpg")
reader=Reader(["en"],gpu=False)
results=reader.readtext(img_cv)
print(results)
```
I already identified torch as the biggest dependency, and fortunately it also has a cpu-only mode, this image takes up to 2.77GB of disk space. Is it possible to optimize it even further? Or is there already a CPU-only installation guide for easyOCR?

**Comment by RoshanShaikh** [comment]
> I have to deploy easyOCR on a device without a GPU and with only limited disk-space. So I would like to make a Dockerfile image where easyOCR is only usable in CPU-mode and where the image uses up as little disk space as possible. The dockerfile looks like this:
> 
> ```
> FROM ubuntu:20.10
> 
> RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y  git \   
>     && apt-get install -y python3 \
>     python3-pip \
>     python3-opencv \
>     && pip3 install \
>     websockets \    
>     && apt-get clean && rm -rf /var/lib/apt/lists/* 
> RUN pip3 install torch==1.5.0+cpu torchvision==0.6.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
> RUN pip3 install git+git://github.com/jaidedai/easyocr.git
> ADD img.jpg img.jpg
> COPY test.py test.py
> CMD ["python3", "test.py"]
> ```
> 
> The pythonfile test.py is (with a locally saved image that contains some text):
> 
> ```
> import cv2
> from easyocr import Reader
> 
> img_cv = cv2.imread("img.jpg")
> reader=Reader(["en"],gpu=False)
> results=reader.readtext(img_cv)
> print(results)
> ```
> 
> I already identified torch as the biggest dependency, and fortunately it also has a cpu-only mode, this image takes up to 2.77GB of disk space. Is it possible to optimize it even further? Or is there already a CPU-only installation guide for easyOCR?

I am trying to deploy flask app on heroku and having same problem.
Did you find any solution?

**Comment by Ebdulmomen1** [comment]
any updates on this?

**Comment by ebadia** [comment]
Same here with Django Rest App in Heroku. Any ideas?

**Comment by mc51** [comment]
Here's an easy and robust approach that worked for me to reduce my docker image from 7.5GB to around 1.5GB for cpu only:

- Make sure you use [uv](https://docs.astral.sh/uv/) for your project
- Add `torch` and `torchvision` manually to your project: `uv add torch torchvision`
- Edit your `pyproject.toml` and add the following to make sure that pytorch is using the cpu only build:

```toml
[tool.uv.sources]
    torch       = [{ index = "pytorch-cpu" }]
    torchvision = [{ index = "pytorch-cpu" }]

[[tool.uv.index]]
    name     = "pytorch-cpu"
    url      = "https://download.pytorch.org/whl/cpu"
    explicit = true
```

This approach is described in the [uv documentation](https://docs.astral.sh/uv/guides/integration/pytorch/).
