### ISSUE TITLE
ValueError: Could not find a format to read the specified file in single-image mode

### ISSUE THREAD

**Issue by MaazBinMusa** [JaidedAI/EasyOCR#620]
I am trying to read text for this image but it is giving me this error

"ValueError: Could not find a format to read the specified file in single-image mode"

I loaded the model without gpu and in en language. I am attaching the image as well
![test](https://user-images.githubusercontent.com/19577994/145749220-4738b1ff-4ca4-4f5d-83b7-631f46860c35.png)

**Comment by senemaktas** [comment]
When I triy to download your image, the type of image is "WebP image" maybe error occur therefore. 

I got screenshot as png type and tried below code :

`
import matplotlib.pyplot as plt
import cv2
from easyocr import Reader
from pylab import rcParams
from IPython.display import Image
rcParams['figure.figsize'] = 8,16
from PIL import Image , ImageDraw , ImageFont

font = ImageFont.truetype("/content/BungeeColor-Regular_colr_Windows.ttf", 20,encoding="utf-8") 


reader = Reader(['en'], gpu=True)
im = Image.open('/content/sample.png')

results = reader.readtext('/content/sample.png', paragraph=False, text_threshold=0.5, rotation_info =[90])

def draw_boxes(image,bounds):
  draw = ImageDraw.Draw(image)
  for bound in bounds:
    print(bound)
    p0, p1, p2, p3 = bound[0]
    print(bound[1])
    print(*p0, *p1, *p2, *p3, *p0)
    draw.line([*p0, *p1, *p2, *p3, *p0], width=5)
    draw.text(p0,bound[1],(0,255,0),font=font)
  return image

draw_boxes(im,results)
`

Note: you have to download tff file for font. I do not remember where ı got it, search on google please.
