### ISSUE TITLE
Costum Model using TPS-ResNet-BiLSTM-Attn

### ISSUE THREAD

**Issue by alfredoartilesv** [JaidedAI/EasyOCR#622]
Hi I'm trying to set a costum model following the example on [custom model](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md) using the network TPS-ResNet-BiLSTM-Attn that is savailable in [deep-text-recognition-benchmark](https://github.com/clovaai/deep-text-recognition-benchmark). Tried generating the .py and .yaml files for the recognition network architecture and model configuration but have not succeeded in creating them based on the example provided.

I did change the hidden size parameter to 512 and the characters to match the total length of 37 that are required  by the network to match sizes.

Any Idea what else I could be missing?

**Comment by Nikhil-Sawant-141** [comment]
@alfredoartilesv Go to EasyOCR\trainer\modules. Here lie all your answers. Thank You.

**Comment by Lucas-Mantuan** [comment]
Hello @alfredoartilesv!
I've trained using network like you: TPS-ResNet-BiLSTM-Attn and I'm trying to generate .oy and .yaml files but the example provided doesn't seem to be comprehensive for this model network. Can you tell me how to solve the problem?

**Comment by Arindam-Jain** [comment]
@alfredoartilesv @Nikhil-Sawant-141 
as far as I know these are 36 characters `0123456789abcdefghijklmnopqrstuvwxyz` that will be in yaml file
so what is 37th character?
