### ISSUE TITLE
RuntimeError: Cannot re-initialize CUDA in forked subprocessv

### ISSUE THREAD

**Issue by shivanand3939** [JaidedAI/EasyOCR#628]
Getting the error:

"RuntimeError: Cannot re-initialize CUDA in forked subprocess. To use CUDA with multiprocessing, you must use the 'spawn' start method" 

when trying to call easyocr inside a celery thread... How to run easyOCR when multiprocessing is enabled

**Comment by hungshinlee** [comment]
Try to switch cuda compute mode to default mode by

```
sudo nvidia-smi -c 0
```
