### ISSUE TITLE
readtext doesn't work with latest opencv version

### ISSUE THREAD

**Issue by SHA65536** [JaidedAI/EasyOCR#630]
Windows 10 64bit
easyocr 1.4.1
opencv-python 4.5.5.62

## Problem
When using reader.readtext I was getting an error message from opencv
```
\lib\site-packages\easyocr\craft_utils.py", line 31, in getDetBoxes_core
    nLabels, labels, stats, centroids = cv2.connectedComponentsWithStats(text_score_comb.astype(np.uint8), connectivity=4)
cv2.error: Unknown C++ exception from OpenCV code
```

## Solution
Spent most of my day trying to fix whatever was wrong with connectedComponentsWithStats.... Issue didn't go away no matter what I did until I switched from opencv-python version 4.5.5.62 to version 4.5.4.60 .

I know this is a opencv problem so you can't do much about, but probably should limit the opencv version until they fix

**Comment by varunsingh3000** [comment]
Same issue here, I am using opencv-python 4.5.5.62 and at the readtext method my code would throw me a segmentation fault error (found using faulthandler). I haven't tried downgrading opencv yet to see if it works.

**Comment by varunsingh3000** [comment]
Just followed the above solution by @SHA65536 and now readtext is working.

**Comment by Vino2530** [comment]
I'm also facing the same error "cv2.error: Unknown C++ exception from OpenCV code easyocr". And followed the @SHA65536 solution it works perfectly for me.

**Comment by JafirDon** [comment]
Hi,
Please change the opencv-python version to 4.5.4.60.
Try this command,
```
!pip uninstall opencv-python
!pip install opencv-python==4.5.4.60 easyocr
```

then, you will use `import easyocr`
thank you

**Comment by hjalmoru1102** [comment]
@SHA65536 couldn't thank you enough

**Comment by Parashar7** [comment]
I am currently facing the same issue and tried the solution mentioned by @SHA65536, but it's not working for me, actually Easyocr is running fine in the python code, but throwing error when converted into an exe file.

Version of python and libraries that I am using: 
Python v3.9 
easyocr v1.7.0 
opencv-python v4.7.0.72 
auto-py-to-exe v2.36.0

The error that I got:
File "easyocr_check.py", line 11, in \<module\>
File "easyocr\\easyocr.py", line 452, in readtext
File "easyocr\\easyocr.py", line 321, in detect
File "easyocr\\detection.py", line 95, in get_textbox
File "easyocr\\detection.py", line 55, in test_net
File "easyocr\\craft_utils.py", line 236, in getDetBoxes
File "easyocr\\craft_utils.py", line 31, in getDetBoxes_core
cv2.error: Unknown C++ exception from OpenCV code
