### ISSUE TITLE
Character Bounding Boxes

### ISSUE THREAD

**Issue by Laveen-exe** [JaidedAI/EasyOCR#631]
Hi,
I am working on a project where I need the bounding boxes around the characters rather than the whole word. Is there any way I can do that using EasyOCR?
Thanks

**Comment by SatyamSSJ10** [comment]
> Hi, I am working on a project where I need the bounding boxes around the characters rather than the whole word. Is there any way I can do that using EasyOCR? Thanks

actually yes, 
`bounds = reader.readtext(img, detail=0,paragraph=True, y_ths=0.1 x_ths=0.1,text_threshold=0.9)`

the import things are `paragraph=True, y_ths=0.1 x_ths=0.1` you can try paragraph true/False and see if working or not.
you can read the API Doc for them, under Parameters 4: Bounding Box Merging
https://www.jaided.ai/easyocr/documentation/

**Comment by senthamizh31** [comment]
@Laveen-exe Did you get solution for this in easyocr?

**Comment by SatyamSSJ10** [comment]
> @Laveen-exe Did you get solution for this in easyocr?

the above is the answer bro. I have already posted the answer.

**Comment by senthamizh31** [comment]
@SatyamSSJ10  It is not working for me brother..
bounds = reader.readtext(img, detail=0,paragraph=True, y_ths=0.1, x_ths=0.1,text_threshold=0.9)

"bounds" returns the x y coordinates of the complete text in image.
**[[[[63, 77], [365, 77], [365, 119], [63, 119]], 'This is the sample text']]**

**Comment by SatyamSSJ10** [comment]
Try paragraph false, and decrease x_ths even more

**Comment by rmast** [comment]
> bounds = reader.readtext(img, detail=0,paragraph=True, y_ths=0.1, x_ths=0.1,text_threshold=0.9)

Nope.
![0001](https://user-images.githubusercontent.com/3341558/175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.jpg)

```
import easyocr
reader = easyocr.Reader(['nl','en']) # this needs to run only once to load the model into memory
bounds = reader.readtext('175789293-f39ddfdb-6f3e-4598-8d16-80a1f4a88b36.jpg', detail=0,paragraph=False, y_ths=0.01, x_ths=0.01,text_threshold=0.9)
print (bounds)
```

['KVK', '14', 'Wijziging', 'print', 'Ondernemings- en vestigingsgegevens', 'wis', 'clear', 'Waarom dit formulier?', 'voor het doorgeven van bijvoor-', 'Waarom het handelsregister?', 'Met', 'formulier kunt', 'wijzi-', 'beeld veranderde kapitaalsgege-', 'Het inschrijven van onder-', 'Dit gedeelte wordt door KVK ingevuld.', 'gingen', 'de ondernemings-', 'vens of wijzigingen', 'de statuten:', 'nemingen en rechtspersonen', 'vestigingsgegevens opgeven.', 'Daarvoor heeft u het formulier', 'is verplicht op grond van de', "'Wijziging vennootschaps- of", 'Handelsregisterwet.', 'Datum ontvangst', 'Het kan gaan om een', "rechtspersoongegevens' nodig:", 'De gegevens die u op', 'formulier', 'wijziging van:', 'invult, worden opgenomen in het', 'een handelsnaam;', 'Vragen?', 'Handelsregister.', 'openbaar:', 'een internetadres (www-adres);', 'Kijk', 'KVKnl of bel de Kamer', 'anderen kunnen', 'gegevens', 'de bedrijfsactiviteiten;', 'van Koophandel', 'als u nog', 'natrekken', 'ook', 'kunt gegevens', 'het adres', 'correspondentie-', 'vragen heeft. Bijvoorbeeld over', 'opvragen van ondernemingen', 'adres;', 'het invullen van', 'formulier.', 'waarmee', 'bijvoorbeeld zaken', 'Datum inschrijving', 'het telefoon-, faxnummer of', 'doen.', 'e-mailadres;', 'Als', 'een vergissing maakt bij', 'Zo draagt het Handelsregister bij', 'het aantal werkzame personen;', 'het invullen; dan kunt u het foute', 'tot zeker zakendoen:', 'opheffing', 'overdracht van', 'antwoord doorhalen en het', 'KVK-nummer', 'onderneming of vestiging:', 'goede antwoord erbij zetten:', 'kunt dit formulier niet gebruiken', 'Plaats hierbij wel', 'handtekening:', 'Inschrijfgegevens bij KVK', 'Toelichting', 'welke', 'onderneming of rechtspersoon wordt de wijziging opgegeven?', 'Om', 'gewijzigde gegevens', 'te kunnen doorvoeren, heeft', 'KVK de gegevens nodig', 'naam', 'waaronder', 'onderneming', 'of rechtspersoon staat inge-', 'schreven:', 'naam; plaats van vesti -', 'ging', 'inschrijfnummer.', 'plaats van vestiging', 'inschrijfnummer bij KVK', 'Soort wijziging', 'Toelichting', 'De wijzigingen betreffen', 'kunt op dit formulier', 'wijzigingen opgeven', 'de', 'de hoofdvestiging of de enige vestiging', 'gegevens van één vestiging:', 'de hoofdvestiging of', 'één andere vestiging', 'enige vestiging;', 'één vestiging:', 'het adres van deze vestiging is', '2.2', 'Kruis hier aan wat', 'gewijzigd', 'door naar de aangegeven vraag (meerdere antwoorden mogelijk)', 'handelsnaam of handelsnamen', 'naar vraag', 'bedrijfsactiviteiten; diensten en/of producten', 'naar vraag', 'activiteiten van', 'rechtspersoon zonder onderneming', 'naar vraag', 'adres en/of correspondentieadres', 'naar vraag', 'internetadres (www-adres)', 'naar vraag', 'telefoon-, faxnummer; e-mailadres; berichtenboxnaam', 'naar vraag', 'aantal werkzame personen', 'naar vraag', 'opheffing of overdracht', 'naar vraag', 'Kamer van Koophandel@ juni 2020   Wijziging ondernemings- en vestigingsgegevens', 'blad', 'van', 'Voor']

**Comment by SatyamSSJ10** [comment]
I think EasyOCR is limited to it. Alternatively you can try streching the image so that there's more space between words. Stretch the image and then run the OCR

**Comment by rmast** [comment]
I’m now thinking of starting segmentation with EasyOCR and then Otsu and eventually invert the fond boxes and follow through with Tesseract for finer grained operations.

**Comment by najeebullahshah** [comment]
@rmast why don't you try pytesserect they have function image_to_boxes and it does gives boxes on each character

**Comment by rmast** [comment]
Pytesseract's image_to_boxes depends on Tesseract's segmenter that makes clearly readable text disappear without warning. I'm now trying to combine EasyOCR for detection and tesseract page segmentation mode 7, with promising results. However pytesseract doesn't provide font-details. Tesserocr might come closer to what I want.

**Comment by rmast** [comment]
I can allmost get separate words with, width_ths=0.03, but still not separate chars.

**Comment by SatyamSSJ10** [comment]
> I can allmost get separate words with, width_ths=0.03, but still not separate chars.

I don't think you'll get separate characters unless you tweak the OCR files. Else you can do is slice the words

**Comment by Solyemin** [comment]
Hey , @SatyamSSJ10 have you been able to detect individual characters using easyocr??if yes can you please provide the code here??

**Comment by rmast** [comment]
With the given hints I was 't able to. Workaround was using detect for sentences and using single line Tesseract (mode 6 or 7?) including legacy mode to find the boxes. I provided a Tesseract PR on 90 degree text that might still not be accepted due to lack of testing capacity.

Outlook voor Android downloaden<https://aka.ms/ghei36>
________________________________
