### ISSUE TITLE
Out of memory issues

### ISSUE THREAD

**Issue by RobindeGrootNL** [JaidedAI/EasyOCR#638]
Environment:
- Databricks Runtime 10.2 ML GPU
- Python 3.8
- 128GB Ram, Tesla V100

I am trying to get EasyOCR to run on Databricks (not using spark yet, just trying to run it inside a notebook on a numpy array) and I get issues with memory management and my kernel keeps restarting. This happens regardless if I am using the GPU or CPU versions of EasyOCR.

I install the library using `%sh pip install easyocr` (shell command in Databricks) and import it using `import easyocr`.

I think initialise the reader as follows: `reader = easyocr.Reader(['en'])`, which goes ahead without problems. Then running 'result = reader.readtext(img_array)' gives a weird error: 

```
Caused by: py4j.Py4JNetworkException: Error while sending a command: null response: c
p0
runLine
sresult = reader.readtext("/dbfs/tmp/.../100082933.png")
ao725
s5719662678366250367_5579501158655526979_3c069821e91141bf9d3cc599ab1d34a9
ro726
e

```

Running the following gave the following result gave zeroes for `memory_reserved` as well as `memory_allocated`:
```
print(
torch.cuda.get_device_properties(0).total_memory
,torch.cuda.memory_reserved(0)
,torch.cuda.memory_allocated(0)
)
```

To force the use of the cpu, I also ran it as follows:
reader = easyocr.Reader(['en'], gpu=False)
result = reader.readtext(img_array)

Which resulted in the following error:
```
ConnectException: Connection refused (Connection refused)
Error while obtaining a new communication channel
ConnectException error: This is often caused by an OOM error that causes the connection to the Python REPL to be closed. Check your query's memory usage.
```

This also happens when not loading it from a numpy array but just directly from a .png image from disk.

Even using an example image gives the same error:
`result = reader.readtext("https://github.com/JaidedAI/EasyOCR/blob/master/examples/english.png?raw=true")
`
What could be causing this and what would be a way to prevent this from happening so I can use easyocr in my workflow? I will worry about running inside a Spark UDF later.

**Comment by bugra10ur** [comment]
I have the same problem even if I try with very small size images

**Comment by bugra10ur** [comment]
this following package versions solved my issue.

torch                 1.9.1             
torchvision        0.10.1              
tensorflow         2.2.0   
scikit-image       0.17.2

**Comment by RobindeGrootNL** [comment]
Thank you for the update, and I'm happy to hear you managed to get it working! I in the meantime switched to another library for OCR (tesserocr python library based on tesseract-ocr) which worked nice and fast for me. For completeness I list here the library versions I used that did not work for me:

torch: 1.10.0+gpu
torchvision: 0.11.1+gpu
tensorflow: 2.7.0
