### ISSUE TITLE
from .cv2 import _registerMatType ImportError: cannot import name '_registerMatType'

### ISSUE THREAD

**Issue by languandong** [JaidedAI/EasyOCR#639]
the problem of "import easyocr'
what should I  do?

**Comment by vneseresearcher** [comment]
Change version of opencv2, bro!

**Comment by bugra10ur** [comment]
Try to feed your input like below; It worked for me.
np.asarray(image)

**Comment by SatyamSSJ10** [comment]
use `opencv_python_headless==4.5.2.52`
`pip install opencv_python_headless==4.5.2.52`
