### ISSUE TITLE
Installation error, how to solve?

### ISSUE THREAD

**Issue by vssir** [JaidedAI/EasyOCR#641]
Installation error, how to solve?
![install](https://user-images.githubusercontent.com/10388068/149310578-a32fc2b2-526c-418c-9aa8-8666177b0f01.png)

Environment: Python 3.10.1

**Comment by Akhilesh64** [comment]
@vssir Downgrade your python version

**Comment by JafirDon** [comment]
Hi,
Try this command,
```
!pip install opencv-python==4.1.2.30 easyocr
```

**Comment by SatyamSSJ10** [comment]
> Installation error, how to solve? ![install](https://user-images.githubusercontent.com/10388068/149310578-a32fc2b2-526c-418c-9aa8-8666177b0f01.png)
> 
> Environment: Python 3.10.1

EasyOCR best works in python 3.8.x and opencv_python_headless==4.5.2.52

**Comment by vssir** [comment]
Thank you all.

**Comment by ericchansen** [comment]
Hey, no installation error here, but I'm just curious why we're restricting the OpenCV version below <=4.5.4.60? Can anyone point me in the right direction?

**Comment by rkcosmos** [comment]
see #630
