### ISSUE TITLE
please support like led font

### ISSUE THREAD

**Issue by freecells** [JaidedAI/EasyOCR#642]
eg:
![smg](https://user-images.githubusercontent.com/38281785/149431507-1b1eaca2-ea6b-4332-b14f-37896423e81f.png)
![smg1](https://user-images.githubusercontent.com/38281785/149431529-9f526bd5-dc16-435f-a3b5-8284c0286cae.png)

### Font :
[digifaw.zip](https://github.com/JaidedAI/EasyOCR/files/7866827/digifaw.zip)

**Comment by rkcosmos** [comment]
thanks for the suggestion, we will consider it.
