### ISSUE TITLE
Increase easyOCR model performance on cpu

### ISSUE THREAD

**Issue by mahmoudhammouri** [JaidedAI/EasyOCR#645]
Hi 
How I can increase number of workers of CPU when I use aesyOCR model ???
I look-up to increase the speed of processes without using gpu

Thanks

**Comment by mahmoudhammouri** [comment]
@rkcosmos 
please, I need your support 

Thanks in advance

**Comment by vamshi-1611** [comment]
I am also facing with same issue can u please support

**Comment by connected201** [comment]
yes, very poor performance on dual xeon i need about ~5-8 seconds to recognize 1 image!. abbyy fine reader can process ~200 images in ~3-5 seconds.
