### ISSUE TITLE
Needed device specifications to run easyOCR model

### ISSUE THREAD

**Issue by mahmoudhammouri** [JaidedAI/EasyOCR#646]
Hi 

What is the minimum requirements of RAM, CPU, or GPU that we need it to run easyOCR model 
not to fine-tuning or retraining on another data ???

Thanks

**Comment by Langlais115** [comment]
**GPU**:
As far as I understand your GPU need to **support CUDA** software layer, that gives direct access to the GPU's virtual instruction set and parallel computational elements. I don't know the exact spec for the GPU. What I don't know is which minimum version is required.
[You can find the list Here on Wikipedia](https://en.wikipedia.org/wiki/CUDA#GPUs_supported)

**CPU**:
For the CPU, it needs to support the [**instruction AVX2**](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#CPUs_with_AVX2)

I do have none of them so I'm stuck too. :- (

**Comment by roccopietrini** [comment]
@rkcosmos can you please give some specification about GPU (memory) ? In order to have a single inference without OOM, what is the minimum GPU specification?
