### ISSUE TITLE
SSL verification error on Mac.

### ISSUE THREAD

**Issue by FPFdeveloper** [JaidedAI/EasyOCR#647]
I don't get this error on my windows machine.
This is a fresh venv with modules just installed, tried installing both pip and github, neither worked.

<img width="1440" alt="Screenshot 2022-01-20 at 00 10 51" src="https://user-images.githubusercontent.com/74162889/150240381-ad51ca27-baec-4e7b-aa3d-4d4475ea2d69.png">

**Comment by mertguvencli** [comment]
It's related to Python installation. 

The [Stackoverflow](https://stackoverflow.com/a/42098127/10515127) answer may help you.

Add the following code at the top of your file
```python 
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

# then import Easyocr library
import easyocr
```

**Comment by ageron** [comment]
@mertguvencli , please don't recommend this solution, it will destroy all SSL security. The correct solution is to install the root certificates. It's just a matter of opening a terminal and running:

```
/Applications/Python\ 3.10/Install\ Certificates.command
```
