### ISSUE TITLE
dataset used for english/latin language

### ISSUE THREAD

**Issue by Shiro-LK** [JaidedAI/EasyOCR#651]
Hello,

Thank  you for sharing this very good work!

I have a question regarding latin/english dataset used for the training of the CRNN model. Is it trained only on the Synth dataset ? (https://www.robots.ox.ac.uk/~vgg/data/scenetext/) or is there more datasets than this one ?

**Comment by ziyeZzz** [comment]
same question. 
Is the dataset as same as deep-text-recognition-benchmark used? [MJSynth (MJ)](http://www.robots.ox.ac.uk/~vgg/data/text/)[1] and [SynthText (ST)](http://www.robots.ox.ac.uk/~vgg/data/scenetext/)[2]

and which part of the recogniton model have easyOCR changed from the benchmark? How does this change affect?
