### ISSUE TITLE
I have a problem with import

### ISSUE THREAD

**Issue by KhaledAbuNada-AI** [JaidedAI/EasyOCR#653]
**import easyocr
ModuleNotFoundError: No module named 'easyocr'**

**Comment by SatyamSSJ10** [comment]
did you install easyocr?
`pip install easyocr`

**Comment by connected201** [comment]
pip3! pip is default for pip2 python, easyocr not working on python2! if you have version 2 and 3 you need specify pip version and use every time pip3! developers can add hint in main page! or change install command.
