### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by mwt-why** [JaidedAI/EasyOCR#655]
my operating system is ubuntu:
the code :
------------------------------------------------------------------------------
import easyocr

path = "/home/why/work/python/pas/images/shot.png"
reader = easyocr.Reader(['en'])
result = reader.readtext(path)

**Comment by 678098** [comment]
@mwt-why please try this
https://stackoverflow.com/questions/70567344/easyocr-segmentation-fault-core-dumped
