### ISSUE TITLE
combine Arabic with bengali  in same image

### ISSUE THREAD

**Issue by mobassir94** [JaidedAI/EasyOCR#657]
easyocr works with images containing english+any other language with it,but i have samples where bengali and arabic both are present in same image and this approach doesn't work : `reader = easyocr.Reader(['en','bn','ar'])` or even `reader = easyocr.Reader(['bn','ar'])`
is there any way to use easyocr on samples where both bengali and arabic are present?

**Comment by SatyamSSJ10** [comment]
could you send me the sample images, let me try, I have done some fine-tuning in my code to work better. So I might as well try this

**Comment by mobassir94** [comment]
@SatyamSSJ10  sure
from here you can get sample images : https://www.kaggle.com/datasets/mobassir/tafsir-ibn-kathir-by-islamic-foundation check the folders containing images,not all images have bangla+arabic mixture but at least 50-60% images containing mixture of bangla+arabic

**Comment by rm-asif-amin** [comment]
@mobassir94 Did you solve this?

**Comment by mobassir94** [comment]
@rm-asif-amin https://github.com/mobassir94/Multilingual-Reader

**Comment by rm-asif-amin** [comment]
@mobassir94 Thank you for sharing. I'm checking it out.
