### ISSUE TITLE
Pillow version depencency conflict

### ISSUE THREAD

**Issue by mikko-kepit** [JaidedAI/EasyOCR#658]
Currently installing via pip seems to cause `pillow` library required version conflict between dependencies `torchvision`and `sckikit-image`.

**OS**: MacOS Catalina 10.15.7
**Pyhon version**: 3.8.2

Output of `pipdeptree` tool after `pip install easyocr` fails with error `imageio 2.14.1 requires pillow>=8.3.2, but you'll have pillow 8.2.0 which is incompatible.`. Conflicting packages highlighted with bold.

easyocr==1.4.1
  - numpy [required: Any, installed: 1.22.1]
  - opencv-python-headless [required: Any, installed: 4.5.5.62]
    - numpy [required: >=1.14.5, installed: 1.22.1]
    - numpy [required: >=1.17.3, installed: 1.22.1]
  - Pillow [required: <8.3.0, installed: 8.2.0]
  - python-bidi [required: Any, installed: 0.4.2]
    - six [required: Any, installed: 1.16.0]
  - PyYAML [required: Any, installed: 6.0]
  - scikit-image [required: Any, installed: 0.19.1]
    - imageio [required: >=2.4.1, installed: 2.14.1]
      - numpy [required: Any, installed: 1.22.1]
      - **pillow [required: >=8.3.2, installed: 8.2.0]**
    - networkx [required: >=2.2, installed: 2.6.3]
    - numpy [required: >=1.17.0, installed: 1.22.1]
    - packaging [required: >=20.0, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.7]
    - pillow [required: >=6.1.0,!=8.3.0,!=7.1.1,!=7.1.0, installed: 8.2.0]
    - PyWavelets [required: >=1.1.1, installed: 1.2.0]
      - numpy [required: >=1.17.3, installed: 1.22.1]
    - scipy [required: >=1.4.1, installed: 1.7.3]
      - numpy [required: >=1.16.5,<1.23.0, installed: 1.22.1]
    - tifffile [required: >=2019.7.26, installed: 2021.11.2]
      - numpy [required: >=1.15.1, installed: 1.22.1]
  - scipy [required: Any, installed: 1.7.3]
    - numpy [required: >=1.16.5,<1.23.0, installed: 1.22.1]
  - torch [required: Any, installed: 1.10.2]
    - typing-extensions [required: Any, installed: 4.0.1]
  - torchvision [required: >=0.5, installed: 0.11.3]
    - numpy [required: Any, installed: 1.22.1]
    - **pillow [required: >=5.3.0,!=8.3.0, installed: 8.2.0]**
    - torch [required: ==1.10.2, installed: 1.10.2]
      - typing-extensions [required: Any, installed: 4.0.1]

**Comment by mikko-kepit** [comment]
I was able to install all packages without conflicts with `--use-feature=2020-resolver` argument for `pip`. Weird. I thought it was already in use.

```
> virtualenv venv
created virtual environment CPython3.8.2.final.0-64 in 277ms
  creator CPython3macOsFramework(dest=/ ... /venv, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/ .. /Library/Application Support/virtualenv)
    added seed packages: pip==20.2.4, setuptools==50.3.2, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
> source venv/bin/activate.fish
(venv) > pip install easyocr --use-feature=2020-resolver

...

Successfully installed Pillow-8.2.0 PyWavelets-1.2.0 PyYAML-6.0 easyocr-1.4.1 imageio-2.9.0 networkx-2.6.3 numpy-1.22.1 opencv-python-headless-4.5.5.62 packaging-21.3 pyparsing-3.0.7 python-bidi-0.4.2 scikit-image-0.19.1 scipy-1.7.3 six-1.16.0 tifffile-2021.11.2 torch-1.10.2 torchvision-0.11.3 typing-extensions-4.0.1
```

Ouput of `pipdeptree` after successful install:

easyocr==1.4.1
  - numpy [required: Any, installed: 1.22.1]
  - opencv-python-headless [required: Any, installed: 4.5.5.62]
    - numpy [required: >=1.14.5, installed: 1.22.1]
    - numpy [required: >=1.17.3, installed: 1.22.1]
  - Pillow [required: <8.3.0, installed: 8.2.0]
  - python-bidi [required: Any, installed: 0.4.2]
    - six [required: Any, installed: 1.16.0]
  - PyYAML [required: Any, installed: 6.0]
  - scikit-image [required: Any, installed: 0.19.1]
    - imageio [required: >=2.4.1, installed: 2.9.0]
      - numpy [required: Any, installed: 1.22.1]
      - pillow [required: Any, installed: 8.2.0]
    - networkx [required: >=2.2, installed: 2.6.3]
    - numpy [required: >=1.17.0, installed: 1.22.1]
    - packaging [required: >=20.0, installed: 21.3]
      - pyparsing [required: >=2.0.2,!=3.0.5, installed: 3.0.7]
    - pillow [required: >=6.1.0,!=8.3.0,!=7.1.1,!=7.1.0, installed: 8.2.0]
    - PyWavelets [required: >=1.1.1, installed: 1.2.0]
      - numpy [required: >=1.17.3, installed: 1.22.1]
    - scipy [required: >=1.4.1, installed: 1.7.3]
      - numpy [required: >=1.16.5,<1.23.0, installed: 1.22.1]
    - tifffile [required: >=2019.7.26, installed: 2021.11.2]
      - numpy [required: >=1.15.1, installed: 1.22.1]
  - scipy [required: Any, installed: 1.7.3]
    - numpy [required: >=1.16.5,<1.23.0, installed: 1.22.1]
  - torch [required: Any, installed: 1.10.2]
    - typing-extensions [required: Any, installed: 4.0.1]
  - torchvision [required: >=0.5, installed: 0.11.3]
    - numpy [required: Any, installed: 1.22.1]
    - pillow [required: >=5.3.0,!=8.3.0, installed: 8.2.0]
    - torch [required: ==1.10.2, installed: 1.10.2]
      - typing-extensions [required: Any, installed: 4.0.1]
pipdeptree==2.2.1
  - pip [required: >=6.0.0, installed: 20.2.4]
setuptools==50.3.2
wheel==0.35.1

**Comment by ilovedogs1235** [comment]
nope
