### ISSUE TITLE
domain specific dictionary

### ISSUE THREAD

**Issue by naarkhoo** [JaidedAI/EasyOCR#660]
I am doing OCR (english and french) on cohorts of text that are very domain specific - seems often the results are misspelled - any recommendation on how to provide the model with domain specific dictionary ? alternatively I can do a post-analysis on top of the text recognition result - which approach do you recommend.

**Comment by naarkhoo** [comment]
I still appreciate to get a few words on this; even if my question is irrelevant I appreciate any hint on where to look for.

**Comment by rkcosmos** [comment]
I would recommend post-analysis. This would be easiest approach in my opinion. However, if you want to improve the recognition model itself, you can do that by using your dictionary to generate your own dataset and train/finetune a recognition model. see https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md for a guideline on training your model.
