### ISSUE TITLE
chinese text detected not accurate

### ISSUE THREAD

**Issue by yfq512** [JaidedAI/EasyOCR#663]
Any parameters can I tune to improve accuracy？

**Comment by yfq512** [comment]
Chinese word size is too small that accuracy is reduced, How to tune parameters to improve accuracy?

**Comment by SatyamSSJ10** [comment]
> Chinese word size is too small that accuracy is reduced, How to tune parameters to improve accuracy?

You can try increasing the image size first with quality, you can use Waifu2x to increase image size without much loss.

if you want to improve the confident level of text (meaning if you only want to print the characters the EasyOCR is confident that they look same) add this parameter `text_threshold=0.9` else you could try reducing it in case you're not getting the characters at that position. min=0, max=1
ex = `bounds = reader.readtext(img, detail=0,paragraph=True, y_ths=1,canvas_size=8500,text_threshold=0.9)`
