### ISSUE TITLE
failure of simple test while passing others

### ISSUE THREAD

**Issue by tzuohann** [JaidedAI/EasyOCR#664]
Hi.
I've tested the file in your example folder, english.png and as expected, get

```
reader = easyocr.Reader(['en'],gpu=False)
result = reader.readtext('english.png')
result
[([...], 'Reduce your risk of ...infection:', 0.9371086335677042), ([...], 'Clean hands with soa... and water', 0.9680031161010356), ([...], 'or alcohol-based hand rub', 0.8901542465346892), ([...], 'Cover nose and mouth...ughing and', 0.9659280712799074), ([...], 'sneezing with tissue...exed elbow', 0.8517949274596233), ([...], 'Avoid close contact ...nyone with', 0.8957650533414668), ([...], 'cold or flu-like symptoms', 0.7669340484632636), ([...], 'Thoroughly cook meat and eggs', 0.8505019256481634), ([...], 'No unprotected conta... live wild', 0.8362625011949715), ([...], 'or farm animals', 0.7218451089397303), ([...], 'World Health', 0.9974510773183727), ([...], 'Organization', 0.9990362748667504)]

```
I'm guessing from this that the installation is correct.

The attached file Number10.jpg (It's so simple it appears in here in the Forum looking like a bolded **10** text below ) works in the Demo on your website but on my computer, it doesn't.

```
reader = easyocr.Reader(['en'],gpu=False)
result = reader.readtext('Number10.jpg')
result 
[]
```
yields an empty list

I'm puzzled. Could there be some options used in the Demo portion of your website?

Thank you!
T

![Number10](https://user-images.githubusercontent.com/2057796/153470298-fcbc16d7-18be-47e7-bb92-d64973de12c2.jpg)

**Comment by sas9mba** [comment]
https://github.com/JaidedAI/EasyOCR/issues/570
