### ISSUE TITLE
Support Pillow versions > 8.3.0

### ISSUE THREAD

**Issue by shannon-alliance** [JaidedAI/EasyOCR#696]
easyocr dependencies specify `Pillow<8.3.0` which is causing conflicts with other packages. I suspect the reason for this is a bug in 8.3.0 which was fixed in 8.3.1 because there are a few other packages that explicitly exclude this version. If easyocr supports current versions of Pillow it would be better to make the requirement `pillow!=8.3.0 `.

**Comment by yqchilde** [comment]
I have the same request and hope to consider supporting pilot versions > 8.3.0.

**Comment by rkcosmos** [comment]
Pip package is updated. The restriction is lifted.
