### ISSUE TITLE
using custom detection model instead of CRAFT

### ISSUE THREAD

**Issue by amroghoneim** [JaidedAI/EasyOCR#712]
Hello, I am currently in the process of training a custom detection model with different architecture from that of CRAFT. Does easyOCR require only using CRAFT or is it easy to replace it with my own(such as loading it from a directory)?

**Comment by huynhkhoa44** [comment]
same question

**Comment by amroghoneim** [comment]
@huynhkhoa44  We did eventually use our own detection model. We made sure to send the output of that model to have the same format needed by the recognize method input and that's it.

Just noticed your comment so thought I'd share with you even though I don't think you need it now.
