### ISSUE TITLE
Issue recognizing multiple columns 

### ISSUE THREAD

**Issue by IsraelAbebe** [JaidedAI/EasyOCR#720]
Given an image like this 

![image](https://user-images.githubusercontent.com/15804692/167088174-ab5b4cd1-f32e-4b7a-9249-e8f8d9d0fbf7.png)

EasyOCR returns the following 

![image](https://user-images.githubusercontent.com/15804692/167088284-96c84ec0-4684-4214-b9a1-f654067cb32b.png)

while other libraries handle this in the right way 

![image](https://user-images.githubusercontent.com/15804692/167088397-2f02a0ac-6ca5-4176-adad-85d378678aad.png)

Is there a way to make EasyOCR handle this kind of scenarios?

**Comment by rkcosmos** [comment]
Hi, try setting optional argument `paragraph = True`. See documentation [here](https://www.jaided.ai/easyocr/documentation/). For example,
`reader.readtext('file_path', paragraph=True)`

**Comment by IsraelAbebe** [comment]
works , thank you

**Comment by IsraelAbebe** [comment]
![image](https://user-images.githubusercontent.com/15804692/167870485-cca1ef83-c09c-4797-a850-580a9caffca0.png)


the result returned different objects. how can one handle this

**Comment by rkcosmos** [comment]
you can convert list to tuple `tuple(list_name)` or tuple to list `list(tuple_name)`.
