### ISSUE TITLE
ERROR WHEN INSTALL opencv-python-headless

### ISSUE THREAD

**Issue by VERISBABY** [JaidedAI/EasyOCR#734]
TERMINAL SHOW THIS ERROR WHEN I UPDATE LATEST VER. OF opencv-python-headless 4.5.5.64:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
easyocr 1.4.2 requires opencv-python-headless<=4.5.4.60, but you have opencv-python-headless 4.5.5.64 which is incompatible

**Comment by s39674** [comment]
Hi!
Do you have to install `opencv-python-headless==4.5.5.64`? Why? 
If not, uninstall it and reinstall `easyocr`
