### ISSUE TITLE
About incorporating CRAFT training code to this repository

### ISSUE THREAD

**Issue by gmuffiness** [JaidedAI/EasyOCR#736]
It seems that many people need the CRAFT training code, and I recently uploaded a reimplemented training code with similar performance to the CRAFT paper. 

Would it help if I incorporated my training code into the repository here?
@rkcosmos

**Comment by rkcosmos** [comment]
yes, sounds good. I suggest putting your code in 'trainer/craft' folder.

**Comment by gmuffiness** [comment]
Thank you for answering. I'll make a pull request soon.
