### ISSUE TITLE
Not cloning in colab

### ISSUE THREAD

**Issue by smritiranjan** [JaidedAI/EasyOCR#744]
ERROR: Command errored out with exit status 128: git clone -q git://github.com/jaidedai/easyocr.git /tmp/pip-req-build-l0wxvmvs Check the logs for full command output.
![Untitled1 ipynb - Colaboratory](https://user-images.githubusercontent.com/24734530/171790090-f7785598-c6e4-4976-a431-2adc99a2f681.png)

**Comment by s39674** [comment]
It says `Successfully installed easyocr..` just above your command, are you trying to install it again?

**Comment by smritiranjan** [comment]
Thank you @s39674  for answering me, 
Easy OCR is installed, but when running `!pip install git+git://github.com/jaidedai/easyocr.git`  that command its stuck

**Comment by smritiranjan** [comment]
Sorry for unconditionally closing the issue

**Comment by s39674** [comment]
Can you try with: `!pip install git+https://github.com/jaidedai/easyocr.git`?
Does manual cloning work? if so, I think you can just use `!pip install .` in the cloned directory and it is the same process.

**Comment by smritiranjan** [comment]
@s39674  It works now, may be that time some issue occurred, Thank you so much friend. I'm closing the issue

**Comment by s39674** [comment]
Glad to help! 🚀
