### ISSUE TITLE
TypeError: 'NoneType' object is not iterable in recognize method

### ISSUE THREAD

**Issue by amroghoneim** [JaidedAI/EasyOCR#759]
I am using the recognize method provided with my own preset horizontal_list_agg list.
The documentation says that free_list by default is None and that I only need either one of horizontal or free list, yet I get this error as seen below:
```
for bbox in free_list: 

TypeError: 'NoneType' object is not iterable in recognize method
```

**Comment by rkcosmos** [comment]
I probably miss this condition. Can you try `free_list = []` (empty list)?
