### ISSUE TITLE
Word Spacing 

### ISSUE THREAD

**Issue by hanish3464** [JaidedAI/EasyOCR#77]
Hi!

Is good performance about word spacing ?
I think that word spacing will be better if use coordinates of word and line detection bounding box of CRAFT!
I wonder what you think! 

thanks!

**Comment by rkcosmos** [comment]
I agree that information from CRAFT output is very rich and we are currently not use it fully. Your idea is promising but the neat implementation of this can be challenging. If you or anyone can implement this idea and test that it improves the prediction, I would gladly accept a PR.
