### ISSUE TITLE
Use a few custom recognition models

### ISSUE THREAD

**Issue by Palushok** [JaidedAI/EasyOCR#773]
Hello. How i can 2 my own recognition models? For one i can set model_storage_directory, user_network_directory and recog_network. But what to do, if i need two?

**Comment by Shiro-LK** [comment]
@Palushok  I have the same question, did you find out a way to use two custom models ?

**Comment by Palushok** [comment]
I realized that it's impossible. You have 2 options: create custom predictor with 1 detector and two recognizers and use recognizers successively, or you can train custom recognizer model on more outputs (2 alphabets). 
Param "List of lenguages" in constructor in this repo only choose, which pretrained multilingual model you can take.
