### ISSUE TITLE
Tips and trick 

### ISSUE THREAD

**Issue by AliRezaSafaei9494** [JaidedAI/EasyOCR#775]
Hi,
could you share some tip and tirck about creating data and config file 
for train arabic model
thanks

**Comment by AliRezaSafaei9494** [comment]
what is config file for finetune arabic model?

**Comment by AliRezaSafaei9494** [comment]
> [instructions](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md) this is the instructions in training a new model and you can fine tune the existing Arabic Model i also train as you and there is no any progress in accuracy

what is config file for fine tuning arabic model?

**Comment by Mahmuod1** [comment]
[en_filtered_config.yaml](https://github.com/JaidedAI/EasyOCR/blob/master/trainer/config_files/en_filtered_config.yaml) 
this is the config file for English you can add also the Arabic characters and numbers

**Comment by MohieEldinMuhammad** [comment]
Did you find any tips for improving the Arabic model guys ?
