### ISSUE TITLE
cannot import name 'isStringType'

### ISSUE THREAD

**Issue by Sharan1712** [JaidedAI/EasyOCR#80]
Getting the following error while importing easyocr

Using python 3.6.10

`ImportError                               Traceback (most recent call last)
<ipython-input-44-cf55e523160e> in <module>
----> 1 import easyocr
      2 reader = easyocr.Reader(['en'])
      3 reader.readtext('F:/IT Mines/Images/shabbirPan.jpg')

~\anaconda3\envs\OCR\lib\site-packages\easyocr\__init__.py in <module>
----> 1 from .easyocr import Reader
      2 
      3 __version__ = '1.0.0'

~\anaconda3\envs\OCR\lib\site-packages\easyocr\easyocr.py in <module>
----> 1 from .detection import get_detector, get_textbox
      2 from .imgproc import loadImage
      3 from .recognition import get_recognizer, get_text
      4 from .utils import group_text_box, get_image_list, calculate_md5
      5 import numpy as np

~\anaconda3\envs\OCR\lib\site-packages\easyocr\detection.py in <module>
      9 from .craft_utils import getDetBoxes, adjustResultCoordinates
     10 from .imgproc import resize_aspect_ratio, normalizeMeanVariance
---> 11 from .craft import CRAFT
     12 
     13 def copyStateDict(state_dict):

~\anaconda3\envs\OCR\lib\site-packages\easyocr\craft.py in <module>
      9 import torch.nn.functional as F
     10 
---> 11 from .modules import vgg16_bn, init_weights
     12 
     13 class double_conv(nn.Module):

~\anaconda3\envs\OCR\lib\site-packages\easyocr\modules.py in <module>
      3 import torch.nn.functional as F
      4 import torch.nn.init as init
----> 5 from torchvision import models
      6 from torchvision.models.vgg import model_urls
      7 from collections import namedtuple

~\anaconda3\envs\OCR\lib\site-packages\torchvision\__init__.py in <module>
      2 
      3 from torchvision import models
----> 4 from torchvision import datasets
      5 from torchvision import ops
      6 from torchvision import transforms

~\anaconda3\envs\OCR\lib\site-packages\torchvision\datasets\__init__.py in <module>
      7 from .svhn import SVHN
      8 from .phototour import PhotoTour
----> 9 from .fakedata import FakeData
     10 from .semeion import SEMEION
     11 from .omniglot import Omniglot

~\anaconda3\envs\OCR\lib\site-packages\torchvision\datasets\fakedata.py in <module>
      1 import torch
      2 from .vision import VisionDataset
----> 3 from .. import transforms
      4 
      5 

~\anaconda3\envs\OCR\lib\site-packages\torchvision\transforms\__init__.py in <module>
----> 1 from .transforms import *

~\anaconda3\envs\OCR\lib\site-packages\torchvision\transforms\transforms.py in <module>
     13 import warnings
     14 
---> 15 from . import functional as F
     16 
     17 

~\anaconda3\envs\OCR\lib\site-packages\torchvision\transforms\functional.py in <module>
      1 import torch
      2 import math
----> 3 from PIL import Image, ImageOps, ImageEnhance, __version__ as PILLOW_VERSION
      4 try:
      5     import accimage

~\anaconda3\envs\OCR\lib\site-packages\PIL\ImageOps.py in <module>
     22 
     23 from . import Image
---> 24 from ._util import isStringType
     25 
     26 #

ImportError: cannot import name 'isStringType'`

**Comment by rkcosmos** [comment]
Is your pillow version Pillow<7.0?

**Comment by Sharan1712** [comment]
Pillow version is 7.1.2

**Comment by rkcosmos** [comment]
It crashes with another package, try downgrade it.

**Comment by rkcosmos** [comment]
another solution is to upgrage torchvision to version >=0.5
