### ISSUE TITLE
when load arabic model as a custom model to compare that the character_list is correct in order

### ISSUE THREAD

**Issue by Mahmuod1** [JaidedAI/EasyOCR#800]
i tried to load the arabic.pth model yours model but i got error mismatch when loading state_dict 
i think the layers in the custom_model.py doesn't match with the Arabic.pth model 
and this is the error 

RuntimeError: Error(s) in loading state_dict for Model:
	Missing key(s) in state_dict: "FeatureExtraction.ConvNet.0.weight", "FeatureExtraction.ConvNet.0.bias", "FeatureExtraction.ConvNet.3.weight", "FeatureExtraction.ConvNet.3.bias", "FeatureExtraction.ConvNet.6.weight", "FeatureExtraction.ConvNet.6.bias", "FeatureExtraction.ConvNet.8.weight", "FeatureExtraction.ConvNet.8.bias", "FeatureExtraction.ConvNet.11.weight", "FeatureExtraction.ConvNet.12.weight", "FeatureExtraction.ConvNet.12.bias", "FeatureExtraction.ConvNet.12.running_mean", "FeatureExtraction.ConvNet.12.running_var", "FeatureExtraction.ConvNet.14.weight", "FeatureExtraction.ConvNet.15.weight", "FeatureExtraction.ConvNet.15.bias", "FeatureExtraction.ConvNet.15.running_mean", "FeatureExtraction.ConvNet.15.running_var", "FeatureExtraction.ConvNet.18.weight", "FeatureExtraction.ConvNet.18.bias". 
	Unexpected key(s) in state_dict: "FeatureExtraction.ConvNet.conv0_1.weight", "FeatureExtraction.ConvNet.bn0_1.weight", "FeatureExtraction.ConvNet.bn0_1.bias", "FeatureExtraction.ConvNet.bn0_1.running_mean", "FeatureExtraction.ConvNet.bn0_1.running_var", "FeatureExtraction.ConvNet.bn0_1.num_batches_tracked", "FeatureExtraction.ConvNet.conv0_2.weight", "FeatureExtraction.ConvNet.bn0_2.weight", "FeatureExtraction.ConvNet.bn0_2.bias", "FeatureExtraction.ConvNet.bn0_2.running_mean", "FeatureExtraction.ConvNet.bn0_2.running_var", "FeatureExtraction.ConvNet.bn0_2.num_batches_tracked", "FeatureExtraction.ConvNet.layer1.0.conv1.weight", "FeatureExtraction.ConvNet.layer1.0.bn1.weight", "FeatureExtraction.ConvNet.layer1.0.bn1.bias", "FeatureExtraction.ConvNet.layer1.0.bn1.running_mean", "FeatureExtraction.ConvNet.layer1.0.bn1.running_var", "FeatureExtraction.ConvNet.layer1.0.bn1.num_batches_tracked", "FeatureExtraction.ConvNet.layer1.0.conv2.weight", "FeatureExtraction.ConvNet.layer1.0.bn2.weight", "FeatureExtraction.ConvNet.layer1.0.bn2.bias", "FeatureExtraction.ConvNet.layer1.0.bn2.running_mean", "FeatureExtraction.ConvNet.layer1.0.bn2.running_var", "FeatureExtraction.ConvNet.layer1.0.bn2.num_batches_tracked", "FeatureExtraction.ConvNet.layer1.0.downsample.0.weight", "FeatureExtraction.ConvNet.layer1.0.downsample.1.weight", "FeatureExtraction.ConvNet.layer1.0.downsample.1.bias", "FeatureExtraction.ConvNet.layer1.0.downsample.1.running_mean", "FeatureExtraction.ConvNet.layer1.0.dow...

**Comment by Mahmuod1** [comment]
thx i solved it

**Comment by akashlp27** [comment]
hey @Mahmuod1 , could u help in understanding how did u solve it

**Comment by ftmasadi** [comment]
> hey @Mahmuod1 , could u help in understanding how did u solve it

Are you solve this error?

**Comment by ftmasadi** [comment]
I use the above model for train, but during the test, I encounter a mismatch problem and I don't know how to solve this problem. @Mahmuod1

**Comment by ftmasadi** [comment]
Should I use a space in the .yaml file in the test?
Doesn't adding a white space make it not detect correctly in the test step? @Mahmuod1
