### ISSUE TITLE
Details about recognition model architecture

### ISSUE THREAD

**Issue by RaiAmanRai** [JaidedAI/EasyOCR#802]
Hi @rkcosmos , I noticed that there have been two different architectures used for recognition models. 

What's the motive behind that and why only some selected languages chosen for the bigger and complex one.

Also, could you provide the python file for the bigger architecture, just like the one you mentioned [here in custom_example.zip](https://jaided.ai/easyocr/modelhub/)

**Comment by rkcosmos** [comment]
Bigger models were released first and they are too slow for most people. Smaller one is much faster with comparable accuracy.

**Comment by TheMegistone4Ever** [comment]
> Bigger models were released first and they are too slow for most people. Smaller one is much faster with comparable accuracy.

Hello< where I can get smaller models?
