### ISSUE TITLE
Custom model fine-tuning on initial weights

### ISSUE THREAD

**Issue by vemchance** [JaidedAI/EasyOCR#818]
Thanks for the awesome package. 

I'm trying to fine-tune EasyOCR and create a custom model, however I don't necessarily want to create an entirely new model. I'd like to fine-tune it to recognise more specific fonts for my use case. EasyOCR performs the best for my use case out of other packages but could be improved I think.

I have generated data to create my own custom model, but find the results are worse. I've generated enough data and can only assume the recognition is trained from scratch when I create my own custom model, but haven't been able to determine if this is actually the case from the docs here.

Is there a way to use the original weights from EasyOCR or simply fine-tune the model with new, additional data? Or should I look at generating more data which is broader than my use case to try and replicate the same best performance of EasyOCR?

**Comment by rkcosmos** [comment]
you can finetune from existing model by providing a model path to `saved_model` in config file. See this [config file](saved_model) for example .

**Comment by vemchance** [comment]
Thank you! The link you gave didn't work but I figured it out using the same method.

**Comment by rkcosmos** [comment]
for other people who see this, this is the intended link https://github.com/JaidedAI/EasyOCR/blob/master/trainer/config_files/en_filtered_config.yaml
