### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by RicketyRick** [JaidedAI/EasyOCR#82]
Hi! I run into an out of memory error right from the start.

Build is the current pip install and the current developer build.
Testprogram is your simple example:
import easyocr
reader = easyocr.Reader(['de'])
reader.readtext('test.png')

Cuda version 10.1
torch 1.5.1
torchvision 0.6.1

After start (and a clean reboot of my machine) I get: 
RuntimeError: CUDA out of memory. Tried to allocate 856.00 MiB (GPU 0; 4.00 GiB total capacity; 1.69 GiB already allocated; 310.80 MiB free; 2.65 GiB reserved in total by PyTorch)

Is it even possible to use easyOCR with 4GB GPU memory?

Thank you!

**Comment by rkcosmos** [comment]
It uses +-2GB on my machine.
