### ISSUE TITLE
Redundant character in fa_char.txt

### ISSUE THREAD

**Issue by Serjio42** [JaidedAI/EasyOCR#821]
It looks like the redundancy in charset [fa_char.txt](https://github.com/JaidedAI/EasyOCR/blob/master/easyocr/character/fa_char.txt) :
There is `اً` in the 34th line, that is combination of `ا` (from line 2) and diacritic symbol ` ً` from line 40.
But these symbols are exist standalone in the charset. And looks like we actually can combine many letters with this diacritic symbol ` ً` , but only `اً` in charset.

**Comment by rkcosmos** [comment]
can you create a pull request to delete combined character out?

**Comment by Serjio42** [comment]
Sure, here it is.
