### ISSUE TITLE
About common words OCR to wrong words on traditional Chinese.

### ISSUE THREAD

**Issue by MAN-GOR** [JaidedAI/EasyOCR#842]
I found that some words will OCR to other wrong words on traditional Chinese.
Since there are common words OCR to wrong words, there are already 1500+ images with wrong OCR for one word.
I keep these images, can I compress them and upload them to the cloud to send them to you?
Maybe you can retrain them?

**Comment by rkcosmos** [comment]
hi, you can also retrain it yourselves (see https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md)
