### ISSUE TITLE
Vertical Japanese support?

### ISSUE THREAD

**Issue by polm** [JaidedAI/EasyOCR#85]
Hello, I tried the model on vertical Japanese writing and the output was not great. Am I doing something wrong, and if not, are there plans to support it?

**Comment by rkcosmos** [comment]
Yeah, vertical text is not supported yet. I know it is important for Japanese and Chinese. I'll try to do it later. Cannot promise it to be fast though, I have a lot of work on hand.

**Comment by polm** [comment]
Great! No rush, just wanted to know if there were plans to support it at all.
