### ISSUE TITLE
[Question] List of supported image formats for the reader.

### ISSUE THREAD

**Issue by Sharzzz001** [JaidedAI/EasyOCR#868]
Can someone list the supported image formats for reader.readtext function. I know jpg, png work. Other than these are there any other formats that it supports?

**Comment by ftmasadi** [comment]
> Can someone list the supported image formats for reader.readtext function. I know jpg, png work. Other than these are there any other formats that it supports?

File extension support: png, jpg, tiff.

**Comment by Sharzzz001** [comment]
Thanks a lot!!
