### ISSUE TITLE
Process Time

### ISSUE THREAD

**Issue by adidevil** [JaidedAI/EasyOCR#88]
Great Work, Just a simple question
For a normal Image, It takes around 6-7 seconds of time to give output with gpu, any method to make it faster.

**Comment by rkcosmos** [comment]
There are 2 processes. The first is loading model to memory. This need to be done only once for multiple images. Out of 6-7 seconds, I guess 5-6 is from this process.

`reader = easyocr.Reader(['ch_tra','en'])`

The second is getting text. This is generally fast for normal image (not too many text). You can make it faster if your GPU have a lot of RAM by setting batch_size more than 1

`reader.readtext('chinese.jpg', batch_size = 4)`
