### ISSUE TITLE
Fine Tuning on Custom Dataset - Thai 

### ISSUE THREAD

**Issue by MdotO** [JaidedAI/EasyOCR#896]
Hi ,
       I had a look at the current training scripts and aim to fine tune the thai model, with weight thai_g1.pth, on our custom dataset.
To actually load the weights, which will serve as pretrained weights, I need to know the thai_filtered.yml file and also other opt arguments, much like the "en_filtered.yml" which was present in the sample train folder/trainer.ipynb

I could create / experiment with my own configs but the problem is that my custom dataset is small . Thus I would like to freeze most of the layers and train for the last few layers. Again, all this would depend on me being able to properly load weights/knowing the model architecture. 
Can you provide those opts/configs for the thai model you trained? Also additionally, i think it will be useful to share these configs alongside the weights for other languages as well! 

I was looking at the the **easyocr/model/model.py** file and we need only supply inp,out and hidden size . Can you please confirm whether this is the right direction ?

Thanks!

**Comment by khawar-islam** [comment]
@MdotO Did you find something valuable to solve your problem?

**Comment by MdotO** [comment]
> @MdotO Did you find something valuable to solve your problem?

Hi Khawar. Yeah actually the model.py file I referenced above + the config.py file was enough to actually construct the thai.yml file that the author used and then I simply retrained it using the trainer script. You can choose to use a new head or original authors model head in retraining. I did need to make some small tweaks otherwise it lead to bugs.

Please let me know if you have already resolved this otherwise I can go into more details if you deem it necessary

**Comment by khawar-islam** [comment]
Dear @MdotO I have also started fine-tuning process, If you know answers. please let me know. It would be extremely helpful for me.

Q1) What is the impact of `new_prediction: True` and `new_prediction: False` while fine-tuning existing EasyOCR model?
Q2) Are there any possibility to while fine-tuning we can increase the size of language dictionary? there are several characters missing in existing models. I tried but failed because EasyOCR throws exception tensor `mismatch` error.
Q3) Did your Thai model is enough to recognize english, numbers and thai language in an image?

**Comment by MdotO** [comment]
Note: I am assuming you are only talking about training the recognition/classification model and not the detector model


1) Prediction new = True is meant if you are adding different set of characters in config.py(either less or more or in a different order) for whatever language. It seems that setting this to True will be good for your case since for your case loads of characters are missing. 
2) You can add those characters in your custom_config.py as stated in the trainer [documentation](https://github.com/JaidedAI/EasyOCR/blob/master/custom_model.md) and use the provided config.py in source code as reference as to how to construct them. Regarding the error, yeah I believe there is an issue when you provide new characters in custom config but don't specify prediction new =True.
3) The current thai model provided by author can recognize all English text + (base 10) digits + Majority of thai characters (if not all). For my case actually, I had to drop a few characters with intention of making things easier for model to train.
[train_infer.zip](https://github.com/JaidedAI/EasyOCR/files/11315970/train_infer.zip)

I have provided my attached custom thai .py and .yaml and filtered.yaml files for your reference in zip format(as github doesnt allow some extensions of these files)
The thai.py is the main source code file used in inference and training for model cosntruction.
The filtered.yaml is used in training/evaluation while thai.yaml is used in inference. Please note that the overall character list in training yaml and inference yaml file must match!
