### ISSUE TITLE
weight of size [64, 3, 3, 3], expected input[10, 1, 64, 704] to have 3 channels, but got 1 channels instead

### ISSUE THREAD

**Issue by Shaiken** [JaidedAI/EasyOCR#913]
我使用自己訓練的.pth
無法讀取測試
有人能幫助嗎??

i got a best .pth
try test image and error preds

preds = model(image, text_for_pred) <--

參數:
number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €"
lang_char: '一堆中文字'
experiment_name: 'cus_filtered' #'en_filtered'
train_data: './all_data'
valid_data: './all_data/cus_val_filtered' #'all_data/en_val'
manualSeed: 1111
workers: 1
batch_size: 32 #32
num_iter: 300000
valInterval: 20000
saved_model: 'saved_models/cus_filtered/best_accuracy.pth' #'saved_models/cus_filtered/chinese.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: False
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'cus_train_filtered' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 34 
imgH: 64
imgW: 600
rgb: True #False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 3 #3
output_channel: 512 #256
hidden_size: 256 #256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False

**Comment by Shaiken** [comment]
我已找到問題，目前在訓練雖然支援rgb訓練，讀取模型卻只支援灰階，除了自己改tensor別無他法。

**Comment by pection** [comment]
Can you provide guidance on this? Maybe I will fix it.
