### ISSUE TITLE
How to restart training from the saved model iteration.pth?

### ISSUE THREAD

**Issue by Mani-mk-mk** [JaidedAI/EasyOCR#916]
I was using a custom dataset to train EasyOCR, which has seven segment display digits. The training worked well up until the 110000th iteration, however my runtime got disconnected in between and I now want to restart it from the saved checkpoint. 
So, could someone please explain or assist me ?

**Comment by Arunavameister** [comment]
In the configuration file, there is a parameter 'saved_model', you can put the path to the latest saved weight, for example : saved_model : 'saved_models/en_filtered/iter_110000.pth'

**Comment by Mani-mk-mk** [comment]
Hey man,

Thank you for your help; if it's okay with you, I have one more question.

The height and weight parameters are specified in the configuration file,
and I can see from the sample dataset that all the images are 64 pixels in
height and have a width of less than 600 pixels, which is also specified in
the configuration file.

Therefore, would using a picture whose height or width is more or less than
what is required lead to the creation of a poor model? So are the specified
parameters are threshold for width and height

Thank you for your help

**Comment by Arunavameister** [comment]
Yes, go ahead modify them!
