### ISSUE TITLE
Input type is cuda, but 'deform_conv_cuda.*.so' is not imported successfully.

### ISSUE THREAD

**Issue by arcb01** [JaidedAI/EasyOCR#922]
```python
reader = easyocr.Reader(['en'], gpu=True, detect_network='dbnet18')
```
I tried running the OCR using dbnet18 as a detection network. But got into that error.
Any idea?

- Python: 3.9.13
- PyTorch & CUDA: 1.9.1 + CUDA 11.1
- OS: Windows 10

**Comment by MuhammadRamzan4** [comment]
@arcb01 Facing the same issue, how did you resolve it?
