### ISSUE TITLE
 AttributeError: '_MultiProcessingDataLoaderIter' object has no attribute 'next'

### ISSUE THREAD

**Issue by proclaim5584** [JaidedAI/EasyOCR#923]
Hi.
I am currently trying to train my own model.
I obtained the dataset as required and modified the config file. However, I get this error when trying to train.
I have already tried to decrease workers in config file.
I also tried to modify the dataset.py file, line 101 from
image, text = data_loader_iter.next() 
to
image, text = next(data_loader_iter)

However, the error persist.

Thanks

**Comment by AryaPulkit** [comment]
I am also facing the same issue.

**Comment by elahedaneshmand** [comment]
I have same issue, Do  you solve this problem?

**Comment by elahedaneshmand** [comment]
@JaidedTeam 
Can You please help us for this type of error?

**Comment by proclaim5584** [comment]
Nothing yet?

**Comment by masoudMZB** [comment]
same here.

**Comment by masoudMZB** [comment]
To solve this problem comment a line and change it to this code : 

```
# image, text = data_loader_iter.next()
 image, text = next(data_loader_iter)
```

```
# image, text = self.dataloader_iter_list[i].next()
image, text = next(self.dataloader_iter_list[i])
```

and if you run this code in Colab. you should restart runtime after commenting these lines because editing py file doesn't affect . you should restart runtime too
