### ISSUE TITLE
AttributeError: 'numpy.float64' object has no attribute 'lower'

### ISSUE THREAD

**Issue by proclaim5584** [JaidedAI/EasyOCR#936]
Hi.
I am trying to train a model. I have created a dataset as required and I tried to run the training script.
This is the result:
```

 
 File "Downloads/EasyOCR-master/trainer/start_train.py", line 30, in <module>
    train(opt, amp=False)
  File "Downloads/EasyOCR-master/trainer/train.py", line 40, in train
    train_dataset = Batch_Balanced_Dataset(opt)
  File "Downloads/EasyOCR-master/trainer/dataset.py", line 56, in __init__
    _dataset, _dataset_log = hierarchical_dataset(root=opt.train_data, opt=opt, select_data=[selected_d])
  File "Downloads/EasyOCR-master/trainer/dataset.py", line 132, in hierarchical_dataset
    dataset = OCRDataset(dirpath, opt)
  File "Downloads/EasyOCR-master/trainer/dataset.py", line 164, in __init__
    if re.search(out_of_char, label.lower()):
AttributeError: 'numpy.float64' object has no attribute 'lower'
```
I found that this is correlated with my dataset containing only numbers (so the labels.csv are only numbers). In fact, If I try to modify my dataset and add some letters, the error is gone.
But I don't need to add letters, my dataset are composed by numbers only.

I think I need to modify dataset.py in some way.
Furthermore, for some reason, when I trained another model some weeks ago with a similar dataset containing only numbers, I hadn't this error. I don't know what happened in meantime. I only modified some model parameters in opt and nothing more.

Thanks.

**Comment by 2281** [comment]
@proclaim5584 Hi!
I have the same problem. Did you solve it ?
I wrapped the numbers in single quotes. But I'm not sure this is a good solution
