### ISSUE TITLE
download model file is corrupted

### ISSUE THREAD

**Issue by AdamBear** [JaidedAI/EasyOCR#95]
### I changed code to ignore the md5 check, but the following error is raised:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 496857 more bytes. The file might be corrupted.

**Comment by rkcosmos** [comment]
Try download manually from links in README.

**Comment by Vijayabhaskar96** [comment]
The most probable situation is your network failed to download the file completely, rerun the code it should automatically re-download the model if the checksum failed.
