### ISSUE TITLE
Pillow 7.0.0 support

### ISSUE THREAD

**Issue by apiszcz** [JaidedAI/EasyOCR#99]
pip install is removing Pillow 7.0 and install 6.2.2, is there planned support for Pillow 7.0?

**Comment by rkcosmos** [comment]
Currently Pillow>=7 crashes with another standard package (don't remember which one). I wait for them to resolve and we can have last version of everything.

**Comment by korakot** [comment]
@apizcz I have tested it with Google Colab.

You can install it with `pip install easyocr --no-deps`. It will work with Pillow 7.0 with no error.

**Comment by apiszcz** [comment]
Nice, great thank you, Pillow 7.2.0 out.

**Comment by rkcosmos** [comment]
It was a conflict with torchvision. (see [pytorch issue](https://github.com/pytorch/vision/issues/1712) ) Now torchvision released version 0.5. Everything can be used with lastest version. will update pip package later

**Comment by apiszcz** [comment]
Got, it, apparently I'm on 0.6.0

```
>>> import torchvision
>>> torchvision.__version__
'0.6.0'
```

facebook, amazing work!

**Comment by rkcosmos** [comment]
wow, software development is fast!
